export const RDI_DURATION_MIN_SECONDS = 0
export const RDI_DURATION_MAX_SECONDS = 24 * 60 * 60

export const RDI_DRY_CONTACT_DELAY_MIN_SECONDS = RDI_DURATION_MIN_SECONDS
export const RDI_DRY_CONTACT_DELAY_MAX_SECONDS = RDI_DURATION_MAX_SECONDS
export const RDI_DRY_CONTACT_TEST_DURATION_MIN_SECONDS = 1
export const RDI_DRY_CONTACT_TEST_DURATION_MAX_SECONDS = RDI_DURATION_MAX_SECONDS
