const enUSLabels = {
  rdiSettings: 'RDI Settings',
  basicInfo: 'Basic Info',
  statusLabel: 'Status',
  deviceName: 'Device Name',
  deviceId: 'Device ID',
  addedAt: 'Added At',
  lastHeartbeat: 'Last Heartbeat',
  telemetry: 'Telemetry',
  system: 'System',
  configuredParameters: 'Configured Parameter Settings',
  alarm: 'Alarm',
  dryContact: 'Output Node 01',
  notification: 'Email Notifications',
  notificationFallbackHint:
    'If device-level alarm emails are blank, global warning-email recipients from system settings will receive the message.',
  field: 'Global',
  commands: 'Commands',
  pid: 'PID',
  firmware: 'Firmware',
  description: 'Device description',
  online: 'Online',
  offline: 'Offline',
  connection: 'Connection',
  interval: 'Device auto-reporting interval (s)',
  temperatureUnit: 'Temperature Unit',
  celsius: 'Celsius',
  fahrenheit: 'Fahrenheit',
  sensor1: 'Temperature Sensor T1',
  sensor2: 'Temperature Sensor T2',
  enabled: 'Enabled',
  lower: 'Lower',
  upper: 'Upper',
  alarmRange: 'Alarm range',
  currentStatus: 'Current Level',
  currentValue: 'Current Value',
  duration: 'Duration',
  switch1: 'Input Node 1',
  switch2: 'Input Node 2',
  mode: 'Mode',
  switchAlarmLevel: 'Alarm Trigger Level',
  // pending-customer-confirm REQ-22: customer wording ambiguous (effective time vs delay)
  triggerEffectiveTime: 'Trigger Effective Time',
  poweredOn: 'Powered on',
  poweredOff: 'Powered off',
  disabled: 'Disabled',
  alarmLevel: 'Output Level During Alarm',
  normalLevel: 'Output Level When Not in Alarm',
  alarmDelay: 'Alarm Delay',
  normalDelay: 'Recovery Delay',
  high: 'High',
  low: 'Low',
  temperatureAlarmNotice: 'Temperature alarm notification',
  switchAlarmNotice: 'Switch alarm notification',
  warrantyAlarmNotice: 'Warranty alarm notification',
  temperatureMail: 'Temperature emails',
  switchMail: 'Switch emails',
  warrantyMail: 'Warranty emails',
  sensor1Mail: 'T1 alarm emails',
  sensor2Mail: 'T2 alarm emails',
  switch1Mail: 'NC1 alarm emails',
  switch2Mail: 'NC2 alarm emails',
  save: 'Save',
  apply: 'Apply to device',
  refresh: 'Refresh',
  sendHigh: 'Set high',
  sendLow: 'Set low',
  test: 'Test output',
  testDuration: 'Test duration',
  location: 'Location',
  installationAddress: 'Installation address',
  installationDate: 'Installation date',
  installerCompany: 'Installer company',
  installerContact: 'Installer contact',
  installerName: 'Installer name',
  installerPhone: 'Installer phone',
  installerEmail: 'Installer email',
  controllerSerialNumber: 'Controller serial number',
  technician: 'Technician',
  customer: 'Customer',
  email: 'Email',
  phone: 'Phone',
  warranty: 'Warranty',
  extendedFields: 'Extended fields',
  nFields: 'N fields',
  swFields: 'SW fields',
  empty: 'No data available',
  saved: 'Saved',
  sent: 'Sent',
  energy: 'Energy',
  latest: 'Latest',
  delta: 'Delta',
  dataPoints: 'Data points',
  minMax: 'Min / Max',
  historyChart: 'History chart',
  historyLoadFailed: 'History data could not be loaded. Retry these series:',
  historyPartialData: 'Only part of the history could be loaded for:',
  historyGapDetected: 'Sampling gaps over 90 seconds were detected in:',
  historyGapNotConnected: 'The chart intentionally leaves detected gaps unconnected.',
  valueAxis: 'Value',
  switchAxis: 'Switch',
  exportData: 'Export data',
  historyKey: 'History key',
  exportFormat: 'Export format',
  load: 'Load',
  change: 'Change',
  share: 'Share',
  copy: 'Copy',
  createShare: 'Create share',
  expires: 'Expires',
  ota: 'OTA',
  otaPackage: 'OTA package',
  firmwareUrl: 'Firmware URL',
  version: 'Version',
  size: 'Size',
  md5: 'MD5',
  otaMissingFields: 'Missing OTA fields',
  otaReadyHint: 'Select a package or fill OTA package details before sending.',
  reloadPackages: 'Reload packages',
  checkUpdate: 'Check update',
  useLatestFirmware: 'Use latest firmware',
  sendField: 'Send field settings',
  unbindDevice: 'Unbind device',
  factoryReset: 'Factory reset',
  confirmUnbind: 'Send the unbind platform account command to this device?',
  confirmFactoryReset: 'Send the factory reset command to this device?',
  confirm: 'Confirm',
  cancel: 'Cancel',
  ledStatus: 'LED1 Status',
  ledOff: 'Off',
  ledSolid: 'Solid',
  ledSlowBlink: 'Slow Blink',
  ledFastBlink: 'Fast Blink',
  ledError: 'Error',
  missingValuePlaceholder: '--',
  // REQ-48：用电量统计 Tab。
  powerUsage: 'Power Usage',
  powerUsageDescription:
    'Cumulative electricity consumption derived from the electricity_consumption telemetry key.',
  cumulativeUsage: 'Cumulative usage',
  today: 'Today',
  thisWeek: 'This week',
  thisMonth: 'This month',
  // 时段下拉的键名沿用 useRdiHistory 里既有的 last1Hour/last1Day/last1Week/last30Days，
  // 文案则按客户视角写成 Today / This week / This month，避免出现两套时段说法。
  last1Hour: 'Last 1 hour',
  last1Day: 'Today',
  last1Week: 'This week',
  last30Days: 'This month',
  customRange: 'Custom range',
  excelFormat: 'Excel',
  csvFormat: 'CSV',
  // REQ-53：Field Setting 只读展示。
  fieldSettingsReadonlyTitle: 'Field Settings (read-only)',
  fieldSettingsFieldColumn: 'Field',
  fieldSettingsRawValueColumn: 'Raw value',
  fieldSettingsInterpretedValueColumn: 'Interpreted value',
  // REQ-47 分享有效期 + REQ-54 固件检查提示。
  oneDay: '1 day',
  sevenDays: '7 days',
  thirtyDays: '30 days',
  alreadyLatest: 'Firmware is already up to date',
  updateAvailable: 'Firmware update available'
} as const

export type LabelKey = keyof typeof enUSLabels

type RdiLabels = Record<LabelKey, string>

export const labels: Record<App.I18n.LangType, RdiLabels> = {
  'en-US': enUSLabels,
  'zh-CN': {
    ...enUSLabels,
    rdiSettings: 'RDI 设置',
    basicInfo: '基础信息',
    statusLabel: '状态',
    deviceName: '设备名称',
    deviceId: '设备 ID',
    addedAt: '添加时间',
    lastHeartbeat: '最后心跳',
    telemetry: '遥测',
    system: '系统',
    configuredParameters: '已保存参数设定',
    alarm: '告警',
    dryContact: '输出节点 01',
    notification: '邮件告警通知',
    notificationFallbackHint: '设备级告警邮箱为空时，将使用系统设置中的全局告警邮箱接收邮件。',
    field: '全局',
    commands: '命令',
    firmware: '固件',
    description: '设备描述',
    online: '在线',
    offline: '离线',
    connection: '连接',
    interval: '设备自动上报间隔 (秒)',
    temperatureUnit: '温度单位',
    celsius: '摄氏度',
    fahrenheit: '华氏度',
    sensor1: 'T1 温度传感器',
    sensor2: 'T2 温度传感器',
    enabled: '启用',
    lower: '下限',
    upper: '上限',
    alarmRange: '告警范围',
    currentStatus: '当前电平',
    currentValue: '当前值',
    duration: '持续时间',
    switch1: '输入节点 1',
    switch2: '输入节点 2',
    mode: '模式',
    switchAlarmLevel: '告警触发电平',
    triggerEffectiveTime: '触发生效时间',
    poweredOn: '通电告警',
    poweredOff: '断电告警',
    disabled: '禁用',
    alarmLevel: '告警时输出电平',
    normalLevel: '非告警时输出电平',
    alarmDelay: '告警延时',
    normalDelay: '恢复延时',
    high: '高',
    low: '低',
    temperatureAlarmNotice: '温度告警通知',
    switchAlarmNotice: '开关告警通知',
    warrantyAlarmNotice: '保修告警通知',
    temperatureMail: '温度告警邮箱',
    switchMail: '开关告警邮箱',
    warrantyMail: '保修告警邮箱',
    sensor1Mail: 'T1 告警邮箱',
    sensor2Mail: 'T2 告警邮箱',
    switch1Mail: 'NC1 告警邮箱',
    switch2Mail: 'NC2 告警邮箱',
    save: '保存',
    apply: '下发到设备',
    refresh: '刷新',
    sendHigh: '设置高电平',
    sendLow: '设置低电平',
    test: '测试输出',
    testDuration: '测试时长',
    location: '位置',
    installationAddress: '安装地址',
    installationDate: '安装日期',
    installerCompany: '安装公司',
    installerContact: '安装联系人',
    installerName: '安装人员',
    installerPhone: '安装电话',
    installerEmail: '安装邮箱',
    controllerSerialNumber: '控制器序列号',
    technician: '技术人员',
    customer: '客户',
    email: '邮箱',
    phone: '电话',
    warranty: '保修',
    extendedFields: '扩展字段',
    nFields: 'N 字段',
    swFields: 'SW 字段',
    empty: '暂无数据',
    saved: '已保存',
    sent: '已发送',
    energy: '能耗',
    latest: '最新值',
    delta: '变化量',
    dataPoints: '数据点',
    minMax: '最小 / 最大',
    historyChart: '历史图表',
    historyLoadFailed: '历史数据加载失败，请重试以下序列：',
    historyPartialData: '以下序列只加载到了部分历史数据：',
    historyGapDetected: '以下序列检测到超过 90 秒的采样缺口：',
    historyGapNotConnected: '图表会在检测到的缺口处主动断线，不会伪装成连续数据。',
    valueAxis: '数值',
    switchAxis: '开关',
    exportData: '导出数据',
    historyKey: '历史字段',
    exportFormat: '导出格式',
    load: '加载',
    change: '切换',
    share: '分享',
    copy: '复制',
    createShare: '创建分享',
    expires: '过期时间',
    otaPackage: 'OTA 包',
    firmwareUrl: '固件地址',
    version: '版本',
    size: '大小',
    otaMissingFields: '缺少 OTA 字段',
    otaReadyHint: '选择升级包或填写 OTA 包信息后再下发。',
    reloadPackages: '重新加载升级包',
    checkUpdate: '检查更新',
    useLatestFirmware: '使用最新固件',
    sendField: '下发字段设置',
    unbindDevice: '解绑设备',
    factoryReset: '恢复出厂设置',
    confirmUnbind: '确认向该设备下发解绑平台账号命令？',
    confirmFactoryReset: '确认向该设备下发恢复出厂设置命令？',
    confirm: '确认',
    cancel: '取消',
    ledStatus: 'LED1 状态',
    ledOff: '熄灭',
    ledSolid: '常亮',
    ledSlowBlink: '慢闪',
    ledFastBlink: '快闪',
    ledError: '错误',
    missingValuePlaceholder: '--',
    powerUsage: '用电量统计',
    powerUsageDescription: '基于遥测键 electricity_consumption 计算的累计用电量。',
    cumulativeUsage: '累计用电量',
    last1Hour: '最近 1 小时',
    last1Day: '当日',
    last1Week: '本周',
    last30Days: '本月',
    excelFormat: 'Excel',
    csvFormat: 'CSV',
    today: '当日',
    thisWeek: '本周',
    thisMonth: '本月',
    customRange: '自定义范围',
    fieldSettingsReadonlyTitle: '字段设置（只读）',
    fieldSettingsFieldColumn: '字段',
    fieldSettingsRawValueColumn: '原始值',
    fieldSettingsInterpretedValueColumn: '解析值'
  },
  'fr-FR': {
    ...enUSLabels,
    rdiSettings: 'Parametres RDI',
    basicInfo: 'Informations de base',
    statusLabel: 'Statut',
    deviceName: 'Nom de l appareil',
    deviceId: 'ID appareil',
    addedAt: 'Ajoute le',
    lastHeartbeat: 'Dernier heartbeat',
    telemetry: 'Telemetrie',
    system: 'Systeme',
    configuredParameters: 'Parametres enregistres',
    alarm: 'Alarme',
    dryContact: 'Sortie 01',
    notification: 'Notifications email',
    notificationFallbackHint:
      'Si les e-mails d alarme de l appareil sont vides, les destinataires globaux des alertes dans les parametres systeme recevront le message.',
    field: 'Global',
    commands: 'Commandes',
    firmware: 'Firmware',
    description: 'Description de l appareil',
    online: 'En ligne',
    offline: 'Hors ligne',
    connection: 'Connexion',
    interval: 'Intervalle de rapport automatique (s)',
    temperatureUnit: 'Unite de temperature',
    celsius: 'Celsius',
    fahrenheit: 'Fahrenheit',
    sensor1: 'Capteur de temperature T1',
    sensor2: 'Capteur de temperature T2',
    enabled: 'Active',
    lower: 'Limite basse',
    upper: 'Limite haute',
    alarmRange: 'Plage d alarme',
    currentStatus: 'Niveau actuel',
    currentValue: 'Valeur actuelle',
    duration: 'Duree',
    switch1: 'Entree 1',
    switch2: 'Entree 2',
    mode: 'Mode',
    switchAlarmLevel: 'Niveau de declenchement',
    triggerEffectiveTime: "Delai de declenchement d'alarme",
    poweredOn: 'Alarme sous tension',
    poweredOff: 'Alarme hors tension',
    disabled: 'Desactive',
    alarmLevel: 'Niveau de sortie pendant alarme',
    normalLevel: 'Niveau de sortie hors alarme',
    alarmDelay: 'Delai d alarme',
    normalDelay: 'Delai de reprise',
    high: 'Haut',
    low: 'Bas',
    temperatureAlarmNotice: 'Notification alarme temperature',
    switchAlarmNotice: 'Notification alarme contact',
    warrantyAlarmNotice: 'Notification alarme garantie',
    temperatureMail: 'Emails temperature',
    switchMail: 'Emails contact',
    warrantyMail: 'Emails garantie',
    sensor1Mail: 'Emails alarme T1',
    sensor2Mail: 'Emails alarme T2',
    switch1Mail: 'Emails alarme NC1',
    switch2Mail: 'Emails alarme NC2',
    save: 'Enregistrer',
    apply: 'Appliquer a l appareil',
    refresh: 'Actualiser',
    sendHigh: 'Definir haut',
    sendLow: 'Definir bas',
    test: 'Tester la sortie',
    testDuration: 'Duree du test',
    location: 'Emplacement',
    installationAddress: 'Adresse d installation',
    installationDate: 'Date d installation',
    installerCompany: 'Societe d installation',
    installerContact: 'Contact d installation',
    installerName: 'Nom de l installateur',
    installerPhone: 'Telephone de l installateur',
    installerEmail: 'Email de l installateur',
    controllerSerialNumber: 'Numero de serie du controleur',
    technician: 'Technicien',
    customer: 'Client',
    email: 'Email',
    phone: 'Telephone',
    warranty: 'Garantie',
    extendedFields: 'Champs etendus',
    nFields: 'Champs N',
    swFields: 'Champs SW',
    empty: 'Aucune donnee',
    saved: 'Enregistre',
    sent: 'Envoye',
    energy: 'Energie',
    latest: 'Derniere valeur',
    delta: 'Variation',
    dataPoints: 'Points de donnees',
    minMax: 'Min / Max',
    historyChart: 'Graphique historique',
    historyLoadFailed: 'Impossible de charger les donnees historiques. Reessayez ces series :',
    historyPartialData: 'Seule une partie de l historique a pu etre chargee pour :',
    historyGapDetected: 'Des interruptions d echantillonnage de plus de 90 secondes ont ete detectees pour :',
    historyGapNotConnected: 'Le graphique laisse volontairement les interruptions detectees non reliees.',
    valueAxis: 'Valeur',
    switchAxis: 'Contact',
    exportData: 'Exporter les donnees',
    historyKey: 'Champ historique',
    exportFormat: 'Format export',
    load: 'Charger',
    change: 'Changer',
    share: 'Partager',
    copy: 'Copier',
    createShare: 'Creer un partage',
    expires: 'Expiration',
    ota: 'OTA',
    otaPackage: 'Package OTA',
    firmwareUrl: 'URL firmware',
    version: 'Version',
    size: 'Taille',
    md5: 'MD5',
    otaMissingFields: 'Champs OTA manquants',
    otaReadyHint: 'Selectionnez un package ou renseignez les details OTA avant l envoi.',
    reloadPackages: 'Recharger les packages',
    checkUpdate: 'Verifier mise a jour',
    useLatestFirmware: 'Utiliser le dernier firmware',
    sendField: 'Envoyer les reglages de champ',
    unbindDevice: 'Dissocier appareil',
    factoryReset: 'Reinitialisation usine',
    confirmUnbind: 'Envoyer la commande de dissociation de compte plateforme a cet appareil ?',
    confirmFactoryReset: 'Envoyer la commande de reinitialisation usine a cet appareil ?',
    confirm: 'Confirmer',
    cancel: 'Annuler',
    ledStatus: 'Etat LED1',
    ledOff: 'Eteinte',
    ledSolid: 'Fixe',
    ledSlowBlink: 'Clignotement lent',
    ledFastBlink: 'Clignotement rapide',
    ledError: 'Erreur',
    missingValuePlaceholder: '--',
    powerUsage: 'Consommation electrique',
    powerUsageDescription:
      'Consommation electrique cumulee derivee de la cle de telemetrie electricity_consumption.',
    cumulativeUsage: 'Consommation cumulee',
    last1Hour: 'Derniere heure',
    last1Day: 'Aujourd hui',
    last1Week: 'Cette semaine',
    last30Days: 'Ce mois',
    excelFormat: 'Excel',
    csvFormat: 'CSV',
    today: 'Aujourd hui',
    thisWeek: 'Cette semaine',
    thisMonth: 'Ce mois',
    customRange: 'Plage personnalisee',
    fieldSettingsReadonlyTitle: 'Reglages de champ (lecture seule)',
    fieldSettingsFieldColumn: 'Champ',
    fieldSettingsRawValueColumn: 'Valeur brute',
    fieldSettingsInterpretedValueColumn: 'Valeur interpretee'
  },
  'es-ES': {
    ...enUSLabels,
    rdiSettings: 'Configuracion RDI',
    basicInfo: 'Informacion basica',
    statusLabel: 'Estado',
    deviceName: 'Nombre del dispositivo',
    deviceId: 'ID del dispositivo',
    addedAt: 'Agregado el',
    lastHeartbeat: 'Ultimo heartbeat',
    telemetry: 'Telemetria',
    system: 'Sistema',
    configuredParameters: 'Parametros guardados',
    alarm: 'Alarma',
    dryContact: 'Salida 01',
    notification: 'Notificaciones por email',
    notificationFallbackHint:
      'Si los correos de alarma del dispositivo estan vacios, los destinatarios globales de alertas de la configuracion del sistema recibiran el mensaje.',
    field: 'Global',
    commands: 'Comandos',
    firmware: 'Firmware',
    description: 'Descripcion del dispositivo',
    online: 'En linea',
    offline: 'Fuera de linea',
    connection: 'Conexion',
    interval: 'Intervalo de reporte automatico (s)',
    temperatureUnit: 'Unidad de temperatura',
    celsius: 'Celsius',
    fahrenheit: 'Fahrenheit',
    sensor1: 'Sensor de temperatura T1',
    sensor2: 'Sensor de temperatura T2',
    enabled: 'Habilitado',
    lower: 'Limite inferior',
    upper: 'Limite superior',
    alarmRange: 'Rango de alarma',
    currentStatus: 'Nivel actual',
    currentValue: 'Valor actual',
    duration: 'Duracion',
    switch1: 'Entrada 1',
    switch2: 'Entrada 2',
    mode: 'Modo',
    switchAlarmLevel: 'Nivel de disparo',
    triggerEffectiveTime: 'Retardo de activacion de alarma',
    poweredOn: 'Alarma con energia',
    poweredOff: 'Alarma sin energia',
    disabled: 'Deshabilitado',
    alarmLevel: 'Nivel de salida en alarma',
    normalLevel: 'Nivel de salida sin alarma',
    alarmDelay: 'Retardo de alarma',
    normalDelay: 'Retardo de recuperacion',
    high: 'Alto',
    low: 'Bajo',
    temperatureAlarmNotice: 'Notificacion de alarma de temperatura',
    switchAlarmNotice: 'Notificacion de alarma de entrada',
    warrantyAlarmNotice: 'Notificacion de alarma de garantia',
    temperatureMail: 'Emails de temperatura',
    switchMail: 'Emails de entrada',
    warrantyMail: 'Emails de garantia',
    sensor1Mail: 'Emails de alarma T1',
    sensor2Mail: 'Emails de alarma T2',
    switch1Mail: 'Emails de alarma NC1',
    switch2Mail: 'Emails de alarma NC2',
    save: 'Guardar',
    apply: 'Aplicar al dispositivo',
    refresh: 'Actualizar',
    sendHigh: 'Definir alto',
    sendLow: 'Definir bajo',
    test: 'Probar salida',
    testDuration: 'Duracion de prueba',
    location: 'Ubicacion',
    installationAddress: 'Direccion de instalacion',
    installationDate: 'Fecha de instalacion',
    installerCompany: 'Empresa instaladora',
    installerContact: 'Contacto de instalacion',
    installerName: 'Nombre del instalador',
    installerPhone: 'Telefono del instalador',
    installerEmail: 'Email del instalador',
    controllerSerialNumber: 'Numero de serie del controlador',
    technician: 'Tecnico',
    customer: 'Cliente',
    email: 'Email',
    phone: 'Telefono',
    warranty: 'Garantia',
    extendedFields: 'Campos extendidos',
    nFields: 'Campos N',
    swFields: 'Campos SW',
    empty: 'Sin datos',
    saved: 'Guardado',
    sent: 'Enviado',
    energy: 'Energia',
    latest: 'Ultimo valor',
    delta: 'Delta',
    dataPoints: 'Puntos de datos',
    minMax: 'Min / Max',
    historyChart: 'Grafico historico',
    historyLoadFailed: 'No se pudieron cargar los datos historicos. Reintente estas series:',
    historyPartialData: 'Solo se pudo cargar parte del historial para:',
    historyGapDetected: 'Se detectaron interrupciones de muestreo de mas de 90 segundos en:',
    historyGapNotConnected: 'El grafico deja intencionadamente sin unir las interrupciones detectadas.',
    valueAxis: 'Valor',
    switchAxis: 'Entrada',
    exportData: 'Exportar datos',
    historyKey: 'Campo historico',
    exportFormat: 'Formato de exportacion',
    load: 'Cargar',
    change: 'Cambiar',
    share: 'Compartir',
    copy: 'Copiar',
    createShare: 'Crear compartido',
    expires: 'Expira',
    ota: 'OTA',
    otaPackage: 'Paquete OTA',
    firmwareUrl: 'URL del firmware',
    version: 'Version',
    size: 'Tamano',
    md5: 'MD5',
    otaMissingFields: 'Faltan campos OTA',
    otaReadyHint: 'Seleccione un paquete o complete los detalles OTA antes de enviar.',
    reloadPackages: 'Recargar paquetes',
    checkUpdate: 'Buscar actualizacion',
    useLatestFirmware: 'Usar ultimo firmware',
    sendField: 'Enviar ajustes de campo',
    unbindDevice: 'Desvincular dispositivo',
    factoryReset: 'Restablecimiento de fabrica',
    confirmUnbind: 'Enviar el comando para desvincular la cuenta de plataforma a este dispositivo?',
    confirmFactoryReset: 'Enviar el comando de restablecimiento de fabrica a este dispositivo?',
    confirm: 'Confirmar',
    cancel: 'Cancelar',
    ledStatus: 'Estado LED1',
    ledOff: 'Apagado',
    ledSolid: 'Fijo',
    ledSlowBlink: 'Parpadeo lento',
    ledFastBlink: 'Parpadeo rapido',
    ledError: 'Error',
    missingValuePlaceholder: '--',
    powerUsage: 'Consumo electrico',
    powerUsageDescription:
      'Consumo electrico acumulado derivado de la clave de telemetria electricity_consumption.',
    cumulativeUsage: 'Consumo acumulado',
    last1Hour: 'Ultima hora',
    last1Day: 'Hoy',
    last1Week: 'Esta semana',
    last30Days: 'Este mes',
    today: 'Hoy',
    thisWeek: 'Esta semana',
    thisMonth: 'Este mes',
    customRange: 'Rango personalizado',
    excelFormat: 'Excel',
    csvFormat: 'CSV',
    fieldSettingsReadonlyTitle: 'Ajustes de campo (solo lectura)',
    fieldSettingsFieldColumn: 'Campo',
    fieldSettingsRawValueColumn: 'Valor sin procesar',
    fieldSettingsInterpretedValueColumn: 'Valor interpretado'
  }
}

export const systemExtraFieldDefinitions = [
  { key: 'site_name' },
  { key: 'customer_name' },
  { key: 'maintenance_technician' },
  { key: 'contact_email' },
  { key: 'contact_phone' },
  { key: 'warranty_status' },
  { key: 'remark' }
] as const

export type SystemExtraFieldKey = (typeof systemExtraFieldDefinitions)[number]['key'] | string

const enUSSystemExtraLabels: Record<string, string> = {
  site_name: 'Site name',
  customer_name: 'Customer name',
  maintenance_technician: 'Maintenance technician',
  contact_email: 'Contact email',
  contact_phone: 'Contact phone',
  warranty_status: 'Warranty status',
  remark: 'Remark'
}

export const systemExtraFieldLabels: Record<App.I18n.LangType, Record<string, string>> = {
  'en-US': enUSSystemExtraLabels,
  'zh-CN': {
    site_name: '站点名称',
    customer_name: '客户名称',
    maintenance_technician: '维护人员',
    contact_email: '联系邮箱',
    contact_phone: '联系电话',
    warranty_status: '保修状态',
    remark: '备注'
  },
  'fr-FR': {
    site_name: 'Nom du site',
    customer_name: 'Nom du client',
    maintenance_technician: 'Technicien de maintenance',
    contact_email: 'Email de contact',
    contact_phone: 'Telephone de contact',
    warranty_status: 'Statut de garantie',
    remark: 'Remarque'
  },
  'es-ES': {
    site_name: 'Nombre del sitio',
    customer_name: 'Nombre del cliente',
    maintenance_technician: 'Tecnico de mantenimiento',
    contact_email: 'Email de contacto',
    contact_phone: 'Telefono de contacto',
    warranty_status: 'Estado de garantia',
    remark: 'Observacion'
  }
}
