const fs = require('fs');
const os = require('os');
const path = require('path');
const { expect } = require('chai');
const audit = require('../lib/production-placeholder-audit');
const { main } = require('../scripts/check_production_placeholders');

function fixture(files) {
  const root = fs.mkdtempSync(path.join(os.tmpdir(), 'aetherlink-placeholder-'));
  for (const [relative, source] of Object.entries(files)) {
    const target = path.join(root, ...relative.split('/'));
    fs.mkdirSync(path.dirname(target), { recursive: true });
    fs.writeFileSync(target, source);
  }
  return root;
}

function inventoryFor(paths) {
  return {
    listRepositoryPaths: () => paths.map(item => ({ path: item })),
    categoryFor: relative => /(?:^|\/)(?:tests?|docs?)(?:\/|$)|\.test\./.test(relative) ? 'test' : 'source',
    moduleFor: relative => relative.split('/')[0],
    generateInventory: () => { throw new Error('mutating inventory generator must not run'); }
  };
}

describe('production placeholder gate contract [00_production_placeholder_gate_contract]', function () {
  it('reuses inventory and follows only production frontend, backend, and broker imports', function () {
    const files = {
      'frontend/src/main.ts': "import './live'\n",
      'frontend/src/live.ts': 'export const live = true\n',
      'frontend/src/unreachable.ts': 'throw new Error("not implemented")\n',
      'backend/main.go': 'package main\nimport _ "aetherlink-iot/backend/internal/live"\n',
      'backend/internal/live/live.go': 'package live\n',
      'backend/internal/dead/dead.go': 'package dead\n',
      'mqtt-broker/cmd/gmqttd/main.go': 'package main\nimport _ "github.com/DrmagicE/gmqtt/plugin/live"\n',
      'mqtt-broker/plugin/live/live.go': 'package live\n',
      'backend/internal/roadmap/future.go': 'package roadmap\n',
      'backend/tests/fake.go': 'package tests\n'
    };
    const root = fixture(files);
    try {
      const paths = Object.keys(files);
      const catalog = audit.buildProductionCatalog({ projectRoot: root, inventory: inventoryFor(paths) });
      expect(catalog.reachable).to.have.members([
        'frontend/src/main.ts', 'frontend/src/live.ts', 'backend/main.go',
        'backend/internal/live/live.go', 'mqtt-broker/cmd/gmqttd/main.go', 'mqtt-broker/plugin/live/live.go'
      ]);
      expect(catalog.cataloged).not.to.include.members([
        'backend/internal/roadmap/future.go', 'backend/tests/fake.go'
      ]);
      expect(catalog.reachable).not.to.include.members([
        'frontend/src/unreachable.ts', 'backend/internal/dead/dead.go'
      ]);
    } finally { fs.rmSync(root, { recursive: true, force: true }); }
  });

  it('requires both a generated family and a generator marker for exemption', function () {
    const generated = '// Code generated by gorm. DO NOT EDIT.\npackage model\n';
    expect(audit.isGeneratedExempt('backend/internal/model/demo.gen.go', generated)).to.equal(true);
    expect(audit.isGeneratedExempt('backend/internal/model/demo.gen.go', 'package model\n')).to.equal(false);
    expect(audit.isGeneratedExempt('backend/internal/service/demo.go', generated)).to.equal(false);
  });

  it('detects all four false-success rule families with stable counts', function () {
    const source = [
      'package sample',
      'func CreateThing() error {',
      '  return nil',
      '}',
      'func ReadThing() error {',
      '  return errors.New("not implemented")',
      '}',
      'func PublishThing() map[string]string {',
      '  _ = client.Publish("topic")',
      '  return map[string]string{"status": "delivered"}',
      '}'
    ].join('\n');
    const findings = audit.findPlaceholderFindings('backend/internal/service/sample.go', source);
    expect(findings.map(item => item.ruleId)).to.have.members(audit.DEFAULT_RULES);
    expect(new Set(findings.map(item => item.fingerprint)).size).to.equal(4);
  });

  it('reconciles exact exemptions and fails changed, expired, malformed, and stale entries', function () {
    const finding = audit.findPlaceholderFindings(
      'backend/internal/service/sample.go',
      'package sample\nfunc Read() error {\n return errors.New("not implemented")\n}'
    )[0];
    const exact = { ruleId: finding.ruleId, path: finding.path, fingerprint: finding.fingerprint,
      reason: 'tracked upstream', owner: 'platform', expires: '2099-01-01' };
    const accepted = audit.reconcileAllowlist([finding], { entries: [exact], errors: [] }, new Date('2026-09-09'));
    expect(accepted).to.include.keys('allowed', 'violations', 'staleAllowlist', 'errors');
    expect(accepted.allowed).to.have.length(1);
    const changed = audit.reconcileAllowlist([finding], { entries: [{ ...exact, fingerprint: 'a'.repeat(64) }], errors: [] });
    expect(changed.violations).to.have.length(1);
    expect(changed.staleAllowlist).to.have.length(1);
    const expired = audit.reconcileAllowlist([finding], { entries: [{ ...exact, expires: '2020-01-01' }], errors: [] });
    expect(expired.errors[0].reason).to.equal('expired-allowlist-entry');
    const malformed = audit.loadAllowlist('fixture', { readFile: () => '{"version":2,"entries":[]}' });
    expect(malformed.errors[0].reason).to.equal('invalid-allowlist-schema');
    const stale = audit.reconcileAllowlist([], { entries: [exact], errors: [] });
    expect(stale.staleAllowlist).to.deep.equal([exact]);
  });

  it('reconciles audit counts, CLI exit codes, and leaves cwd unchanged', function () {
    const cwd = process.cwd();
    const catalog = { cataloged: ['frontend/src/main.ts'], reachable: ['frontend/src/main.ts'] };
    const options = { catalog, readSource: () => 'throw new Error("not implemented")',
      allowlist: { entries: [], errors: [] } };
    const result = audit.auditProductionPlaceholders(options);
    expect(result.ok).to.equal(false);
    expect(result.summary).to.deep.include({ cataloged: 1, reachable: 1, findings: 1, violations: 1, allowed: 0 });
    let output = '';
    expect(main({ audit: () => ({ ok: true }), stdout: { write: value => { output += value; } } })).to.equal(0);
    expect(JSON.parse(output).ok).to.equal(true);
    expect(main({ audit: () => result, stdout: { write() {} } })).to.equal(1);
    expect(process.cwd()).to.equal(cwd);
  });
});
