/**
 * 文件用途: Pinia 路由 store，管理动态路由、菜单、缓存路由、面包屑和本地化后的导航状态。
 * 核心逻辑: 根据 auth route mode 合并 generated routes 与后端路由，并把授权路由注册到 Vue Router。
 * 关键注意事项: 登录刷新、权限 guard、菜单可见性和兼容 route supplement 都依赖初始化顺序。
 * 重构建议: 保持 route 生成纯函数在 shared.ts 中可测，拆分后端路由 normalize 与 Vue Router 注册副作用。
 */
import { computed, ref } from 'vue'
import type { RouteRecordRaw } from 'vue-router'
import { defineStore } from 'pinia'
import { useBoolean } from '@aetherlink/hooks'
import type { CustomRoute, ElegantConstRoute, LastLevelRouteKey, RouteKey, RouteMap } from '@elegant-router/types'
import { router } from '@/router'
import { SetupStoreId } from '@/enum'
import { ROOT_ROUTE, createRoutes, getAuthVueRoutes } from '@/router/routes'
import { getRouteName, getRoutePath } from '@/router/elegant/transform'
import { fetchGetUserRoutes } from '@/service/api'
import { useAppStore } from '../app'
import { useAuthStore } from '../auth'
import { useTabStore } from '../tab'
import {
  filterAuthRoutesByRoles,
  getBreadcrumbsByRoute,
  getCacheRouteNames,
  getGlobalMenusByAuthRoutes,
  getSelectedMenuKeyPathByKey,
  isRouteExistByRouteName,
  sortRoutesByOrder,
  updateLocaleOfGlobalMenus
} from './shared'

function routeAllowsRoles(route: ElegantConstRoute, roles: string[]) {
  const routeRoles = route.meta?.roles || []
  if (!routeRoles.length) return true
  if (roles.includes('SYS_ADMIN')) return true
  return routeRoles.some(role => roles.includes(role))
}

export const useRouteStore = defineStore(SetupStoreId.Route, () => {
  const appStore = useAppStore()
  const authStore = useAuthStore()
  const tabStore = useTabStore()
  const { bool: isInitAuthRoute, setBool: setIsInitAuthRoute } = useBoolean()
  const removeRouteFns: (() => void)[] = []

  /**
   * Auth route mode
   *
   * It recommends to use static mode in the development environment, and use dynamic mode in the production
   * environment, if you use static mode in development environment, the auth routes will be auto generated by plugin
   * "@elegant-router/vue"
   */
  const authRouteMode = ref(import.meta.env.VITE_AUTH_ROUTE_MODE)
  /** Home route key */
  const routeHome = ref(import.meta.env.VITE_ROUTE_HOME)
  const DYNAMIC_ROUTE_SUPPLEMENTS: Partial<Record<RouteKey, RouteKey[]>> = {
    device: ['device_share', 'device_shared-with-me'],
    management: ['management_setting'],
    // Visualization detail routes are not menu entries. Keep the local native
    // routes and hybrid compatibility routes reachable when dynamic auth data
    // only returns the visualization parent or a subset of children. The page
    // chooses Native by default; the provider seam still blocks explicit
    // Legacy selection when the optional external profile is disabled.
    visualization: [
      'visualization_thingsvis',
      'visualization_thingsvis-dashboards',
      'visualization_thingsvis-editor',
      'visualization_thingsvis-menu-dashboard',
      'visualization_thingsvis-preview',
      'visualization_native-boards',
      'visualization_native-board',
      'visualization_native-board-editor'
    ]
  }

  /**
   * Set route home
   *
   * @param routeKey Route key
   */
  function setRouteHome(routeKey: LastLevelRouteKey) {
    routeHome.value = routeKey
  }

  /** Global menus */
  const menus = ref<App.Global.Menu[]>([])

  /** Get global menus */
  function getGlobalMenus(routes: ElegantConstRoute[]) {
    menus.value = getGlobalMenusByAuthRoutes(routes)
  }

  /** Update global menus by locale */
  function updateGlobalMenusByLocale() {
    menus.value = updateLocaleOfGlobalMenus(menus.value)
  }

  /** Cache routes */
  const cacheRoutes = ref<RouteKey[]>([])

  /**
   * Get cache routes
   *
   * @param routes Vue routes
   */
  function getCacheRoutes(routes: RouteRecordRaw[]) {
    const { constantVueRoutes } = createRoutes()

    cacheRoutes.value = getCacheRouteNames([...constantVueRoutes, ...routes])
  }

  /**
   * Add cache routes
   *
   * @param routeKey
   */
  function addCacheRoutes(routeKey: RouteKey) {
    if (cacheRoutes.value.includes(routeKey)) return

    cacheRoutes.value.push(routeKey)
  }

  /**
   * Remove cache routes
   *
   * @param routeKey
   */
  function removeCacheRoutes(routeKey: RouteKey) {
    const index = cacheRoutes.value.findIndex(item => item === routeKey)

    if (index === -1) return

    cacheRoutes.value.splice(index, 1)
  }

  /**
   * Re-cache routes by route key
   *
   * @param routeKey
   */
  async function reCacheRoutesByKey(routeKey: RouteKey) {
    removeCacheRoutes(routeKey)

    await appStore.reloadPage()

    addCacheRoutes(routeKey)
  }

  /**
   * Re-cache routes by route keys
   *
   * @param routeKeys
   */
  async function reCacheRoutesByKeys(routeKeys: RouteKey[]) {
    for await (const key of routeKeys) {
      await reCacheRoutesByKey(key)
    }
  }

  /** Global breadcrumbs */
  const breadcrumbs = computed(() => getBreadcrumbsByRoute(router.currentRoute.value, menus.value))

  /** Reset store */
  async function resetStore() {
    routeHome.value = import.meta.env.VITE_ROUTE_HOME
    menus.value = []
    cacheRoutes.value = []
    setIsInitAuthRoute(false)
    resetVueRoutes()
  }

  /** Reset vue routes */
  function resetVueRoutes() {
    removeRouteFns.forEach(fn => fn())
    removeRouteFns.length = 0
  }

  /** Init auth route */
  async function initAuthRoute(): Promise<boolean> {
    let success = false
    if (authRouteMode.value === 'static') {
      success = await initStaticAuthRoute()
    } else {
      success = await initDynamicAuthRoute()
    }

    if (success) {
      tabStore.initHomeTab()
    }

    return success
  }

  /** Init static auth route */
  async function initStaticAuthRoute(): Promise<boolean> {
    const { authRoutes } = createRoutes()

    const filteredAuthRoutes = filterAuthRoutesByRoles(authRoutes, authStore?.userInfo?.roles as string[])

    handleAuthRoutes(filteredAuthRoutes)

    setIsInitAuthRoute(true)

    return true // Indicate success
  }

  /** Init dynamic auth route */
  async function initDynamicAuthRoute(): Promise<boolean> {
    const { data, error } = await fetchGetUserRoutes()

    if (!error) {
      const routes = mergeDynamicRouteSupplements(data?.list || [])

      handleAuthRoutes(routes)

      setRouteHome('home')

      handleUpdateRootRouteRedirect('home')

      setIsInitAuthRoute(true)

      return true // Indicate success
    }

    return false // Indicate failure
  }

  function mergeDynamicRouteSupplements(routes: ElegantConstRoute[]): ElegantConstRoute[] {
    const { authRoutes } = createRoutes()
    // These routes are hybrid compatibility entry points, not an opt-in
    // external-service permission boundary. Keep them resolvable so
    // provider=native works in Native-only deployments; the provider facade
    // rejects provider=legacy when VITE_ENABLE_THINGSVIS_COMPAT is not Y.
    const mergedRoutes = routes.map(route => cloneRoute(route))
    const currentRoles = Array.isArray(authStore.userInfo?.roles) ? authStore.userInfo.roles : []

    Object.entries(DYNAMIC_ROUTE_SUPPLEMENTS).forEach(([parentName, childNames]) => {
      const parentRouteName = parentName as RouteKey
      const parentRoute = findRouteByName(mergedRoutes, parentRouteName)
      const localParentRoute = findRouteByName(authRoutes, parentRouteName)

      if (!parentRoute || !localParentRoute?.children?.length) return

      const existingChildNames = new Set((parentRoute.children || []).map(child => child.name as RouteKey))
      const supplementChildren: ElegantConstRoute[] = childNames
        .map(childName => findRouteByName(localParentRoute.children || [], childName))
        .filter((child): child is ElegantConstRoute => Boolean(child))
        .filter(child => !existingChildNames.has(child.name as RouteKey))
        .filter(child => routeAllowsRoles(child, currentRoles))
        .map(child => {
          const supplementChild = cloneRoute(child)
          supplementChild.meta = {
            ...supplementChild.meta,
            title: supplementChild.meta?.title || child.name,
            hideInMenu: true,
            activeMenu: parentRouteName
          }
          return supplementChild
        })

      if (!supplementChildren.length) return

      parentRoute.children = [...(parentRoute.children || []), ...supplementChildren]
    })

    return mergedRoutes
  }

  function findRouteByName(routes: ElegantConstRoute[], routeName: RouteKey): ElegantConstRoute | null {
    for (const route of routes) {
      if (route.name === routeName) return route
      if (route.children?.length) {
        const childRoute = findRouteByName(route.children, routeName)
        if (childRoute) return childRoute
      }
    }

    return null
  }

  function cloneRoute<T extends ElegantConstRoute>(route: T): T {
    return {
      ...route,
      meta: route.meta ? { ...route.meta } : route.meta,
      children: route.children?.map(child => cloneRoute(child))
    }
  }

  /**
   * Handle routes
   *
   * @param routes Auth routes
   */
  function handleAuthRoutes(routes: ElegantConstRoute[]) {
    const sortRoutes = sortRoutesByOrder(routes)

    const vueRoutes = getAuthVueRoutes(sortRoutes)

    addRoutesToVueRouter(vueRoutes)

    getGlobalMenus(sortRoutes)

    getCacheRoutes(vueRoutes)
  }

  /**
   * Add routes to vue router
   *
   * @param routes Vue routes
   */
  function addRoutesToVueRouter(routes: RouteRecordRaw[]) {
    routes.forEach(route => {
      const removeFn = router.addRoute(route)
      addRemoveRouteFn(removeFn)
    })
  }

  /**
   * Add remove route fn
   *
   * @param fn
   */
  function addRemoveRouteFn(fn: () => void) {
    removeRouteFns.push(fn)
  }

  /**
   * Update root route redirect when auth route mode is dynamic
   *
   * @param redirectKey Redirect route key
   */
  function handleUpdateRootRouteRedirect(redirectKey: LastLevelRouteKey) {
    const redirect = getRoutePath(redirectKey)

    if (redirect) {
      const rootRoute: CustomRoute = { ...ROOT_ROUTE, redirect }

      router.removeRoute(rootRoute.name)

      const [rootVueRoute] = getAuthVueRoutes([rootRoute])

      router.addRoute(rootVueRoute)
    }
  }

  /**
   * Get is auth route exist
   *
   * @param routePath Route path
   */
  async function getIsAuthRouteExist(routePath: RouteMap[RouteKey]) {
    const routeName = getRouteName(routePath)

    if (!routeName) {
      return false
    }

    const { authRoutes } = createRoutes()

    if (isRouteExistByRouteName(routeName, authRoutes)) {
      return true
    }

    if (authRouteMode.value === 'static') {
      return isRouteExistByRouteName(routeName, authRoutes)
    }

    return false
  }

  /**
   * Get selected menu key path
   *
   * @param selectedKey Selected menu key
   */
  function getSelectedMenuKeyPath(selectedKey: string) {
    return getSelectedMenuKeyPathByKey(selectedKey, menus.value)
  }

  return {
    resetStore,
    routeHome,
    menus,
    updateGlobalMenusByLocale,
    cacheRoutes,
    reCacheRoutesByKey,
    reCacheRoutesByKeys,
    breadcrumbs,
    initAuthRoute,
    isInitAuthRoute,
    setIsInitAuthRoute,
    getIsAuthRouteExist,
    getSelectedMenuKeyPath
  }
})
