/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

declare module "@elegant-router/types" {
  type ElegantConstRoute = import('@elegant-router/vue').ElegantConstRoute;

  /**
   * route layout
   */
  export type RouteLayout = "base" | "blank";

  /**
   * route map
   */
  export type RouteMap = {
    "root": "/";
    "not-found": "/:pathMatch(.*)*";
    "403": "/403";
    "404": "/404";
    "500": "/500";
    "alarm": "/alarm";
    "alarm_notification-group": "/alarm/notification-group";
    "alarm_notification-record": "/alarm/notification-record";
    "alarm_rdi-overview": "/alarm/rdi-overview";
    "alarm_warning-message": "/alarm/warning-message";
    "apply": "/apply";
    "apply_plugin": "/apply/plugin";
    "apply_service": "/apply/service";
    "automation": "/automation";
    "automation_linkage-edit": "/automation/linkage-edit";
    "automation_scene-edit": "/automation/scene-edit";
    "automation_scene-linkage": "/automation/scene-linkage";
    "automation_scene-manage": "/automation/scene-manage";
    "dashboard": "/dashboard";
    "dashboard_rdi-overview": "/dashboard/rdi-overview";
    "dashboard_workbench": "/dashboard/workbench";
    "dashboard_workspace": "/dashboard/workspace";
    "device": "/device";
    "device_command-center": "/device/command-center";
    "device_config": "/device/template";
    "device_config-detail": "/device/config-detail";
    "device_config-edit": "/device/config-edit";
    "device_details": "/device/details";
    "device_details-child": "/device/details-child";
    "device_grouping": "/device/grouping";
    "device_grouping-details": "/device/grouping-details";
    "device_manage": "/device/manage";
    "device_service-access": "/device/service-access";
    "device_service-details": "/device/service-details";
    "device_share": "/device/share";
    "device_shared-with-me": "/device/shared-with-me";
    "device_template": "/device/thingsmodel";
    "device-details-app": "/device-details-app";
    "home": "/home";
    "legal": "/legal";
    "login": "/login/:module(pwd-login|code-login|register|register-email|register-super-admin|reset-pwd|bind-wechat)?";
    "management": "/management";
    "management_api": "/management/api";
    "management_auth": "/management/auth";
    "management_notification": "/management/notification";
    "management_role": "/management/role";
    "management_setting": "/management/setting";
    "management_user": "/management/user";
    "personal-center": "/personal-center";
    "product": "/product";
    "product_update-ota": "/product/update-ota";
    "product_update-package": "/product/update-package";
    "system-management-user": "/system-management-user";
    "system-management-user_equipment-map": "/system-management-user/equipment-map";
    "system-management-user_system-log": "/system-management-user/system-log";
    "visualization": "/visualization";
    "visualization_native-board": "/visualization/native-board";
    "visualization_native-board-editor": "/visualization/native-board-editor";
    "visualization_native-boards": "/visualization/native-boards";
    "visualization_thingsvis": "/visualization/thingsvis";
    "visualization_thingsvis-dashboards": "/visualization/thingsvis-dashboards";
    "visualization_thingsvis-editor": "/visualization/thingsvis-editor";
    "visualization_thingsvis-menu-dashboard": "/visualization/thingsvis-menu-dashboard";
    "visualization_thingsvis-preview": "/visualization/thingsvis-preview";
  };

  /**
   * route key
   */
  export type RouteKey = keyof RouteMap;

  /**
   * route path
   */
  export type RoutePath = RouteMap[RouteKey];

  /**
   * custom route key
   */
  export type CustomRouteKey = Extract<
    RouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the generated route key
   */
  export type GeneratedRouteKey = Exclude<RouteKey, CustomRouteKey>;

  /**
   * the first level route key, which contain the layout of the route
   */
  export type FirstLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "alarm"
    | "apply"
    | "automation"
    | "dashboard"
    | "device"
    | "device-details-app"
    | "home"
    | "legal"
    | "login"
    | "management"
    | "personal-center"
    | "product"
    | "system-management-user"
    | "visualization"
  >;

  /**
   * the custom first level route key
   */
  export type CustomFirstLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the last level route key, which has the page file
   */
  export type LastLevelRouteKey = Extract<
    RouteKey,
    | "403"
    | "404"
    | "500"
    | "legal"
    | "login"
    | "alarm_notification-group"
    | "alarm_notification-record"
    | "alarm_rdi-overview"
    | "alarm_warning-message"
    | "apply_plugin"
    | "apply_service"
    | "automation_linkage-edit"
    | "automation_scene-edit"
    | "automation_scene-linkage"
    | "automation_scene-manage"
    | "dashboard_rdi-overview"
    | "dashboard_workbench"
    | "dashboard_workspace"
    | "device-details-app"
    | "device_command-center"
    | "device_config-detail"
    | "device_config-edit"
    | "device_config"
    | "device_details-child"
    | "device_details"
    | "device_grouping-details"
    | "device_grouping"
    | "device_manage"
    | "device_service-access"
    | "device_service-details"
    | "device_share"
    | "device_shared-with-me"
    | "device_template"
    | "home"
    | "management_api"
    | "management_auth"
    | "management_notification"
    | "management_role"
    | "management_setting"
    | "management_user"
    | "personal-center"
    | "product_update-ota"
    | "product_update-package"
    | "system-management-user_equipment-map"
    | "system-management-user_system-log"
    | "visualization_native-board"
    | "visualization_native-board-editor"
    | "visualization_native-boards"
    | "visualization_thingsvis-dashboards"
    | "visualization_thingsvis-editor"
    | "visualization_thingsvis-menu-dashboard"
    | "visualization_thingsvis-preview"
    | "visualization_thingsvis"
  >;

  /**
   * the custom last level route key
   */
  export type CustomLastLevelRouteKey = Extract<
    CustomRouteKey,
    | "root"
    | "not-found"
  >;

  /**
   * the single level route key
   */
  export type SingleLevelRouteKey = FirstLevelRouteKey & LastLevelRouteKey;

  /**
   * the custom single level route key
   */
  export type CustomSingleLevelRouteKey = CustomFirstLevelRouteKey & CustomLastLevelRouteKey;

  /**
   * the first level route key, but not the single level
  */
  export type FirstLevelRouteNotSingleKey = Exclude<FirstLevelRouteKey, SingleLevelRouteKey>;

  /**
   * the custom first level route key, but not the single level
   */
  export type CustomFirstLevelRouteNotSingleKey = Exclude<CustomFirstLevelRouteKey, CustomSingleLevelRouteKey>;

  /**
   * the center level route key
   */
  export type CenterLevelRouteKey = Exclude<GeneratedRouteKey, FirstLevelRouteKey | LastLevelRouteKey>;

  /**
   * the custom center level route key
   */
  export type CustomCenterLevelRouteKey = Exclude<CustomRouteKey, CustomFirstLevelRouteKey | CustomLastLevelRouteKey>;

  /**
   * the center level route key
   */
  type GetChildRouteKey<K extends RouteKey, T extends RouteKey = RouteKey> = T extends `${K}_${infer R}`
    ? R extends `${string}_${string}`
      ? never
      : T
    : never;

  /**
   * the single level route
   */
  type SingleLevelRoute<K extends SingleLevelRouteKey = SingleLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}$view.${K}`;
      }
    : never;

  /**
   * the last level route
   */
  type LastLevelRoute<K extends GeneratedRouteKey> = K extends LastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component: `view.${K}`;
      }
    : never;

  /**
   * the center level route
   */
  type CenterLevelRoute<K extends GeneratedRouteKey> = K extends CenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the multi level route
   */
  type MultiLevelRoute<K extends FirstLevelRouteNotSingleKey = FirstLevelRouteNotSingleKey> = K extends string
    ? ElegantConstRoute & {
        name: K;
        path: RouteMap[K];
        component: `layout.${RouteLayout}`;
        children: (CenterLevelRoute<GetChildRouteKey<K>> | LastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom first level route
   */
  type CustomSingleLevelRoute<K extends CustomFirstLevelRouteKey = CustomFirstLevelRouteKey> = K extends string
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `layout.${RouteLayout}$view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom last level route
   */
  type CustomLastLevelRoute<K extends CustomRouteKey> = K extends CustomLastLevelRouteKey
    ? Omit<ElegantConstRoute, 'children'> & {
        name: K;
        path: RouteMap[K];
        component?: `view.${LastLevelRouteKey}`;
      }
    : never;

  /**
   * the custom center level route
   */
  type CustomCenterLevelRoute<K extends CustomRouteKey> = K extends CustomCenterLevelRouteKey
    ? Omit<ElegantConstRoute, 'component'> & {
        name: K;
        path: RouteMap[K];
        children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
      }
    : never;

  /**
   * the custom multi level route
   */
  type CustomMultiLevelRoute<K extends CustomFirstLevelRouteNotSingleKey = CustomFirstLevelRouteNotSingleKey> =
    K extends string
      ? ElegantConstRoute & {
          name: K;
          path: RouteMap[K];
          component: `layout.${RouteLayout}`;
          children: (CustomCenterLevelRoute<GetChildRouteKey<K>> | CustomLastLevelRoute<GetChildRouteKey<K>>)[];
        }
      : never;

  /**
   * the custom route
   */
  type CustomRoute = CustomSingleLevelRoute | CustomMultiLevelRoute;

  /**
   * the generated route
   */
  type GeneratedRoute = SingleLevelRoute | MultiLevelRoute;

  /**
   * the elegant route
   */
  type ElegantRoute = GeneratedRoute | CustomRoute;
}
