// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 alarm config 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameAlarmConfig = "alarm_config"

// AlarmConfig mapped from table <alarm_config>
type AlarmConfig struct {
	ID                  string    `gorm:"column:id;primaryKey" json:"id"`
	Name                string    `gorm:"column:name;not null;comment:告警名称" json:"name"`                                    // 告警名称
	Description         *string   `gorm:"column:description;comment:告警描述" json:"description"`                               // 告警描述
	AlarmLevel          string    `gorm:"column:alarm_level;not null;comment:告警级别H: 高M: 中L: 低" json:"alarm_level"`          // 告警级别H: 高M: 中L: 低
	NotificationGroupID string    `gorm:"column:notification_group_id;not null;comment:通知组id" json:"notification_group_id"` // 通知组id
	CreatedAt           time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt           time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	TenantID            string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Remark              *string   `gorm:"column:remark" json:"remark"`
	Enabled             string    `gorm:"column:enabled;not null;comment:是否启用Y-启用N-停止" json:"enabled"`                                // 是否启用Y-启用N-停止
	TriggerDuration     int32     `gorm:"column:trigger_duration;not null;default:0;comment:触发持续时间(秒)0-立即触发" json:"trigger_duration"` // 触发持续时间(秒)0-立即触发
}

// TableName AlarmConfig's table name
func (*AlarmConfig) TableName() string {
	return TableNameAlarmConfig
}
