// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 alarm history 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameAlarmHistory = "alarm_history"

// AlarmHistory mapped from table <alarm_history>
type AlarmHistory struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	AlarmConfigID     string    `gorm:"column:alarm_config_id;not null" json:"alarm_config_id"`
	GroupID           string    `gorm:"column:group_id;not null" json:"group_id"`
	SceneAutomationID string    `gorm:"column:scene_automation_id;not null" json:"scene_automation_id"`
	Name              string    `gorm:"column:name;not null;comment:告警名称" json:"name"`                            // 告警名称
	Description       *string   `gorm:"column:description;comment:告警描述" json:"description"`                       // 告警描述
	Content           *string   `gorm:"column:content;comment:内容（什么原因导致的告警）" json:"content"`                      // 内容（什么原因导致的告警）
	AlarmStatus       string    `gorm:"column:alarm_status;not null;comment:L 底 M中 H 高 N 正常" json:"alarm_status"` // L 底 M中 H 高 N 正常
	TenantID          string    `gorm:"column:tenant_id;not null;comment:租户" json:"tenant_id"`                    // 租户
	Remark            *string   `gorm:"column:remark" json:"remark"`
	CreateAt          time.Time `gorm:"column:create_at;not null;comment:创建时间" json:"create_at"`                   // 创建时间
	AlarmDeviceList   string    `gorm:"column:alarm_device_list;not null;comment:触发设备id" json:"alarm_device_list"` // 触发设备id
}

// TableName AlarmHistory's table name
func (*AlarmHistory) TableName() string {
	return TableNameAlarmHistory
}
