// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 alarm info 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameAlarmInfo = "alarm_info"

// AlarmInfo mapped from table <alarm_info>
type AlarmInfo struct {
	ID               string    `gorm:"column:id;primaryKey" json:"id"`
	AlarmConfigID    string    `gorm:"column:alarm_config_id;not null;comment:告警配置id" json:"alarm_config_id"`                        // 告警配置id
	Name             string    `gorm:"column:name;not null;comment:告警名称" json:"name"`                                                // 告警名称
	AlarmTime        time.Time `gorm:"column:alarm_time;not null;comment:告警时间" json:"alarm_time"`                                    // 告警时间
	Description      *string   `gorm:"column:description;comment:告警描述" json:"description"`                                           // 告警描述
	Content          *string   `gorm:"column:content;comment:内容" json:"content"`                                                     // 内容
	Processor        *string   `gorm:"column:processor;comment:处理人id" json:"processor"`                                              // 处理人id
	ProcessingResult string    `gorm:"column:processing_result;not null;comment:处理结果DOP-已处理UND-未处理IGN-已忽略" json:"processing_result"` // 处理结果DOP-已处理UND-未处理IGN-已忽略
	TenantID         string    `gorm:"column:tenant_id;not null;comment:租户id" json:"tenant_id"`                                      // 租户id
	Remark           *string   `gorm:"column:remark" json:"remark"`
	AlarmLevel       *string   `gorm:"column:alarm_level;comment:告警级别L M H" json:"alarm_level"` // 告警级别L M H
}

// TableName AlarmInfo's table name
func (*AlarmInfo) TableName() string {
	return TableNameAlarmInfo
}
