// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 boards 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameBoard = "boards"

// Board mapped from table <boards>
type Board struct {
	Published   bool       `gorm:"column:published;not null;default:false;comment:是否已发布" json:"published"`
	PublishedAt *time.Time `gorm:"column:published_at;comment:发布时间" json:"published_at"`
	ShareToken  *string    `gorm:"column:share_token;uniqueIndex;comment:公开分享令牌" json:"share_token"`
	ID          string     `gorm:"column:id;primaryKey;comment:Id" json:"id"`                   // Id
	Name        string     `gorm:"column:name;not null;comment:看板名称" json:"name"`               // 看板名称
	Config      *string    `gorm:"column:config;default:{};comment:看板配置" json:"config"`         // 看板配置
	TenantID    string     `gorm:"column:tenant_id;not null;comment:租户id（唯一）" json:"tenant_id"` // 租户id（唯一）
	CreatedAt   time.Time  `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt   time.Time  `gorm:"column:updated_at;not null" json:"updated_at"`
	HomeFlag    string     `gorm:"column:home_flag;not null;comment:首页标志默认N，Y" json:"home_flag"` // 首页标志默认N，Y
	Description *string    `gorm:"column:description;comment:描述" json:"description"`             // 描述
	Remark      *string    `gorm:"column:remark;comment:备注" json:"remark"`                       // 备注
	MenuFlag    *string    `gorm:"column:menu_flag;comment:菜单标志默认N，Y" json:"menu_flag"`          // 菜单标志默认N，Y
	VisType     *string    `gorm:"column:vis_type;comment:可视化类型" json:"vis_type"`                // 可视化类型
}

// TableName Board's table name
func (*Board) TableName() string {
	return TableNameBoard
}
