// Code generated by gorm. DO NOT EDIT.
// 文件用途：计算字段模型，定义从遥测数据派生新指标的表达式配置。

package model

import (
	"time"
)

const TableNameCalculatedField = "calculated_fields"

type CalculatedField struct {
	ID              string    `gorm:"column:id;primaryKey" json:"id"`
	DeviceConfigID  string    `gorm:"column:device_config_id;not null" json:"device_config_id"`
	OutputKey       string    `gorm:"column:output_key;not null" json:"output_key"`
	Expression      string    `gorm:"column:expression;not null" json:"expression"`
	Unit            *string   `gorm:"column:unit" json:"unit"`
	Description     *string   `gorm:"column:description" json:"description"`
	Enabled         bool      `gorm:"column:enabled;not null;default:true" json:"enabled"`
	CreatedAt       time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt       time.Time `gorm:"column:updated_at" json:"updated_at"`
}

func (*CalculatedField) TableName() string { return TableNameCalculatedField }