// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 data scripts 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDataScript = "data_scripts"

// DataScript mapped from table <data_scripts>
type DataScript struct {
	ID              string     `gorm:"column:id;primaryKey;comment:Id" json:"id"`                                                        // Id
	Name            string     `gorm:"column:name;not null;comment:名称" json:"name"`                                                      // 名称
	DeviceConfigID  string     `gorm:"column:device_config_id;not null;comment:设备配置id 关联删除" json:"device_config_id"`                     // 设备配置id 关联删除
	EnableFlag      string     `gorm:"column:enable_flag;not null;comment:启用标志Y-启用 N-停用 默认启用" json:"enable_flag"`                        // 启用标志Y-启用 N-停用 默认启用
	Content         *string    `gorm:"column:content;comment:内容" json:"content"`                                                         // 内容
	ScriptType      string     `gorm:"column:script_type;not null;comment:脚本类型 A-遥测上报预处理B-遥测下发预处理C-属性上报预处理D-属性下发预处理" json:"script_type"` // 脚本类型 A-遥测上报预处理B-遥测下发预处理C-属性上报预处理D-属性下发预处理
	LastAnalogInput *string    `gorm:"column:last_analog_input;comment:上次模拟输入" json:"last_analog_input"`                                 // 上次模拟输入
	Description     *string    `gorm:"column:description;comment:描述" json:"description"`                                                 // 描述
	CreatedAt       *time.Time `gorm:"column:created_at;comment:创建时间" json:"created_at"`                                                 // 创建时间
	UpdatedAt       *time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                                 // 更新时间
	Remark          *string    `gorm:"column:remark;comment:备注" json:"remark"`                                                           // 备注
}

// TableName DataScript's table name
func (*DataScript) TableName() string {
	return TableNameDataScript
}
