// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 data policy 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDataPolicy = "data_policy"

// DataPolicy mapped from table <data_policy>
type DataPolicy struct {
	ID                  string     `gorm:"column:id;primaryKey;comment:Id" json:"id"`                                                   // Id
	DataType            string     `gorm:"column:data_type;not null;comment:清理类型:1-设备数据、2-操作日志" json:"data_type"`                       // 清理类型:1-设备数据、2-操作日志
	RetentionDay        int32      `gorm:"column:retention_days;not null;comment:数据保留时间（天）" json:"retention_days"`                      // 数据保留时间（天）
	LastCleanupTime     *time.Time `gorm:"column:last_cleanup_time;comment:上次清理时间" json:"last_cleanup_time"`                            // 上次清理时间
	LastCleanupDataTime *time.Time `gorm:"column:last_cleanup_data_time;comment:上次清理的数据时间节点（实际清理的数据时间点）" json:"last_cleanup_data_time"` // 上次清理的数据时间节点（实际清理的数据时间点）
	Enabled             string     `gorm:"column:enabled;not null;comment:是否启用：1启用 2停用" json:"enabled"`                                 // 是否启用：1启用 2停用
	Remark              *string    `gorm:"column:remark;comment:备注" json:"remark"`                                                      // 备注
}

// TableName DataPolicy's table name
func (*DataPolicy) TableName() string {
	return TableNameDataPolicy
}
