// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device topic mappings 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDeviceTopicMapping = "device_topic_mappings"

// DeviceTopicMapping mapped from table <device_topic_mappings>
type DeviceTopicMapping struct {
	ID             int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	DeviceConfigID string    `gorm:"column:device_config_id;not null" json:"device_config_id"`
	Name           string    `gorm:"column:name;not null" json:"name"`
	Direction      string    `gorm:"column:direction;not null" json:"direction"`
	SourceTopic    string    `gorm:"column:source_topic;not null" json:"source_topic"`
	TargetTopic    string    `gorm:"column:target_topic;not null" json:"target_topic"`
	Priority       int32     `gorm:"column:priority;not null;default:100" json:"priority"`
	Enabled        bool      `gorm:"column:enabled;not null;default:true" json:"enabled"`
	Description    *string   `gorm:"column:description" json:"description"`
	CreatedAt      time.Time `gorm:"column:created_at;not null;default:now()" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null;default:now()" json:"updated_at"`
	DataIdentifier *string   `gorm:"column:data_identifier" json:"data_identifier"`
}

// TableName DeviceTopicMapping's table name
func (*DeviceTopicMapping) TableName() string {
	return TableNameDeviceTopicMapping
}
