// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device status history 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDeviceStatusHistory = "device_status_history"

// DeviceStatusHistory mapped from table <device_status_history>
type DeviceStatusHistory struct {
	ID         int64     `gorm:"column:id;primaryKey;autoIncrement:true" json:"id"`
	TenantID   string    `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenant_id"`       // 租户ID
	DeviceID   string    `gorm:"column:device_id;not null;comment:设备ID" json:"device_id"`       // 设备ID
	Status     int16     `gorm:"column:status;not null;comment:状态: 0-离线 1-在线" json:"status"`    // 状态: 0-离线 1-在线
	ChangeTime time.Time `gorm:"column:change_time;not null;comment:状态变更时间" json:"change_time"` // 状态变更时间
}

// TableName DeviceStatusHistory's table name
func (*DeviceStatusHistory) TableName() string {
	return TableNameDeviceStatusHistory
}
