// Code generated by gorm. DO NOT EDIT.
// 文件用途：设备影子消息表模型，存储设备离线时的命令/属性设置缓存。
// 核心逻辑：定义 device_shadow_messages 表的字段映射和表名常量。
// 关键注意事项：status 取值 pending/delivered/expired/canceled；expires_at 由 ttl_seconds 计算写入。

package model

import (
	"time"
)

const TableNameDeviceShadowMessage = "device_shadow_messages"

// DeviceShadowMessage mapped from table <device_shadow_messages>
type DeviceShadowMessage struct {
	ID          string    `gorm:"column:id;primaryKey;default:gen_random_uuid()" json:"id"`
	DeviceID    string    `gorm:"column:device_id;not null" json:"device_id"`
	MessageType string    `gorm:"column:message_type;not null;default:command" json:"message_type"`
	Payload     *string   `gorm:"column:payload;type:jsonb;not null;default:{}" json:"payload"`
	TTLSeconds  int       `gorm:"column:ttl_seconds;not null;default:86400" json:"ttl_seconds"`
	Status      string    `gorm:"column:status;not null;default:pending" json:"status"`
	CreatedBy   *string   `gorm:"column:created_by" json:"created_by"`
	CreatedAt   *time.Time `gorm:"column:created_at" json:"created_at"`
	DeliveredAt *time.Time `gorm:"column:delivered_at" json:"delivered_at"`
	ExpiresAt   time.Time `gorm:"column:expires_at;not null" json:"expires_at"`
}

// TableName DeviceShadowMessage's table name
func (*DeviceShadowMessage) TableName() string {
	return TableNameDeviceShadowMessage
}
