// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device trigger condition 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

const TableNameDeviceTriggerCondition = "device_trigger_condition"

// DeviceTriggerCondition mapped from table <device_trigger_condition>
type DeviceTriggerCondition struct {
	ID                   string  `gorm:"column:id;primaryKey;comment:Id" json:"id"`                                                                                                                                                              // Id
	SceneAutomationID    string  `gorm:"column:scene_automation_id;not null;comment:场景联动ID（外键-关联删除）" json:"scene_automation_id"`                                                                                                                 // 场景联动ID（外键-关联删除）
	Enabled              string  `gorm:"column:enabled;not null;comment:是否启用" json:"enabled"`                                                                                                                                                    // 是否启用
	GroupID              string  `gorm:"column:group_id;not null;comment:uuid" json:"group_id"`                                                                                                                                                  // uuid
	TriggerConditionType string  `gorm:"column:trigger_condition_type;not null;comment:条件类型 10：设备类型 - 单个设备 11：设备类型 - 单类设备 2：时间范围" json:"trigger_condition_type"`                                                                                 // 条件类型 10：设备类型 - 单个设备 11：设备类型 - 单类设备 2：时间范围
	TriggerSource        *string `gorm:"column:trigger_source;comment:触发源有以下几种可能： 条件类型为10时，为设备id；条件类型为11时，设备配置id（device_config_id）" json:"trigger_source"`                                                                                       // 触发源有以下几种可能： 条件类型为10时，为设备id；条件类型为11时，设备配置id（device_config_id）
	TriggerParamType     *string `gorm:"column:trigger_param_type;comment:遥测TEL属性ATTR事件EVT状态STATUS" json:"trigger_param_type"`                                                                                                                   // 遥测TEL属性ATTR事件EVT状态STATUS
	TriggerParam         *string `gorm:"column:trigger_param;comment:触发参数 当条件类型为10或11时有效，比如温度 temperature" json:"trigger_param"`                                                                                                                 // 触发参数 当条件类型为10或11时有效，比如温度 temperature
	TriggerOperator      *string `gorm:"column:trigger_operator;comment:运算符 =：等于 !=：不等于 >：大于 <：小于 >=：大于等于 <=：小于等于 between：介于 in：包含在列表内" json:"trigger_operator"`                                                                                 // 运算符 =：等于 !=：不等于 >：大于 <：小于 >=：大于等于 <=：小于等于 between：介于 in：包含在列表内
	TriggerValue         string  `gorm:"column:trigger_value;type:varchar(1024);not null;comment:取值条件类型为10,11，运算符是为7时，假设最大值6最小值2, 格式为2-6；设备状态条件类型为10,11，运算符为8时，多个值英文逗号隔开条件类型为 条件类型是22，示例137|HH:mm:ss+00:00|HH:mm:ss+00:00" json:"trigger_value"` // 取值条件类型为10,11，运算符是为7时，假设最大值6最小值2, 格式为2-6；设备状态条件类型为10,11，运算符为8时，多个值英文逗号隔开条件类型为 条件类型是22，示例137|HH:mm:ss+00:00|HH:mm:ss+00:00
	Remark               *string `gorm:"column:remark" json:"remark"`
	TenantID             string  `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenant_id"` // 租户ID
}

// TableName DeviceTriggerCondition's table name
func (*DeviceTriggerCondition) TableName() string {
	return TableNameDeviceTriggerCondition
}
