// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device model custom commands 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

const TableNameDeviceModelCustomCommand = "device_model_custom_commands"

// DeviceModelCustomCommand mapped from table <device_model_custom_commands>
type DeviceModelCustomCommand struct {
	ID               string  `gorm:"column:id;primaryKey;comment:id" json:"id"`                                          // id
	DeviceTemplateID string  `gorm:"column:device_template_id;not null;comment:设备模板id" json:"device_template_id"`        // 设备模板id
	ButtomName       string  `gorm:"column:buttom_name;not null;comment:按钮名称" json:"buttom_name"`                        // 按钮名称
	DataIdentifier   string  `gorm:"column:data_identifier;not null;comment:数据标识符" json:"data_identifier"`               // 数据标识符
	Description      *string `gorm:"column:description;comment:描述" json:"description"`                                   // 描述
	Instruct         *string `gorm:"column:instruct;comment:指令内容" json:"instruct"`                                       // 指令内容
	EnableStatus     string  `gorm:"column:enable_status;not null;comment:启用状态enable-启用disable-禁用" json:"enable_status"` // 启用状态enable-启用disable-禁用
	Remark           *string `gorm:"column:remark;comment:备注" json:"remark"`                                             // 备注
	TenantID         string  `gorm:"column:tenant_id;not null" json:"tenant_id"`
}

// TableName DeviceModelCustomCommand's table name
func (*DeviceModelCustomCommand) TableName() string {
	return TableNameDeviceModelCustomCommand
}
