// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device templates 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDeviceTemplate = "device_templates"

// DeviceTemplate mapped from table <device_templates>
type DeviceTemplate struct {
	ID             string    `gorm:"column:id;primaryKey;comment:Id" json:"id"`        // Id
	Name           string    `gorm:"column:name;not null;comment:模板名称" json:"name"`    // 模板名称
	Author         *string   `gorm:"column:author;comment:作者" json:"author"`           // 作者
	Version        *string   `gorm:"column:version;comment:版本号" json:"version"`        // 版本号
	Description    *string   `gorm:"column:description;comment:描述" json:"description"` // 描述
	TenantID       string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	CreatedAt      time.Time `gorm:"column:created_at;not null" json:"created_at"`
	UpdatedAt      time.Time `gorm:"column:updated_at;not null" json:"updated_at"`
	Flag           *int16    `gorm:"column:flag;default:1;comment:标志 默认1" json:"flag"`                // 标志 默认1
	Label          *string   `gorm:"column:label;comment:标签" json:"label"`                            // 标签
	WebChartConfig *string   `gorm:"column:web_chart_config;comment:web图表配置" json:"web_chart_config"` // web图表配置
	AppChartConfig *string   `gorm:"column:app_chart_config;comment:app图表配置" json:"app_chart_config"` // app图表配置
	Remark         *string   `gorm:"column:remark;comment:备注" json:"remark"`                          // 备注
	Path           *string   `gorm:"column:path;comment:图片路径" json:"path"`                            // 图片路径
	TypeKey        *string   `gorm:"column:type_key;comment:类型" json:"type_key"`                      // 类型
	Brand          *string   `gorm:"column:brand;comment:品牌" json:"brand"`                            // 品牌
	ModelNumber    *string   `gorm:"column:model_number;comment:型号" json:"model_number"`              // 型号
}

// TableName DeviceTemplate's table name
func (*DeviceTemplate) TableName() string {
	return TableNameDeviceTemplate
}
