// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device model attributes 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDeviceModelAttribute = "device_model_attributes"

// DeviceModelAttribute mapped from table <device_model_attributes>
type DeviceModelAttribute struct {
	ID               string    `gorm:"column:id;primaryKey;comment:id" json:"id"`                                   // id
	DeviceTemplateID string    `gorm:"column:device_template_id;not null;comment:设备模板id" json:"device_template_id"` // 设备模板id
	DataName         *string   `gorm:"column:data_name;comment:数据名称" json:"data_name"`                              // 数据名称
	DataIdentifier   string    `gorm:"column:data_identifier;not null;comment:数据标识符" json:"data_identifier"`        // 数据标识符
	ReadWriteFlag    *string   `gorm:"column:read_write_flag;comment:读写标志R-读 W-写 RW-读写" json:"read_write_flag"`     // 读写标志R-读 W-写 RW-读写
	DataType         *string   `gorm:"column:data_type;comment:数据类型String Number Boolean Enum" json:"data_type"`    // 数据类型String Number Boolean Enum
	Unit             *string   `gorm:"column:unit;comment:单位" json:"unit"`                                          // 单位
	Description      *string   `gorm:"column:description;comment:描述" json:"description"`                            // 描述
	AdditionalInfo   *string   `gorm:"column:additional_info;comment:附加信息" json:"additional_info"`                  // 附加信息
	CreatedAt        time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                   // 创建时间
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                   // 更新时间
	Remark           *string   `gorm:"column:remark;comment:备注" json:"remark"`                                      // 备注
	TenantID         string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
}

// TableName DeviceModelAttribute's table name
func (*DeviceModelAttribute) TableName() string {
	return TableNameDeviceModelAttribute
}
