// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device configs 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDeviceConfig = "device_configs"

// DeviceConfig mapped from table <device_configs>
type DeviceConfig struct {
	ID               string    `gorm:"column:id;primaryKey;comment:Id" json:"id"`                                           // Id
	Name             string    `gorm:"column:name;not null;comment:名称" json:"name"`                                         // 名称
	DeviceTemplateID *string   `gorm:"column:device_template_id;comment:设备模板id" json:"device_template_id"`                  // 设备模板id
	PayloadSchemaID  *string   `gorm:"column:payload_schema_id;comment:上行数据结构约束id" json:"payload_schema_id"`                // 上行数据结构约束id
	DeviceType       string    `gorm:"column:device_type;not null;comment:设备类型 1直连设备 2网关设备 3网关子设备" json:"device_type"`      // 设备类型 1直连设备 2网关设备 3网关子设备
	ProtocolType     *string   `gorm:"column:protocol_type;comment:协议类型" json:"protocol_type"`                              // 协议类型
	VoucherType      *string   `gorm:"column:voucher_type;comment:凭证类型" json:"voucher_type"`                                // 凭证类型
	ProtocolConfig   *string   `gorm:"column:protocol_config;comment:协议表单配置" json:"protocol_config"`                        // 协议表单配置
	DeviceConnType   *string   `gorm:"column:device_conn_type;comment:设备连接方式（默认A）A-设备连接平台B-平台连接设备" json:"device_conn_type"` // 设备连接方式（默认A）A-设备连接平台B-平台连接设备
	AdditionalInfo   *string   `gorm:"column:additional_info;default:{};comment:附加信息" json:"additional_info"`               // 附加信息
	Description      *string   `gorm:"column:description;comment:描述" json:"description"`                                    // 描述
	TenantID         string    `gorm:"column:tenant_id;not null;comment:租户id" json:"tenant_id"`                             // 租户id
	CreatedAt        time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                           // 创建时间
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                           // 更新时间
	Remark           *string   `gorm:"column:remark;comment:备注" json:"remark"`                                              // 备注
	OtherConfig      *string   `gorm:"column:other_config;comment:其他配置" json:"other_config"`                                // 其他配置
	TemplateSecret   *string   `gorm:"column:template_secret" json:"template_secret"`
	AutoRegister     int16     `gorm:"column:auto_register;not null" json:"auto_register"`
	ImageURL         *string   `gorm:"column:image_url" json:"image_url"`
}

// TableName DeviceConfig's table name
func (*DeviceConfig) TableName() string {
	return TableNameDeviceConfig
}
