// Code generated by gorm. DO NOT EDIT.
// 文件用途：设备 Modbus 点表模型（ROADMAP B1），存储 target+registers 映射。
// 核心逻辑：定义 device_modbus_profiles 表的字段映射和表名常量。
// 关键注意事项：profile 只存映射信息，绝不存设备凭证；一机一行，主键即 device_id。

package model

import (
	"time"
)

const TableNameDeviceModbusProfile = "device_modbus_profiles"

// DeviceModbusProfile mapped from table <device_modbus_profiles>
type DeviceModbusProfile struct {
	DeviceID  string     `gorm:"column:device_id;primaryKey" json:"device_id"`
	Profile   *string    `gorm:"column:profile;type:jsonb;not null" json:"profile"`
	UpdatedAt *time.Time `gorm:"column:updated_at" json:"updated_at"`
	UpdatedBy *string    `gorm:"column:updated_by" json:"updated_by"`
}

// TableName DeviceModbusProfile's table name
func (*DeviceModbusProfile) TableName() string {
	return TableNameDeviceModbusProfile
}
