// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device model custom control 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDeviceModelCustomControl = "device_model_custom_control"

// DeviceModelCustomControl mapped from table <device_model_custom_control>
type DeviceModelCustomControl struct {
	ID               string    `gorm:"column:id;primaryKey;comment:id" json:"id"`                                                    // id
	DeviceTemplateID string    `gorm:"column:device_template_id;not null;comment:设备模版ID" json:"device_template_id"`                  // 设备模版ID
	Name             string    `gorm:"column:name;not null;comment:名称" json:"name"`                                                  // 名称
	ControlType      string    `gorm:"column:control_type;not null;comment:1.控制类型2.telemetry-遥测3.attributes-属性" json:"control_type"` // 1.控制类型2.telemetry-遥测3.attributes-属性
	Description      *string   `gorm:"column:description;comment:描述" json:"description"`                                             // 描述
	Content          *string   `gorm:"column:content;comment:指令内容" json:"content"`                                                   // 指令内容
	EnableStatus     string    `gorm:"column:enable_status;not null;comment:启用状态enable-启用disable-禁用" json:"enable_status"`           // 启用状态enable-启用disable-禁用
	CreatedAt        time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                    // 创建时间
	UpdatedAt        time.Time `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                                    // 更新时间
	Remark           *string   `gorm:"column:remark;comment:备注" json:"remark"`                                                       // 备注
	TenantID         string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
}

// TableName DeviceModelCustomControl's table name
func (*DeviceModelCustomControl) TableName() string {
	return TableNameDeviceModelCustomControl
}
