// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 device user logs 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameDeviceUserLog = "device_user_logs"

// DeviceUserLog mapped from table <device_user_logs>
type DeviceUserLog struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	DeviceNum int32     `gorm:"column:device_nums;not null" json:"device_nums"`
	DeviceOn  int32     `gorm:"column:device_on;not null" json:"device_on"`
	CreatedAt time.Time `gorm:"column:created_at;not null;default:CURRENT_TIMESTAMP" json:"created_at"`
	TenantID  string    `gorm:"column:tenant_id;not null;comment:租户 id" json:"tenant_id"` // 租户 id
}

// TableName DeviceUserLog's table name
func (*DeviceUserLog) TableName() string {
	return TableNameDeviceUserLog
}
