// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 event datas 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameEventData = "event_datas"

// EventData mapped from table <event_datas>
type EventData struct {
	ID       string    `gorm:"column:id;primaryKey" json:"id"`
	DeviceID string    `gorm:"column:device_id;not null;comment:设备id（外键-关联删除）" json:"device_id"` // 设备id（外键-关联删除）
	Identify string    `gorm:"column:identify;not null;comment:数据标识符" json:"identify"`           // 数据标识符
	T        time.Time `gorm:"column:ts;not null;comment:上报时间" json:"ts"`                        // 上报时间
	Datum    *string   `gorm:"column:data;comment:数据" json:"data"`                               // 数据
	TenantID *string   `gorm:"column:tenant_id" json:"tenant_id"`
}

// TableName EventData's table name
func (*EventData) TableName() string {
	return TableNameEventData
}
