// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 groups 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameGroup = "groups"

// Group mapped from table <groups>
type Group struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	ParentID    *string   `gorm:"column:parent_id;default:0;comment:默认0是父分组" json:"parent_id"` // 默认0是父分组
	Tier        int32     `gorm:"column:tier;not null;default:1;comment:层级 从1开始" json:"tier"`  // 层级 从1开始
	Name        string    `gorm:"column:name;not null;comment:分组名称" json:"name"`               // 分组名称
	Description *string   `gorm:"column:description;comment:描述" json:"description"`            // 描述
	CreatedAt   time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`   // 创建时间
	UpdatedAt   time.Time `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`   // 更新时间
	Remark      *string   `gorm:"column:remark" json:"remark"`
	TenantID    string    `gorm:"column:tenant_id;not null;comment:租户id" json:"tenant_id"`     // 租户id
	OwnerUserID *string   `gorm:"column:owner_user_id;comment:分组拥有者用户ID" json:"owner_user_id"` // 分组拥有者用户ID
}

// TableName Group's table name
func (*Group) TableName() string {
	return TableNameGroup
}
