// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 latest device alarms 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameLatestDeviceAlarm = "latest_device_alarms"

// LatestDeviceAlarm mapped from table <latest_device_alarms>
type LatestDeviceAlarm struct {
	ID                *string    `gorm:"column:id" json:"id"`
	AlarmConfigID     *string    `gorm:"column:alarm_config_id" json:"alarm_config_id"`
	GroupID           *string    `gorm:"column:group_id" json:"group_id"`
	SceneAutomationID *string    `gorm:"column:scene_automation_id" json:"scene_automation_id"`
	Name              *string    `gorm:"column:name" json:"name"`
	Description       *string    `gorm:"column:description" json:"description"`
	Content           *string    `gorm:"column:content" json:"content"`
	AlarmStatus       *string    `gorm:"column:alarm_status" json:"alarm_status"`
	TenantID          *string    `gorm:"column:tenant_id" json:"tenant_id"`
	Remark            *string    `gorm:"column:remark" json:"remark"`
	CreateAt          *time.Time `gorm:"column:create_at" json:"create_at"`
	DeviceID          *string    `gorm:"column:device_id" json:"device_id"`
}

// TableName LatestDeviceAlarm's table name
func (*LatestDeviceAlarm) TableName() string {
	return TableNameLatestDeviceAlarm
}
