// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 logo 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

const TableNameLogo = "logo"

// Logo mapped from table <logo>
type Logo struct {
	ID             string  `gorm:"column:id;primaryKey;comment:Id" json:"id"`                               // Id
	SystemName     string  `gorm:"column:system_name;not null;comment:系统名称" json:"system_name"`             // 系统名称
	LogoCache      string  `gorm:"column:logo_cache;not null;comment:站标Logo" json:"logo_cache"`             // 站标Logo
	LogoBackground string  `gorm:"column:logo_background;not null;comment:加载页面Logo" json:"logo_background"` // 加载页面Logo
	LogoLoading    string  `gorm:"column:logo_loading;not null;comment:加载页面Logo" json:"logo_loading"`       // 加载页面Logo
	HomeBackground string  `gorm:"column:home_background;not null;comment:首页背景" json:"home_background"`     // 首页背景
	ThemeColor     string  `gorm:"column:theme_color;default:'';comment:租户级主题色" json:"theme_color"`        // 主题色（C5 白标）
	Favicon        string  `gorm:"column:favicon;default:'';comment:页签favicon" json:"favicon"`             // 页签favicon（C5 白标）
	Remark         *string `gorm:"column:remark" json:"remark"`
	TenantID       string  `gorm:"column:tenant_id;not null;default:'';comment:租户ID" json:"tenant_id"` // 租户ID（C5 白标：每租户一套品牌）
}

// TableName Logo's table name
func (*Logo) TableName() string {
	return TableNameLogo
}
