// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 message push manage 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameMessagePushManage = "message_push_manage"

// MessagePushManage mapped from table <message_push_manage>
type MessagePushManage struct {
	ID           string     `gorm:"column:id;primaryKey" json:"id"`
	UserID       string     `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`               // 用户id
	PushID       string     `gorm:"column:push_id;not null;comment:推送id" json:"push_id"`               // 推送id
	DeviceType   string     `gorm:"column:device_type;not null;comment:设备类型" json:"device_type"`       // 设备类型
	Status       int16      `gorm:"column:status;not null;default:1;comment:类型 1正常 2注销" json:"status"` // 类型 1正常 2注销
	CreateTime   time.Time  `gorm:"column:create_time;not null;comment:创建类型" json:"create_time"`       // 创建类型
	UpdateTime   *time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                // 更新时间
	DeleteTime   *time.Time `gorm:"column:delete_time;comment:删除时间" json:"delete_time"`                // 删除时间
	LastPushTime *time.Time `gorm:"column:last_push_time;comment:最后一次推送时间" json:"last_push_time"`      // 最后一次推送时间
	ErrCount     *int32     `gorm:"column:err_count;default:1;comment:联系推送错误次数" json:"err_count"`      // 联系推送错误次数
	InactiveTime *time.Time `gorm:"column:inactive_time;comment:标记不活跃时间" json:"inactive_time"`         //标记不活跃时间
}

// TableName MessagePushManage's table name
func (*MessagePushManage) TableName() string {
	return TableNameMessagePushManage
}
