// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 message push log 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameMessagePushLog = "message_push_log"

// MessagePushLog mapped from table <message_push_log>
type MessagePushLog struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	UserID      string    `gorm:"column:user_id;not null;comment:用户id" json:"user_id"`                 // 用户id
	MessageType int64     `gorm:"column:message_type;not null;comment:消息类型 1告警消息" json:"message_type"` // 消息类型 1告警消息
	Content     string    `gorm:"column:content;not null;comment:消息体内容" json:"content"`                // 消息体内容
	Status      int16     `gorm:"column:status;not null;comment:1推送成功 2推送失败" json:"status"`            // 1推送成功 2推送失败
	ErrMessage  string    `gorm:"column:err_message;not null;comment:错误信息" json:"err_message"`         // 错误信息
	CreateTime  time.Time `gorm:"column:create_time;not null;comment:发送时间" json:"create_time"`         // 发送时间
}

// TableName MessagePushLog's table name
func (*MessagePushLog) TableName() string {
	return TableNameMessagePushLog
}
