// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 message push config 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameMessagePushConfig = "message_push_config"

// MessagePushConfig mapped from table <message_push_config>
type MessagePushConfig struct {
	ID         string     `gorm:"column:id;primaryKey" json:"id"`
	URL        string     `gorm:"column:url;not null;comment:推送地址" json:"url"`                                  // 推送地址
	ConfigType int16      `gorm:"column:config_type;not null;default:1;comment:配置类型 1 推送地址" json:"config_type"` // 配置类型 1 推送地址
	CreateTime time.Time  `gorm:"column:create_time;not null;comment:创建时间" json:"create_time"`                  // 创建时间
	UpdateTime *time.Time `gorm:"column:update_time;comment:更新时间" json:"update_time"`                           // 更新时间
}

// TableName MessagePushConfig's table name
func (*MessagePushConfig) TableName() string {
	return TableNameMessagePushConfig
}
