// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 message push rule log 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import "time"

const TableNameMessagePushRuleLog = "message_push_rule_log"

// MessagePushRuleLog mapped from table <message_push_rule_log>
type MessagePushRuleLog struct {
	ID         string    `gorm:"column:id;primaryKey" json:"id"`
	UserID     string    `gorm:"column:user_id;not null" json:"user_id"`
	PushID     string    `gorm:"column:push_id;not null" json:"push_id"`
	Type       int16     `gorm:"column:type;not null;comment:1 主动失效 2被动失效 3定时任务 4自动清理" json:"type"` // 1 主动失效 2被动失效 3定时任务 4自动清理
	CreateTime time.Time `gorm:"column:create_time;not null;comment:创建类型" json:"create_time"`       // 创建类型
}

// TableName MessagePushRuleLog's table name
func (*MessagePushRuleLog) TableName() string {
	return TableNameMessagePushRuleLog
}
