// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 notification groups 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameNotificationGroup = "notification_groups"

// NotificationGroup mapped from table <notification_groups>
type NotificationGroup struct {
	ID                 string    `gorm:"column:id;primaryKey" json:"id"`
	Name               string    `gorm:"column:name;not null;comment:名称" json:"name"`                                                                                                                       // 名称
	NotificationType   string    `gorm:"column:notification_type;not null;comment:通知类型，支持组合用逗号分隔，如EMAIL,APP：MEMBER-成员通知 EMAIL-邮箱通知 SME-短信通知 VOICE-语音通知 WEBHOOK-webhook APP-手机端推送" json:"notification_type"` // 通知类型，支持组合用逗号分隔，如EMAIL,APP。类型：MEMBER-成员通知 EMAIL-邮箱通知 SME-短信通知 VOICE-语音通知 WEBHOOK-webhook APP-手机端推送
	Status             string    `gorm:"column:status;not null;comment:通知状态ON-启用 OFF-停用" json:"status"`                                                                                                     // 通知状态ON-启用 OFF-停用
	NotificationConfig *string   `gorm:"column:notification_config;comment:通知配置" json:"notification_config"`                                                                                                // 通知配置
	Description        *string   `gorm:"column:description;comment:描述" json:"description"`                                                                                                                  // 描述
	TenantID           string    `gorm:"column:tenant_id;not null;comment:租户id" json:"tenant_id"`                                                                                                           // 租户id
	CreatedAt          time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                                                                                         // 创建时间
	UpdatedAt          time.Time `gorm:"column:updated_at;not null;comment:更新时间" json:"updated_at"`                                                                                                         // 更新时间
	Remark             *string   `gorm:"column:remark;comment:备注" json:"remark"`                                                                                                                            // 备注
}

// TableName NotificationGroup's table name
func (*NotificationGroup) TableName() string {
	return TableNameNotificationGroup
}
