// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 notification services config 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

const TableNameNotificationServicesConfig = "notification_services_config"

// NotificationServicesConfig mapped from table <notification_services_config>
type NotificationServicesConfig struct {
	ID         string  `gorm:"column:id;primaryKey" json:"id"`
	Config     *string `gorm:"column:config;comment:通知配置" json:"config"`                                       // 通知配置
	NoticeType string  `gorm:"column:notice_type;not null;comment:通知类型EMAIL-邮箱配置 SME-短信配置" json:"notice_type"` // 通知类型EMAIL-邮箱配置 SME-短信配置
	Status     string  `gorm:"column:status;not null;comment:状态 OPEN-开启 CLOSE-关闭" json:"status"`               // 状态 OPEN-开启 CLOSE-关闭
	Remark     *string `gorm:"column:remark" json:"remark"`
}

// TableName NotificationServicesConfig's table name
func (*NotificationServicesConfig) TableName() string {
	return TableNameNotificationServicesConfig
}
