// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 one time tasks 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameOneTimeTask = "one_time_tasks"

// OneTimeTask mapped from table <one_time_tasks>
type OneTimeTask struct {
	ID                string    `gorm:"column:id;primaryKey" json:"id"`
	SceneAutomationID string    `gorm:"column:scene_automation_id;not null;comment:场景联动ID（外键-关联删除）" json:"scene_automation_id"`          // 场景联动ID（外键-关联删除）
	ExecutionTime     time.Time `gorm:"column:execution_time;not null;comment:执行时间" json:"execution_time"`                               // 执行时间
	ExecutingState    string    `gorm:"column:executing_state;not null;comment:1.执行状态 NEX-未执行 EXE-已执行 EXP-过期未执行" json:"executing_state"` // 1.执行状态 NEX-未执行 EXE-已执行 EXP-过期未执行
	Enabled           string    `gorm:"column:enabled;not null;comment:是否启用 Y-启用 N-停用" json:"enabled"`                                   // 是否启用 Y-启用 N-停用
	Remark            *string   `gorm:"column:remark" json:"remark"`
	ExpirationTime    int64     `gorm:"column:expiration_time;not null;comment:过期时间（默认大于执行时间五分钟5min10min30min1h1day）单位分钟" json:"expiration_time"` // 过期时间（默认大于执行时间五分钟5min10min30min1h1day）单位分钟
}

// TableName OneTimeTask's table name
func (*OneTimeTask) TableName() string {
	return TableNameOneTimeTask
}
