// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 open api keys 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameOpenAPIKey = "open_api_keys"

// OpenAPIKey mapped from table <open_api_keys>
type OpenAPIKey struct {
	ID        string     `gorm:"column:id;primaryKey" json:"id"`
	TenantID  string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	APIKey    string     `gorm:"column:api_key;not null" json:"api_key"`
	Status    *int16     `gorm:"column:status" json:"status"`
	Name      string     `gorm:"column:name;not null" json:"name"`
	CreatedAt *time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt *time.Time `gorm:"column:updated_at" json:"updated_at"`
	CreatedID *string    `gorm:"column:created_id" json:"created_id"`
}

// TableName OpenAPIKey's table name
func (*OpenAPIKey) TableName() string {
	return TableNameOpenAPIKey
}
