// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 operation logs 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameOperationLog = "operation_logs"

// OperationLog mapped from table <operation_logs>
type OperationLog struct {
	ID              string    `gorm:"column:id;primaryKey;comment:Id" json:"id"`                    // Id
	IP              string    `gorm:"column:ip;not null;comment:请求IP" json:"ip"`                    // 请求IP
	Path            *string   `gorm:"column:path;comment:请求url" json:"path"`                        // 请求url
	UserID          string    `gorm:"column:user_id;not null;comment:操作用户" json:"user_id"`          // 操作用户
	Name            *string   `gorm:"column:name;comment:接口名称" json:"name"`                         // 接口名称
	CreatedAt       time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`    // 创建时间
	Latency         *int64    `gorm:"column:latency;comment:耗时(ms)" json:"latency"`                 // 耗时(ms)
	RequestMessage  *string   `gorm:"column:request_message;comment:请求内容" json:"request_message"`   // 请求内容
	ResponseMessage *string   `gorm:"column:response_message;comment:响应内容" json:"response_message"` // 响应内容
	TenantID        string    `gorm:"column:tenant_id;not null;comment:租户id" json:"tenant_id"`      // 租户id
	Remark          *string   `gorm:"column:remark" json:"remark"`
}

// TableName OperationLog's table name
func (*OperationLog) TableName() string {
	return TableNameOperationLog
}
