// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameOtaUpgradeTask = "ota_upgrade_tasks"

// OtaUpgradeTask mapped from table <ota_upgrade_tasks>.
type OtaUpgradeTask struct {
	ID                      string     `gorm:"column:id;primaryKey;comment:Id" json:"id"`
	Name                    string     `gorm:"column:name;not null;comment:task name" json:"name"`
	OtaUpgradePackageID     string     `gorm:"column:ota_upgrade_package_id;not null;comment:ota package id" json:"ota_upgrade_package_id"`
	Description             *string    `gorm:"column:description;comment:description" json:"description"`
	CreatedAt               time.Time  `gorm:"column:created_at;not null;comment:created time" json:"created_at"`
	Remark                  *string    `gorm:"column:remark;comment:remark" json:"remark"`
	TargetMode              string     `gorm:"column:target_mode;not null;default:explicit;comment:ota target mode" json:"target_mode"`
	TargetFilter            *string    `gorm:"column:target_filter;type:jsonb;comment:ota target filter snapshot" json:"target_filter"`
	PreviewTotal            *int64     `gorm:"column:preview_total;comment:backend preview total" json:"preview_total"`
	SelectedCount           *int       `gorm:"column:selected_count;comment:selected device count" json:"selected_count"`
	CreatedBy               *string    `gorm:"column:created_by;comment:creator user id" json:"created_by"`
	CreatedByAuthority      *string    `gorm:"column:created_by_authority;comment:creator authority" json:"created_by_authority"`
	Status                  string     `gorm:"column:status;not null;default:running;comment:durable rollout status" json:"status"`
	StatusDescription       *string    `gorm:"column:status_description;comment:rollout status description" json:"status_description"`
	ScheduledAt             *time.Time `gorm:"column:scheduled_at;comment:planned rollout start" json:"scheduled_at"`
	StartedAt               *time.Time `gorm:"column:started_at;comment:actual rollout start" json:"started_at"`
	CompletedAt             *time.Time `gorm:"column:completed_at;comment:rollout terminal time" json:"completed_at"`
	TimeoutAt               *time.Time `gorm:"column:timeout_at;comment:absolute rollout deadline" json:"timeout_at"`
	TimeoutSeconds          int        `gorm:"column:timeout_seconds;not null;default:3600" json:"timeout_seconds"`
	RolloutRatePerMinute    int        `gorm:"column:rollout_rate_per_minute;not null;default:60" json:"rollout_rate_per_minute"`
	AbortFailureRatePercent *float64   `gorm:"column:abort_failure_rate_percent;type:numeric(5,2)" json:"abort_failure_rate_percent"`
	NextDispatchAt          *time.Time `gorm:"column:next_dispatch_at" json:"next_dispatch_at"`
	RateWindowStartedAt     *time.Time `gorm:"column:rate_window_started_at" json:"rate_window_started_at"`
	RateWindowDispatched    int        `gorm:"column:rate_window_dispatched;not null;default:0" json:"rate_window_dispatched"`
}

// TableName OtaUpgradeTask's table name.
func (*OtaUpgradeTask) TableName() string {
	return TableNameOtaUpgradeTask
}
