// Code generated by gorm.io/gen. DO NOT EDIT.

package model

import "time"

const TableNameOtaUpgradeTaskDetail = "ota_upgrade_task_details"

// OtaUpgradeTaskDetail mapped from table <ota_upgrade_task_details>.
type OtaUpgradeTaskDetail struct {
	ID                    string     `gorm:"column:id;primaryKey;comment:Id" json:"id"`
	OtaUpgradeTaskID      string     `gorm:"column:ota_upgrade_task_id;not null;comment:upgrade task id" json:"ota_upgrade_task_id"`
	DeviceID              string     `gorm:"column:device_id;not null;comment:device id" json:"device_id"`
	Step                  *int16     `gorm:"column:steps;comment:upgrade progress 1-100" json:"steps"`
	Status                int16      `gorm:"column:status;not null;comment:1 pending 2 pushed 3 upgrading 4 succeeded 5 failed 6 canceled" json:"status"`
	StatusDescription     *string    `gorm:"column:status_description;comment:status description" json:"status_description"`
	UpdatedAt             *time.Time `gorm:"column:updated_at" json:"updated_at"`
	Remark                *string    `gorm:"column:remark" json:"remark"`
	DispatchAttempts      int        `gorm:"column:dispatch_attempts;not null;default:0" json:"dispatch_attempts"`
	DispatchLeaseToken    *string    `gorm:"column:dispatch_lease_token" json:"-"`
	DispatchLeaseUntil    *time.Time `gorm:"column:dispatch_lease_until" json:"-"`
	LastDispatchStartedAt *time.Time `gorm:"column:last_dispatch_started_at" json:"last_dispatch_started_at"`
}

// TableName returns OtaUpgradeTaskDetail's table name.
func (*OtaUpgradeTaskDetail) TableName() string {
	return TableNameOtaUpgradeTaskDetail
}
