// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 products 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameProduct = "products"

// Product mapped from table <products>
type Product struct {
	ID             string    `gorm:"column:id;primaryKey;comment:uuid" json:"id"`                // uuid
	Name           string    `gorm:"column:name;not null;comment:产品名称" json:"name"`              // 产品名称
	Description    *string   `gorm:"column:description;comment:描述" json:"description"`           // 描述
	ProductType    *string   `gorm:"column:product_type;comment:产品类型" json:"product_type"`       // 产品类型
	ProductKey     *string   `gorm:"column:product_key;comment:产品key" json:"product_key"`        // 产品key
	ProductModel   *string   `gorm:"column:product_model;comment:产品型号(编号)" json:"product_model"` // 产品型号(编号)
	ImageURL       *string   `gorm:"column:image_url;comment:图片" json:"image_url"`               // 图片
	CreatedAt      time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`  // 创建时间
	Remark         *string   `gorm:"column:remark" json:"remark"`
	AdditionalInfo *string   `gorm:"column:additional_info" json:"additional_info"`
	TenantID       *string   `gorm:"column:tenant_id;comment:租户id" json:"tenant_id"` // 租户id
	DeviceConfigID *string   `gorm:"column:device_config_id" json:"device_config_id"`
}

// TableName Product's table name
func (*Product) TableName() string {
	return TableNameProduct
}
