// Code generated by gorm. DO NOT EDIT.
// 文件用途：规则链数据模型，定义规则链主表、节点表和连接表的 ORM 映射。
// 核心逻辑：DAG 有向无环图存储——rule_chains 主表 + rule_chain_nodes 节点表 + rule_chain_edges 边表。
// 关键注意事项：删除 rule_chain 时级联删除 nodes 和 edges；node_key 是前端 Vue Flow 的节点标识。
package model

import "time"

const (
	TableNameRuleChain     = "rule_chains"
	TableNameRuleChainNode = "rule_chain_nodes"
	TableNameRuleChainEdge = "rule_chain_edges"
)

type RuleChain struct {
	ID          string    `gorm:"column:id;primaryKey" json:"id"`
	Name        string    `gorm:"column:name;not null" json:"name"`
	Description *string   `gorm:"column:description" json:"description"`
	Enabled     bool      `gorm:"column:enabled;not null;default:true" json:"enabled"`
	TenantID    string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	CreatedBy   *string   `gorm:"column:created_by" json:"created_by"`
	CreatedAt   time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   time.Time `gorm:"column:updated_at" json:"updated_at"`
}

func (*RuleChain) TableName() string { return TableNameRuleChain }

type RuleChainNode struct {
	ID        string    `gorm:"column:id;primaryKey" json:"id"`
	ChainID   string    `gorm:"column:chain_id;not null" json:"chain_id"`
	NodeKey   string    `gorm:"column:node_key;not null" json:"node_key"`
	NodeType  string    `gorm:"column:node_type;not null" json:"node_type"`
	Subtype   string    `gorm:"column:subtype;not null;default:''" json:"subtype"`
	Label     *string   `gorm:"column:label" json:"label"`
	Config    *string   `gorm:"column:config;type:jsonb;default:{}" json:"config"`
	PositionX float64   `gorm:"column:position_x;not null;default:0" json:"position_x"`
	PositionY float64   `gorm:"column:position_y;not null;default:0" json:"position_y"`
	CreatedAt time.Time `gorm:"column:created_at" json:"created_at"`
}

func (*RuleChainNode) TableName() string { return TableNameRuleChainNode }

type RuleChainEdge struct {
	ID            string  `gorm:"column:id;primaryKey" json:"id"`
	ChainID       string  `gorm:"column:chain_id;not null" json:"chain_id"`
	SourceNodeKey string  `gorm:"column:source_node_key;not null" json:"source_node_key"`
	TargetNodeKey string  `gorm:"column:target_node_key;not null" json:"target_node_key"`
	Label         *string `gorm:"column:label" json:"label"`
}

func (*RuleChainEdge) TableName() string { return TableNameRuleChainEdge }
