// Code generated by gorm. DO NOT EDIT.
// 文件用途：规则链模型（ROADMAP B2），DAG 图定义持久化。
// 核心逻辑：定义 rule_chains 表的字段映射和表名常量。
// 关键注意事项：graph 为 {nodes:[],edges:[]} JSONB；enabled=false 的链不参与上行执行。

package model

import (
	"time"
)

const TableNameRuleChain = "rule_chains"

// RuleChain mapped from table <rule_chains>
type RuleChain struct {
	ID          string     `gorm:"column:id;primaryKey" json:"id"`
	TenantID    string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Name        string     `gorm:"column:name;not null" json:"name"`
	Description *string    `gorm:"column:description" json:"description"`
	Enabled     bool       `gorm:"column:enabled;not null;default:true" json:"enabled"`
	Graph       []byte     `gorm:"column:graph;type:jsonb;not null" json:"graph"`
	CreatedAt   *time.Time `gorm:"column:created_at" json:"created_at"`
	UpdatedAt   *time.Time `gorm:"column:updated_at" json:"updated_at"`
}

// TableName RuleChain's table name
func (*RuleChain) TableName() string {
	return TableNameRuleChain
}
