// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 scene action info 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameSceneActionInfo = "scene_action_info"

// SceneActionInfo mapped from table <scene_action_info>
type SceneActionInfo struct {
	ID              string     `gorm:"column:id;primaryKey" json:"id"`
	SceneID         string     `gorm:"column:scene_id;not null;comment:场景id（关联删除）" json:"scene_id"`                                            // 场景id（关联删除）
	ActionTarget    string     `gorm:"column:action_target;not null;comment:动作目标id设备id、设备配置id，场景id、告警id" json:"action_target"`                 // 动作目标id设备id、设备配置id，场景id、告警id
	ActionType      string     `gorm:"column:action_type;not null;comment:动作类型10: 单个设备11: 单类设备20: 激活场景30: 触发告警40: 服务" json:"action_type"` // 动作类型10: 单个设备11: 单类设备20: 激活场景30: 触发告警40: 服务
	ActionParamType *string    `gorm:"column:action_param_type;comment:1.参数类型TEL:遥测 2.ATTR:属性 CMD:命令" json:"action_param_type"`               // 1.参数类型TEL:遥测 2.ATTR:属性 CMD:命令
	ActionParam     *string    `gorm:"column:action_param;comment:动作参数" json:"action_param"`                                                   // 动作参数
	ActionValue     *string    `gorm:"column:action_value;comment:目标值" json:"action_value"`                                                    // 目标值
	CreatedAt       time.Time  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`                                              // 创建时间
	UpdatedAt       *time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`                                                       // 更新时间
	TenantID        string     `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Remark          *string    `gorm:"column:remark" json:"remark"`
}

// TableName SceneActionInfo's table name
func (*SceneActionInfo) TableName() string {
	return TableNameSceneActionInfo
}
