// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 scene automations 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameSceneAutomation = "scene_automations"

// SceneAutomation mapped from table <scene_automations>
type SceneAutomation struct {
	ID          string     `gorm:"column:id;primaryKey;comment:联动" json:"id"`                     // 联动
	Name        string     `gorm:"column:name;not null;comment:名称" json:"name"`                   // 名称
	Description *string    `gorm:"column:description;comment:描述" json:"description"`              // 描述
	Enabled     string     `gorm:"column:enabled;not null;comment:是否启用 Y：启用 N：停用" json:"enabled"` // 是否启用 Y：启用 N：停用
	TenantID    string     `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenant_id"`       // 租户ID
	Creator     string     `gorm:"column:creator;not null;comment:创建人id" json:"creator"`          // 创建人id
	Updator     string     `gorm:"column:updator;not null;comment:修改人id" json:"updator"`          // 修改人id
	CreatedAt   time.Time  `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"`     // 创建时间
	UpdatedAt   *time.Time `gorm:"column:updated_at;comment:更新时间" json:"updated_at"`              // 更新时间
	Remark      *string    `gorm:"column:remark" json:"remark"`
}

// TableName SceneAutomation's table name
func (*SceneAutomation) TableName() string {
	return TableNameSceneAutomation
}
