// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 scene automation log 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameSceneAutomationLog = "scene_automation_log"

// SceneAutomationLog mapped from table <scene_automation_log>
type SceneAutomationLog struct {
	SceneAutomationID string    `gorm:"column:scene_automation_id;not null;comment:场景联动ID（外键-关联删除）" json:"scene_automation_id"` // 场景联动ID（外键-关联删除）
	ExecutedAt        time.Time `gorm:"column:executed_at;not null;comment:执行时间" json:"executed_at"`                            // 执行时间
	Detail            string    `gorm:"column:detail;not null;comment:执行说明：详细的执行过程" json:"detail"`                              // 执行说明：详细的执行过程
	ExecutionResult   string    `gorm:"column:execution_result;not null;comment:执行状态S：成功F：失败 全部执行成功才算" json:"execution_result"` // 执行状态S：成功F：失败 全部执行成功才算
	TenantID          string    `gorm:"column:tenant_id;not null" json:"tenant_id"`
	Remark            *string   `gorm:"column:remark" json:"remark"`
}

// TableName SceneAutomationLog's table name
func (*SceneAutomationLog) TableName() string {
	return TableNameSceneAutomationLog
}
