// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 service plugins 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameServicePlugin = "service_plugins"

// ServicePlugin mapped from table <service_plugins>
type ServicePlugin struct {
	ID                string     `gorm:"column:id;primaryKey;comment:服务ID" json:"id"`                                   // 服务ID
	Name              string     `gorm:"column:name;not null;comment:服务名称" json:"name"`                                 // 服务名称
	ServiceIdentifier string     `gorm:"column:service_identifier;not null;comment:服务标识符" json:"service_identifier"`    // 服务标识符
	ServiceType       int32      `gorm:"column:service_type;not null;comment:服务类型: 1-接入协议, 2-接入服务" json:"service_type"` // 服务类型: 1-接入协议, 2-接入服务
	LastActiveTime    *time.Time `gorm:"column:last_active_time;comment:服务最后活跃时间" json:"last_active_time"`              // 服务最后活跃时间
	Version           *string    `gorm:"column:version;comment:版本号" json:"version"`                                     // 版本号
	CreateAt          time.Time  `gorm:"column:create_at;not null;comment:创建时间" json:"create_at"`                       // 创建时间
	UpdateAt          time.Time  `gorm:"column:update_at;not null;comment:更新时间" json:"update_at"`                       // 更新时间
	Description       *string    `gorm:"column:description;comment:描述" json:"description"`                              // 描述
	ServiceConfig     *string    `gorm:"column:service_config;comment:服务配置: 接入协议和接入服务的配置" json:"service_config"`        // 服务配置: 接入协议和接入服务的配置
	Remark            *string    `gorm:"column:remark;comment:备注" json:"remark"`                                        // 备注
}

// TableName ServicePlugin's table name
func (*ServicePlugin) TableName() string {
	return TableNameServicePlugin
}
