// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 service access 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameServiceAccess = "service_access"

// ServiceAccess mapped from table <service_access>
type ServiceAccess struct {
	ID                  string    `gorm:"column:id;primaryKey;comment:接入ID" json:"id"`                             // 接入ID
	Name                string    `gorm:"column:name;not null;comment:名称" json:"name"`                             // 名称
	ServicePluginID     string    `gorm:"column:service_plugin_id;not null;comment:服务ID" json:"service_plugin_id"` // 服务ID
	Voucher             string    `gorm:"column:voucher;not null;comment:凭证" json:"voucher"`                       // 凭证
	Description         *string   `gorm:"column:description;comment:描述" json:"description"`                        // 描述
	ServiceAccessConfig *string   `gorm:"column:service_access_config;comment:服务配置" json:"service_access_config"`  // 服务配置
	Remark              *string   `gorm:"column:remark;comment:备注" json:"remark"`                                  // 备注
	CreateAt            time.Time `gorm:"column:create_at;not null;comment:创建时间" json:"create_at"`                 // 创建时间
	UpdateAt            time.Time `gorm:"column:update_at;not null;comment:更新时间" json:"update_at"`                 // 更新时间
	TenantID            string    `gorm:"column:tenant_id;not null;comment:租户ID" json:"tenant_id"`                 // 租户ID
}

// TableName ServiceAccess's table name
func (*ServiceAccess) TableName() string {
	return TableNameServiceAccess
}
