// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 sys dict 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameSysDict = "sys_dict"

// SysDict mapped from table <sys_dict>
type SysDict struct {
	ID        string    `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`               // 主键ID
	DictCode  string    `gorm:"column:dict_code;not null;comment:字典标识符" json:"dict_code"`  // 字典标识符
	DictValue string    `gorm:"column:dict_value;not null;comment:字典值" json:"dict_value"`  // 字典值
	CreatedAt time.Time `gorm:"column:created_at;not null;comment:创建时间" json:"created_at"` // 创建时间
	Remark    *string   `gorm:"column:remark;comment:备注" json:"remark"`                    // 备注
}

// TableName SysDict's table name
func (*SysDict) TableName() string {
	return TableNameSysDict
}
