// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 sys function 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

const TableNameSysFunction = "sys_function"

// SysFunction mapped from table <sys_function>
type SysFunction struct {
	ID          string  `gorm:"column:id;primaryKey;comment:id" json:"id"`                                        // id
	Name        string  `gorm:"column:name;not null;comment:功能名称" json:"name"`                                    // 功能名称
	EnableFlag  string  `gorm:"column:enable_flag;not null;comment:启用标志 enable-启用 disable-禁用" json:"enable_flag"` // 启用标志 enable-启用 disable-禁用
	Description *string `gorm:"column:description;comment:描述" json:"description"`                                 // 描述
	Remark      *string `gorm:"column:remark;comment:备注" json:"remark"`                                           // 备注
}

// TableName SysFunction's table name
func (*SysFunction) TableName() string {
	return TableNameSysFunction
}
