// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 sys ui elements 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameSysUIElement = "sys_ui_elements"

// SysUIElement mapped from table <sys_ui_elements>
type SysUIElement struct {
	ID           string    `gorm:"column:id;primaryKey;comment:主键ID" json:"id"`                                      // 主键ID
	ParentID     string    `gorm:"column:parent_id;not null;comment:父元素id" json:"parent_id"`                         // 父元素id
	ElementCode  string    `gorm:"column:element_code;not null;comment:元素标识符" json:"element_code"`                   // 元素标识符
	ElementType  int16     `gorm:"column:element_type;not null;comment:元素类型1-菜单 2-目录 3-按钮 4-路由" json:"element_type"` // 元素类型1-菜单 2-目录 3-按钮 4-路由
	Order_       *int16    `gorm:"column:orders;comment:排序" json:"orders"`                                           // 排序
	Param1       *string   `gorm:"column:param1" json:"param1"`
	Param2       *string   `gorm:"column:param2" json:"param2"`
	Param3       *string   `gorm:"column:param3" json:"param3"`
	Authority    string    `gorm:"column:authority;not null;comment:权限(多选)1-系统管理员 2-租户 例如[1,2]" json:"authority"` // 权限(多选)1-系统管理员 2-租户 例如[1,2]
	Description  *string   `gorm:"column:description;comment:描述" json:"description"`                              // 描述
	CreatedAt    time.Time `gorm:"column:created_at;not null" json:"created_at"`
	Remark       *string   `gorm:"column:remark" json:"remark"`
	Multilingual *string   `gorm:"column:multilingual;comment:多语言标识符" json:"multilingual"` // 多语言标识符
	RoutePath    *string   `gorm:"column:route_path" json:"route_path"`
}

// TableName SysUIElement's table name
func (*SysUIElement) TableName() string {
	return TableNameSysUIElement
}
