// Code generated by gorm. DO NOT EDIT.
// 文件用途：租户实体模型（ROADMAP C2 客户层级）。
// 核心逻辑：tenants 表含 parent_tenant_id 自引用，ID 与 users.tenant_id 及各业务表
//           tenant_id 同源；parent 为 NULL 表示根租户，由 60.sql backfill 存量租户登记。
// 关键注意事项：users.tenant_id 无 FK 引用本表，层级归属仅靠 tenants 表登记；
//               超出登记范围的租户 ID 在数据范围解析时退化为"仅自身"。
package model

import "time"

const TableNameTenant = "tenants"

// Tenant mapped from table <tenants>
type Tenant struct {
	ID             string     `gorm:"column:id;primaryKey" json:"id"`
	Name           string     `gorm:"column:name" json:"name"`
	Code           *string    `gorm:"column:code" json:"code"`
	ParentTenantID *string    `gorm:"column:parent_tenant_id" json:"parent_tenant_id"`
	Status         string     `gorm:"column:status" json:"status"` // N-正常 F-冻结
	Remark         *string    `gorm:"column:remark" json:"remark"`
	CreatedAt      time.Time  `gorm:"column:created_at" json:"created_at"`
	UpdatedAt      time.Time  `gorm:"column:updated_at" json:"updated_at"`
}

// TableName Tenant's table name
func (*Tenant) TableName() string {
	return TableNameTenant
}