// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 user address 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameUserAddress = "user_address"

// UserAddress mapped from table <user_address>
type UserAddress struct {
	ID              int32      `gorm:"column:id;primaryKey;autoIncrement:true;comment:地址ID，主键自增" json:"id"`            // 地址ID，主键自增
	UserID          string     `gorm:"column:user_id;not null;comment:用户ID，外键关联用户表" json:"user_id"`                    // 用户ID，外键关联用户表
	Country         *string    `gorm:"column:country;comment:国家" json:"country"`                                       // 国家
	Province        *string    `gorm:"column:province;comment:省份" json:"province"`                                     // 省份
	City            *string    `gorm:"column:city;comment:城市" json:"city"`                                             // 城市
	District        *string    `gorm:"column:district;comment:区县" json:"district"`                                     // 区县
	Street          *string    `gorm:"column:street;comment:街道/乡镇" json:"street"`                                      // 街道/乡镇
	DetailedAddress *string    `gorm:"column:detailed_address;comment:详细地址" json:"detailed_address"`                   // 详细地址
	PostalCode      *string    `gorm:"column:postal_code;comment:邮政编码" json:"postal_code"`                             // 邮政编码
	AddressLabel    *string    `gorm:"column:address_label;comment:地址标签" json:"address_label"`                         // 地址标签
	Longitude       *string    `gorm:"column:longitude;comment:经度" json:"longitude"`                                   // 经度
	Latitude        *string    `gorm:"column:latitude;comment:纬度" json:"latitude"`                                     // 纬度
	AdditionalInfo  *string    `gorm:"column:additional_info;comment:附加信息" json:"additional_info"`                     // 附加信息
	CreatedTime     *time.Time `gorm:"column:created_time;default:CURRENT_TIMESTAMP;comment:创建时间" json:"created_time"` // 创建时间
	UpdatedTime     *time.Time `gorm:"column:updated_time;default:CURRENT_TIMESTAMP;comment:更新时间" json:"updated_time"` // 更新时间
}

// TableName UserAddress's table name
func (*UserAddress) TableName() string {
	return TableNameUserAddress
}
