// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 vis files 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

const TableNameVisFile = "vis_files"

// VisFile mapped from table <vis_files>
type VisFile struct {
	ID          string  `gorm:"column:id;primaryKey" json:"id"`
	VisPluginID string  `gorm:"column:vis_plugin_id;not null;comment:可视化插件id" json:"vis_plugin_id"` // 可视化插件id
	FileName    *string `gorm:"column:file_name;comment:名称" json:"file_name"`                       // 名称
	FileURL     *string `gorm:"column:file_url;comment:url地址" json:"file_url"`                      // url地址
	FileSize    *string `gorm:"column:file_size;comment:文件大小" json:"file_size"`                     // 文件大小
	CreateAt    *int64  `gorm:"column:create_at" json:"create_at"`
	Remark      *string `gorm:"column:remark" json:"remark"`
}

// TableName VisFile's table name
func (*VisFile) TableName() string {
	return TableNameVisFile
}
