// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 vis plugin 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

const TableNameVisPlugin = "vis_plugin"

// VisPlugin mapped from table <vis_plugin>
type VisPlugin struct {
	ID                string  `gorm:"column:id;primaryKey" json:"id"`
	TenantID          string  `gorm:"column:tenant_id;not null;comment:租户id" json:"tenant_id"`          // 租户id
	PluginName        string  `gorm:"column:plugin_name;not null;comment:可视化插件名称" json:"plugin_name"`   // 可视化插件名称
	PluginDescription *string `gorm:"column:plugin_description;comment:插件描述" json:"plugin_description"` // 插件描述
	CreateAt          *int64  `gorm:"column:create_at" json:"create_at"`
	Remark            *string `gorm:"column:remark" json:"remark"`
}

// TableName VisPlugin's table name
func (*VisPlugin) TableName() string {
	return TableNameVisPlugin
}
