// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.
// Code generated by gorm.io/gen. DO NOT EDIT.

// 文件用途：定义 vis dashboard 的生成模型结构及其数据库表映射，作为 backend/internal/model 的持久化模型边界。
// 核心逻辑：保留生成器输出的字段、标签、表名常量和 TableName 方法，让 DAL/Service 层复用统一的模型契约。
// 关键注意事项：该文件属于 generated/model 边界，不在这里手工调整字段生成逻辑；业务约束应放在服务层或生成源配置中。
// 重构建议：若需重构字段、表结构或标签，请优先修改生成源、数据库迁移或模型定义后重新生成。

package model

import (
	"time"
)

const TableNameVisDashboard = "vis_dashboard"

// VisDashboard mapped from table <vis_dashboard>
type VisDashboard struct {
	ID            string     `gorm:"column:id;primaryKey" json:"id"`
	RelationID    *string    `gorm:"column:relation_id" json:"relation_id"`
	JSONDatum     *string    `gorm:"column:json_data;default:{}" json:"json_data"`
	DashboardName *string    `gorm:"column:dashboard_name" json:"dashboard_name"`
	CreateAt      *time.Time `gorm:"column:create_at" json:"create_at"`
	Sort          *int32     `gorm:"column:sort;comment:排序" json:"sort"` // 排序
	Remark        *string    `gorm:"column:remark" json:"remark"`
	TenantID      *string    `gorm:"column:tenant_id" json:"tenant_id"`
	ShareID       *string    `gorm:"column:share_id;comment:分享id" json:"share_id"` // 分享id
}

// TableName VisDashboard's table name
func (*VisDashboard) TableName() string {
	return TableNameVisDashboard
}
