// Board data access helpers.
package dal

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	model "aetherlink-iot/backend/internal/model"
	query "aetherlink-iot/backend/internal/query"
	global "aetherlink-iot/backend/pkg/global"

	"gorm.io/gen"
	"gorm.io/gorm"

	"github.com/sirupsen/logrus"
)

func UpdateBoard(boards *model.Board, tenantID string) error {
	p := query.Board
	r, err := query.Board.Where(p.ID.Eq(boards.ID), p.TenantID.Eq(tenantID)).Updates(boards)
	if err != nil {
		logrus.Error(err)
		return err
	}
	if r.RowsAffected == 0 {
		return fmt.Errorf("no data updated")
	}
	return err
}

func DeleteBoard(id string, tenantID string) error {
	r, err := query.Board.Where(query.Board.ID.Eq(id), query.Board.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		logrus.Error(err)
		return err
	}
	if r.RowsAffected == 0 {
		return gorm.ErrRecordNotFound
	}
	return nil
}

// PublishBoard marks a native board as publicly viewable and returns the
// persisted record. The share token is generated by the service layer so the
// DAL remains responsible only for the tenant-scoped write.
func PublishBoard(id string, tenantID string, shareToken string, publishedAt time.Time) (*model.Board, error) {
	p := query.Board
	result, err := p.Where(p.ID.Eq(id), p.TenantID.Eq(tenantID), p.VisType.Eq("native")).Updates(map[string]interface{}{
		"published":    true,
		"published_at": publishedAt,
		"share_token":  shareToken,
		"updated_at":   publishedAt,
	})
	if err != nil {
		logrus.Error(err)
		return nil, err
	}
	if result.RowsAffected == 0 {
		return nil, gorm.ErrRecordNotFound
	}
	return p.Where(p.ID.Eq(id), p.TenantID.Eq(tenantID)).First()
}

// GetPublishedBoardByShareToken is intentionally the only unauthenticated
// board lookup. It requires both a matching token and the native published
// flag, so an unpublished or ThingsVis board cannot be exposed through this
// endpoint.
// tenant-scope: public-share?2026-08-26 ?????
func GetPublishedBoardByShareToken(shareToken string) (*model.Board, error) {
	p := query.Board
	return p.Where(
		p.ShareToken.Eq(shareToken),
		p.Published.Is(true),
		p.VisType.Eq("native"),
	).First()
}

// GetPublishedBoardsByShareTokens 批量按 share token 取已发布原生看板（TP-22 大屏轮播）。
// tenant-scope: public-share——share_token 是发布方主动公开的能力凭证（与
// GetPublishedBoardByShareToken 同语义）：跨 token 可能来自不同租户，本查询刻意
// 不带 tenant_id 过滤；仅放行 published=true 且 vis_type=native 的行，
// 未发布/非原生/未知 token 在 DAL 层即不可见（fail-closed）。
// 返回顺序不保证，由服务层按请求顺序重排。
func GetPublishedBoardsByShareTokens(tokens []string) ([]*model.Board, error) {
	if len(tokens) == 0 {
		return []*model.Board{}, nil
	}
	p := query.Board
	rows, err := p.Where(
		p.ShareToken.In(tokens...),
		p.Published.Is(true),
		p.VisType.Eq("native"),
	).Find()
	if err != nil {
		logrus.Error(err)
		return nil, err
	}
	return rows, nil
}

// GetBoardListByPageForScopesWithGroupScope 组共享可见性变体（TB-46 GPE v1）：
// hiddenBoardIDs 非空时按 ID 排除（组绑定且调用者非组内成员的看板，fail-closed 隐藏）。
// tenant-scope: caller-enforced (scopes 由 service 层展开并校验；nil=管理员全量)。
func GetBoardListByPageForScopesWithGroupScope(boards *model.GetBoardListByPageReq, scopes []string, hiddenBoardIDs []string) (int64, interface{}, error) {
	return boardListByScopes(boards, scopes, hiddenBoardIDs)
}

func boardListByScopes(boards *model.GetBoardListByPageReq, scopes []string, hiddenBoardIDs []string) (int64, interface{}, error) {
	q := query.Board
	var count int64
	queryBuilder := q.WithContext(context.Background())
	// An empty scope list is reserved for SYS_ADMIN's explicit all-tenant list scope.
	if len(scopes) > 0 {
		switch len(scopes) {
		case 1:
			queryBuilder = queryBuilder.Where(q.TenantID.Eq(scopes[0]))
		default:
			queryBuilder = queryBuilder.Where(q.TenantID.In(scopes...))
		}
	}

	if boards.Name != nil && *boards.Name != "" {
		queryBuilder = queryBuilder.Where(q.Name.Like(ContainsLikePattern(*boards.Name)))
	}

	if boards.HomeFlag != nil && *boards.HomeFlag != "" {
		queryBuilder = queryBuilder.Where(q.HomeFlag.Eq(*boards.HomeFlag))
	}

	if boards.VisType != nil && *boards.VisType != "" {
		queryBuilder = queryBuilder.Where(q.VisType.Eq(*boards.VisType))
	}

	// 组共享可见性（TB-46 GPE v1）：hiddenBoardIDs = 组绑定且调用者不可见的看板。
	// gen 的 NotIn 不接受空参数（见下方 projectID 分支注释），故先判空。
	if len(hiddenBoardIDs) > 0 {
		queryBuilder = queryBuilder.Where(q.ID.NotIn(hiddenBoardIDs...))
	}

	// 看板项目分组过滤：先解析项目成员看板 ID，再按 ID 集合过滤。
	// scopes 恰好一个租户时成员查找限租户；SYS_ADMIN 全量视图时不限。
	// "none" 表示内置项目（不落库的默认分组）= 不属于任何项目的看板。
	if boards.ProjectID != nil {
		projectID := strings.TrimSpace(*boards.ProjectID)
		if projectID != "" {
			tenantForProject := ""
			if len(scopes) == 1 {
				tenantForProject = scopes[0]
			}
			if projectID == "none" {
				// 内置项目 = 不属于任何项目的看板。成员表可能为空：此时无排除集，
				// 全部看板都属内置项目（gen 的 NotIn 不接受空参数，必须分支处理）。
				memberIDs, merr := ListAllProjectMemberBoardIDs(tenantForProject)
				if merr != nil {
					logrus.Error(merr)
					return 0, nil, merr
				}
				if len(memberIDs) > 0 {
					queryBuilder = queryBuilder.Where(q.ID.NotIn(memberIDs...))
				}
			} else {
				memberIDs, merr := ListBoardIDsByProject(projectID, tenantForProject)
				if merr != nil {
					logrus.Error(merr)
					return 0, nil, merr
				}
				if len(memberIDs) == 0 {
					return 0, []interface{}{}, nil
				}
				queryBuilder = queryBuilder.Where(q.ID.In(memberIDs...))
			}
		}
	}

	count, err := queryBuilder.Count()
	if err != nil {
		logrus.Error(err)
		return count, nil, err
	}
	queryBuilder = applyListPagination(queryBuilder, boards.Page, boards.PageSize)
	queryBuilder = queryBuilder.Order(q.CreatedAt.Desc())
	boardsList, err := queryBuilder.Select(
		q.ID,
		q.Name,
		q.HomeFlag,
		q.MenuFlag,
		q.UpdatedAt,
		q.CreatedAt,
		q.Description,
		q.Remark,
		q.TenantID,
		q.VisType,
		q.Published,
		q.PublishedAt,
		q.ShareToken,
	).Find()
	if err != nil {
		logrus.Error(err)
		return count, boardsList, err
	}

	return count, boardsList, nil
}

func GetBoard(id string, tenantId string) (interface{}, error) {
	p := query.Board
	board, err := query.Board.Where(p.ID.Eq(id)).Where(p.TenantID.Eq(tenantId)).Select().First()
	if err != nil {
		logrus.Error(err)
	}
	return board, err
}

func GetBoardListByTenantId(tenantid string) (int64, interface{}, error) {
	q := query.Board
	var count int64
	queryBuilder := q.WithContext(context.Background())
	boardsList, err := queryBuilder.Where(q.TenantID.Eq(tenantid), q.HomeFlag.Eq("Y")).Select().First()
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return count, nil, nil
		}
		logrus.Error(err)
		return count, boardsList, err
	}
	count, err = queryBuilder.Count()
	return count, boardsList, err
}

type BoardQuery struct{}

func (BoardQuery) Create(ctx context.Context, info *model.Board) (*model.Board, error) {
	var (
		board = query.Board
		err   error
	)
	if err = board.WithContext(ctx).Create(info); err != nil {
		logrus.Error(ctx, "[BoardQuery]First failed:", err)
	}
	return info, err
}

func (BoardQuery) First(ctx context.Context, option ...gen.Condition) (info *model.Board, err error) {
	board := query.Board
	info, err = board.WithContext(ctx).Where(option...).First()
	if err != nil {
		logrus.Error(ctx, "[BoardQuery]First failed:", err)
	}
	return info, err
}

// UpdateHomeFlagN clears the existing home flag before a new home board is saved.
func (BoardQuery) UpdateHomeFlagN(ctx context.Context, tenantid string) error {
	var (
		board = query.Board
		err   error
	)
	if _, err := board.WithContext(ctx).Where(query.Board.TenantID.Eq(tenantid), query.Board.HomeFlag.Eq("Y")).Updates(map[string]interface{}{"home_flag": "N"}); err != nil {
		logrus.Error(ctx, "update failed:", err)
	}
	return err
}

// GetBoardByNameAndTenant 查询指定租户下指定名称的看板（TB-15）。
func (BoardQuery) GetBoardByNameAndTenant(ctx context.Context, tenantID, name string) (*model.Board, error) {
	var b model.Board
	err := global.DB.WithContext(ctx).Where("tenant_id = ? AND name = ?", tenantID, name).First(&b).Error
	if err != nil {
		return nil, err
	}
	return &b, nil
}

// GetBoardNamesMatchingBase 查询指定租户下 baseName 或 baseName (N) 形式的看板名称列表（TB-15）。
func (BoardQuery) GetBoardNamesMatchingBase(ctx context.Context, tenantID, baseName string) ([]string, error) {
	var names []string
	err := global.DB.WithContext(ctx).Model(&model.Board{}).
		Where("tenant_id = ? AND (name = ? OR name LIKE ?)", tenantID, baseName, baseName+" (%)").
		Pluck("name", &names).Error
	return names, err
}
