// Board data access helpers.
package dal

import (
	"context"
	"errors"
	"fmt"
	"strings"
	"time"

	model "aetherlink-iot/backend/internal/model"
	query "aetherlink-iot/backend/internal/query"
	global "aetherlink-iot/backend/pkg/global"

	"gorm.io/gen"
	"gorm.io/gorm"

	"github.com/sirupsen/logrus"
)

func CreateBoard(boards *model.Board) error {
	if _, err := query.Board.Where(query.Board.HomeFlag.Eq("Y"), query.Board.TenantID.Eq(boards.TenantID)).First(); err == nil {
		return fmt.Errorf("home board already exists")
	}
	return query.Board.Create(boards)
}

func UpdateBoard(boards *model.Board, tenantID string) error {
	p := query.Board
	r, err := query.Board.Where(p.ID.Eq(boards.ID), p.TenantID.Eq(tenantID)).Updates(boards)
	if err != nil {
		logrus.Error(err)
		return err
	}
	if r.RowsAffected == 0 {
		return fmt.Errorf("no data updated")
	}
	return err
}

func DeleteBoard(id string, tenantID string) error {
	r, err := query.Board.Where(query.Board.ID.Eq(id), query.Board.TenantID.Eq(tenantID)).Delete()
	if err != nil {
		logrus.Error(err)
		return err
	}
	if r.RowsAffected == 0 {
		return nil
	}
	return nil
}

// PublishBoard marks a native board as publicly viewable and returns the
// persisted record. The share token is generated by the service layer so the
// DAL remains responsible only for the tenant-scoped write.
func PublishBoard(id string, tenantID string, shareToken string, publishedAt time.Time) (*model.Board, error) {
	p := query.Board
	result, err := p.Where(p.ID.Eq(id), p.TenantID.Eq(tenantID), p.VisType.Eq("native")).Updates(map[string]interface{}{
		"published":    true,
		"published_at": publishedAt,
		"share_token":  shareToken,
		"updated_at":   publishedAt,
	})
	if err != nil {
		logrus.Error(err)
		return nil, err
	}
	if result.RowsAffected == 0 {
		return nil, gorm.ErrRecordNotFound
	}
	return p.Where(p.ID.Eq(id), p.TenantID.Eq(tenantID)).First()
}

// GetPublishedBoardByShareToken is intentionally the only unauthenticated
// board lookup. It requires both a matching token and the native published
// flag, so an unpublished or ThingsVis board cannot be exposed through this
// endpoint.
// tenant-scope: public-share?2026-08-26 ?????
func GetPublishedBoardByShareToken(shareToken string) (*model.Board, error) {
	p := query.Board
	return p.Where(
		p.ShareToken.Eq(shareToken),
		p.Published.Is(true),
		p.VisType.Eq("native"),
	).First()
}

func GetBoardListByPage(boards *model.GetBoardListByPageReq, tenantId string) (int64, interface{}, error) {
	q := query.Board
	var count int64
	queryBuilder := q.WithContext(context.Background())
	// An empty tenant id is reserved for SYS_ADMIN's explicit all-tenant list
	// scope. Ordinary callers are rejected in the service layer before reaching
	// this DAL function, so an empty value must not silently become a tenant.
	if strings.TrimSpace(tenantId) != "" {
		queryBuilder = queryBuilder.Where(q.TenantID.Eq(tenantId))
	}

	if boards.Name != nil && *boards.Name != "" {
		queryBuilder = queryBuilder.Where(q.Name.Like(ContainsLikePattern(*boards.Name)))
	}

	if boards.HomeFlag != nil && *boards.HomeFlag != "" {
		queryBuilder = queryBuilder.Where(q.HomeFlag.Eq(*boards.HomeFlag))
	}

	if boards.VisType != nil && *boards.VisType != "" {
		queryBuilder = queryBuilder.Where(q.VisType.Eq(*boards.VisType))
	}
	count, err := queryBuilder.Count()
	if err != nil {
		logrus.Error(err)
		return count, nil, err
	}
	queryBuilder = applyListPagination(queryBuilder, boards.Page, boards.PageSize)
	queryBuilder = queryBuilder.Order(q.CreatedAt.Desc())
	boardsList, err := queryBuilder.Select(
		q.ID,
		q.Name,
		q.HomeFlag,
		q.MenuFlag,
		q.UpdatedAt,
		q.CreatedAt,
		q.Description,
		q.Remark,
		q.TenantID,
		q.VisType,
		q.Published,
		q.PublishedAt,
		q.ShareToken,
	).Find()
	if err != nil {
		logrus.Error(err)
		return count, boardsList, err
	}

	return count, boardsList, err
}

func GetBoard(id string, tenantId string) (interface{}, error) {
	p := query.Board
	board, err := query.Board.Where(p.ID.Eq(id)).Where(p.TenantID.Eq(tenantId)).Select().First()
	if err != nil {
		logrus.Error(err)
	}
	return board, err
}

func GetBoardListByTenantId(tenantid string) (int64, interface{}, error) {
	q := query.Board
	var count int64
	queryBuilder := q.WithContext(context.Background())
	boardsList, err := queryBuilder.Where(q.TenantID.Eq(tenantid), q.HomeFlag.Eq("Y")).Select().First()
	if err != nil {
		if errors.Is(err, gorm.ErrRecordNotFound) {
			return count, nil, nil
		}
		logrus.Error(err)
		return count, boardsList, err
	}
	count, err = queryBuilder.Count()
	return count, boardsList, err
}

type BoardQuery struct{}

func (BoardQuery) Create(ctx context.Context, info *model.Board) (*model.Board, error) {
	var (
		board = query.Board
		err   error
	)
	if err = board.WithContext(ctx).Create(info); err != nil {
		logrus.Error(ctx, "[BoardQuery]First failed:", err)
	}
	return info, err
}

func (BoardQuery) First(ctx context.Context, option ...gen.Condition) (info *model.Board, err error) {
	board := query.Board
	info, err = board.WithContext(ctx).Where(option...).First()
	if err != nil {
		logrus.Error(ctx, "[BoardQuery]First failed:", err)
	}
	return info, err
}

// UpdateHomeFlagN clears the existing home flag before a new home board is saved.
func (BoardQuery) UpdateHomeFlagN(ctx context.Context, tenantid string) error {
	var (
		board = query.Board
		err   error
	)
	if _, err := board.WithContext(ctx).Where(query.Board.TenantID.Eq(tenantid), query.Board.HomeFlag.Eq("Y")).Updates(map[string]interface{}{"home_flag": "N"}); err != nil {
		logrus.Error(ctx, "update failed:", err)
	}
	return err
}

// GetDeviceTrend returns hourly online and offline device counts for the tenant.
// tenantID identifies the tenant scope.
// GetDeviceTrend returns hourly online and offline device counts for the tenant.
// tenantID identifies the tenant scope.
// startTime defaults to the previous 48 hours when omitted.
// endTime defaults to now when omitted.
func GetDeviceTrend(tenantID string, ownerUserID *string, startTime, endTime *int64) ([]model.DeviceTrendPoint, error) {
	now := time.Now()
	if endTime == nil {
		t := now.Unix()
		endTime = &t
	}
	if startTime == nil {
		t := now.Add(-48 * time.Hour).Unix()
		startTime = &t
	}

	startTimeUTC := time.Unix(*startTime, 0).UTC()
	endTimeUTC := time.Unix(*endTime, 0).UTC()

	var results []model.DeviceTrendPoint

	sql := `
WITH
-- 1. Build the hourly time series.
hour_series AS (
    SELECT generate_series AS hour_ts
    FROM generate_series($2::timestamptz, $3::timestamptz, '1 hour') AS generate_series
),
-- 2. Count devices created before the requested end time.
device_total AS (
    SELECT COUNT(*)::bigint AS total_cnt
    FROM devices
    WHERE tenant_id = $1
      AND ($4 = '' OR owner_user_id = $4)
      AND activate_flag <> 'inactive'
      AND created_at <= $3
),
-- 3. Count devices already online before the requested range.
before_online AS (
    SELECT COUNT(DISTINCT dsh.device_id)::bigint AS cnt
    FROM device_status_history dsh
    INNER JOIN (
        SELECT device_id, MAX(id) AS max_id
        FROM device_status_history
        WHERE tenant_id = $1 AND change_time < $2
          AND device_id IN (
              SELECT id FROM devices
              WHERE tenant_id = $1
                AND activate_flag <> 'inactive'
                AND ($4 = '' OR owner_user_id = $4)
          )
        GROUP BY device_id
    ) latest ON dsh.id = latest.max_id
    WHERE dsh.status = 1
),
-- 4. Estimate devices that never emitted status changes.
never_reported AS (
    SELECT COUNT(*)::bigint AS cnt
    FROM devices d
    WHERE d.tenant_id = $1
      AND ($4 = '' OR d.owner_user_id = $4)
      AND d.activate_flag <> 'inactive'
      AND d.created_at <= $3
      AND d.is_online = 1
      AND NOT EXISTS (
          SELECT 1
          FROM device_status_history dsh
          WHERE dsh.tenant_id = $1
            AND dsh.device_id = d.id
      )
),
-- 5. Load latest status change per device per hour inside the requested range.
all_changes AS (
    SELECT
        dsh.device_id,
        dsh.status,
        date_trunc('hour', dsh.change_time) AS hour_ts
    FROM device_status_history dsh
    INNER JOIN (
        SELECT device_id,
               date_trunc('hour', change_time) AS hour_ts,
               MAX(id) AS max_id
        FROM device_status_history
        WHERE tenant_id = $1
          AND change_time >= $2
          AND change_time <= $3
          AND device_id IN (
              SELECT id FROM devices
              WHERE tenant_id = $1
                AND activate_flag <> 'inactive'
                AND ($4 = '' OR owner_user_id = $4)
          )
        GROUP BY device_id, date_trunc('hour', change_time)
    ) latest ON dsh.id = latest.max_id
),
-- 6. Compare each hourly status point with the previous point.
device_prev AS (
    SELECT
        device_id,
        hour_ts,
        status,
        LAG(status) OVER (
            PARTITION BY device_id ORDER BY hour_ts
        ) AS prev_status
    FROM all_changes
),
-- 7. Aggregate per-hour online and offline deltas.
hourly_delta AS (
    SELECT hour_ts,
        COUNT(*) FILTER (
            WHERE status = 1 AND (prev_status IS NULL OR prev_status != 1)
        )::bigint AS online_delta,
        COUNT(*) FILTER (
            WHERE status = 0 AND (prev_status IS NULL OR prev_status != 0)
        )::bigint AS offline_delta
    FROM device_prev
    GROUP BY hour_ts
),
-- 8. Merge the base online count with per-hour deltas.
merged AS (
    SELECT
        s.hour_ts,
        (SELECT cnt FROM before_online) + (SELECT cnt FROM never_reported) AS init_online,
        COALESCE(h.online_delta,  0)::bigint AS od,
        COALESCE(h.offline_delta, 0)::bigint AS fd
    FROM hour_series s
    LEFT JOIN hourly_delta h ON h.hour_ts = s.hour_ts
),
-- 9. Roll forward the online count hour by hour.
--    cur_online = GREATEST(0, prev_online + od - fd)
with_online AS (
    SELECT
        hour_ts,
        GREATEST(
            init_online + SUM(od - fd) OVER (
                ORDER BY hour_ts
                ROWS BETWEEN UNBOUNDED PRECEDING AND CURRENT ROW
            ), 0
        )::bigint AS cur_online
    FROM merged
)
-- 10. Return hourly total, online, and offline counts.
SELECT
    h.hour_ts                                        AS timestamp,
    t.total_cnt                                      AS device_total,
    LEAST(w.cur_online, t.total_cnt)::bigint         AS device_online,
    GREATEST(t.total_cnt - LEAST(w.cur_online, t.total_cnt), 0)::bigint AS device_offline
FROM with_online w
JOIN merged h ON h.hour_ts = w.hour_ts
CROSS JOIN device_total t
ORDER BY h.hour_ts ASC;
`
	ownerFilter := ""
	if ownerUserID != nil {
		ownerFilter = strings.TrimSpace(*ownerUserID)
	}
	err := global.DB.Raw(sql, tenantID, startTimeUTC, endTimeUTC, ownerFilter).Scan(&results).Error
	if err != nil {
		logrus.Error("GetDeviceTrend query failed")
		return nil, err
	}

	return results, nil
}

// Device trend queries intentionally keep SQL comments close to the CTEs above.
