const { metadataCase, e2eCase } = require("./helpers");

module.exports = {
  "tests/00_coverage_contract.test.js": {
    file: "tests/00_coverage_contract.test.js",
    type: "api",
    evidenceKind: "contract",
    fileFlags: {},
    cases: [],
  },
  "tests/00_e2e_metadata_contract.test.js": {
    file: "tests/00_e2e_metadata_contract.test.js",
    type: "api",
    evidenceKind: "contract",
    fileFlags: {},
    cases: [],
  },
  "tests/00_endpoint_coverage.test.js": {
    file: "tests/00_endpoint_coverage.test.js",
    type: "api",
    evidenceKind: "catalog",
    fileFlags: {},
    cases: [],
  },
  "tests/00_oracle_contract.test.js": {
    file: "tests/00_oracle_contract.test.js",
    type: "api",
    evidenceKind: "contract",
    fileFlags: {},
    cases: [],
  },
  "tests/00_preflight_api_e2e.test.js": {
    file: "tests/00_preflight_api_e2e.test.js",
    type: "api",
    evidenceKind: "preflight",
    fileFlags: {},
    cases: [],
  },
  "tests/00_runtime_config_env.test.js": {
    file: "tests/00_runtime_config_env.test.js",
    type: "api",
    evidenceKind: "config",
    fileFlags: {},
    cases: [],
  },
  ...Object.fromEntries(
    [
      "tests/01_auth.test.js",
      "tests/03_data.test.js",
      "tests/04_alarm.test.js",
      "tests/05_config.test.js",
      "tests/06_system.test.js",
      "tests/07_board.test.js",
      "tests/08_role.test.js",
      "tests/08_role_casbin.test.js",
      "tests/09_casbin.test.js",
      "tests/09_dict_notification.test.js",
      "tests/10_dict.test.js",
      "tests/10_ota_data_script.test.js",
      "tests/11_device_extra.test.js",
      "tests/11_notification.test.js",
      "tests/12_telemetry_extra.test.js",
      "tests/13_data_script.test.js",
      "tests/13_user_extra.test.js",
      "tests/14_attribute_command_event.test.js",
      "tests/14_device_config.test.js",
      "tests/15_device_config_openapi.test.js",
      "tests/16_write_flows.test.js",
    ].map((file) => [
      file,
      {
        file,
        type: "api",
        evidenceKind: "boundary",
        fileFlags: {
          broadApiBucket: true,
        },
        cases: [],
      },
    ]),
  ),
  "tests/14_device_config.test.js": {
    file: "tests/14_device_config.test.js",
    type: "api",
    evidenceKind: "boundary",
    fileFlags: {},
    cases: [
      metadataCase(
        "covers TC-DCFG-011 with concrete API assertions",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
      metadataCase(
        "covers TC-DCFG-012 with concrete API assertions",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
      metadataCase(
        "covers TC-DCFG-013 with concrete API assertions",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
    ],
  },
  "tests/04_alarm.test.js": {
    file: "tests/04_alarm.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "creates an alarm config through the public API",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
      metadataCase(
        "updates the alarm config created by this test run",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
      metadataCase(
        "returns the scene-seeded alarm history row",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
      metadataCase(
        "acknowledges the scene-seeded history row",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
      metadataCase(
        "resets the scene-seeded history row",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
      metadataCase(
        "returns the seeded device alarm status",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
    ],
  },
  "tests/06_system.test.js": {
    file: "tests/06_system.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "creates a UI element and verifies it appears in the list",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["system-deployment"],
      ),
      metadataCase(
        "rejects updates for a non-existent UI element id",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["system-deployment"],
      ),
      metadataCase(
        "re-saves the current logo payload without changing values",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["system-deployment"],
      ),
    ],
  },
  "tests/07_board.test.js": {
    file: "tests/07_board.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "returns the tenant board list with list and total fields",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["visualization"],
      ),
      metadataCase(
        "creates a tenant board with the current local payload shape",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["visualization"],
      ),
      metadataCase(
        "updates the created board",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["visualization"],
      ),
      metadataCase(
        "rejects tenant overview for tenant_admin in the current local deployment",
        "business",
        true,
        true,
        true,
        false,
        true,
        ["visualization"],
      ),
    ],
  },
  "tests/10_ota_data_script.test.js": {
    file: "tests/10_ota_data_script.test.js",
    type: "api",
    evidenceKind: "boundary",
    fileFlags: {
      broadApiBucket: true,
      explicitBoundaryOnly: true,
    },
    cases: [
      metadataCase(
        "rejects OTA task preview when device_filter is omitted",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "scaffolds OTA full-filter preview with a non-empty device_filter but keeps fake package boundary explicit",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "returns record-not-found for a fake OTA task support bundle id",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["ota-script-openapi-service"],
      ),
    ],
  },
  "tests/14_attribute_command_event.test.js": {
    file: "tests/14_attribute_command_event.test.js",
    type: "api",
    evidenceKind: "boundary",
    fileFlags: {
      explicitBoundaryOnly: true,
    },
    cases: [
      metadataCase(
        "returns the current local attribute payload for the tenant device",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns attribute set logs with count and list fields",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns record-not-found for invalid attribute deletion",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns command set logs for the tenant device",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns command data as an array for the tenant device",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns event data with count and list for the tenant device",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
    ],
  },
};
