const { metadataCase, e2eCase } = require("./helpers");

module.exports = {
  "tests/17_api_boundary_smoke.test.js": {
    file: "tests/17_api_boundary_smoke.test.js",
    type: "api",
    evidenceKind: "boundary",
    fileFlags: {},
    cases: [
      metadataCase(
        "serves the root health endpoint",
        "boundary",
        false,
        true,
        true,
        false,
        false,
      ),
      metadataCase(
        "serves prometheus metrics and the metrics viewer",
        "boundary",
        false,
        true,
        true,
        false,
        false,
      ),
      metadataCase(
        "routes swagger and static file requests through the configured wildcard handlers",
        "boundary",
        false,
        true,
        true,
        false,
        false,
      ),
      metadataCase(
        "exercises public websocket-style endpoints and OTA download validation edges",
        "boundary",
        false,
        true,
        true,
        false,
        true,
      ),
      metadataCase(
        "exposes setup-state probes without authentication",
        "boundary",
        false,
        true,
        true,
        false,
        false,
      ),
      metadataCase(
        "rejects incomplete public auth mutation payloads with validation errors",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "rejects incomplete plugin requests at the public plugin boundary",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "rejects incomplete public gateway registration payloads",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies casbin user list and mutation boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies OTA delete and update invalid-id boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies expected-data validation endpoints",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies message push config and session endpoints",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies dashboard-menu invalid id boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies openapi invalid update and delete boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies authenticated SSE and system-function update boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies selected device read, debug, and onboarding guide boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "only classifies selected device permission-sensitive list and metrics boundaries",
        "boundary",
        false,
        true,
        true,
        false,
        true,
      ),
      metadataCase(
        "only classifies device mutation and connect validation boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies telemetry, attribute, and command validation boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies device-config, UI-form, upload, and shared-RDI read boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies template, group, data-script, and alarm invalid-id boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
      metadataCase(
        "only classifies user transform and logout boundaries without poisoning later tests",
        "boundary",
        false,
        true,
        true,
        true,
        true,
      ),
    ],
  },
  "tests/02_device.test.js": {
    file: "tests/02_device.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "returns the current RDI thing model definition",
        "contract",
        false,
        true,
        true,
        false,
        false,
        ["rdi"],
      ),
      metadataCase(
        "returns the current tenant device list with pagination",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns the opt-in RDI installation summary without exposing private device metadata",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["device-telemetry", "permission-tenancy", "rdi"],
      ),
      metadataCase(
        "keeps tenant_user device list and selector scoped to owned devices",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "allows only super_admin to opt into the all-tenant RDI overview scope",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["device-telemetry", "permission-tenancy", "alarm-notification", "rdi"],
      ),
      metadataCase(
        "rejects tenant_user direct and batch actions on tenant-admin alarm history",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["permission-tenancy", "alarm-notification"],
      ),
      metadataCase(
        "rejects a PID that is too short",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "rejects a PID that is too long",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "rejects a PID with special characters",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "keeps the inactive PID activation case honest when the fixture is already consumed",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "rejects duplicate activation for an already activated PID",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "returns config, system info, and thing model for the activated device",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
      metadataCase(
        "returns device detail payload for the activated device",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry", "rdi"],
      ),
      metadataCase(
        "returns the current device online status payload",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry", "rdi"],
      ),
      metadataCase(
        "creates a share token and exposes the public share path",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
      metadataCase(
        "returns the public shared device payload for a valid token",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
      metadataCase(
        "allows tenant_admin_b to accept the shared device when that local account exists",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
      metadataCase(
        "marks repeated share acceptance as already accepted",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "allows a same-tenant tenant_user to accept and read but not manage a shared device",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["permission-tenancy", "rdi"],
      ),
      metadataCase(
        "rejects an invalid public share token with the current business error",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["rdi"],
      ),
      metadataCase(
        "returns the accepted shared device in the recipient tenant list",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
      metadataCase(
        "returns the current device group tree payload",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns the device selector payload",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns the current device group page",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "creates, details, and updates a device group cleanly",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "creates and lists a device-group relation for the activated device",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects duplicate device-group relations with the current uniqueness error",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "deletes a device-group relation and stays idempotent on a repeated delete",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns the current device template page",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "creates a device template and exposes it in the stats endpoint",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns the current device template menu and selector payloads",
        "boundary",
        false,
        true,
        true,
        false,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns the current database-not-found error for an invalid template id",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns the current device template chart payload for the activated device",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
    ],
  },
};
