const { metadataCase, e2eCase } = require("./helpers");

module.exports = {
  "tests/16_device_alarm_share.test.js": {
    file: "tests/16_device_alarm_share.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "updates an existing device name and verifies the detail response",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "accepts optional device metadata update fields for the existing fixture device",
        "contract",
        false,
        true,
        false,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects update without device id with validation code 100002",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects update for a missing UUID with database record-not-found code",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects overlong device name with max length validation",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects unauthenticated device update with HTTP 401 and nested 40100",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "deletes a disposable activated device when available, otherwise asserts consumed PID boundary",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects deleting a missing UUID with database record-not-found code",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects deleting an invalid id string with database record-not-found code",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects unauthenticated device delete with HTTP 401 and nested 40100",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "deletes a created alarm config and verifies it is absent from the list",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "rejects deleting a missing alarm config UUID with record-not-found code",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "rejects deleting an invalid alarm config id string with record-not-found code",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "rejects unauthenticated alarm config delete with HTTP 401 and nested 40100",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "rejects deleting the same alarm config twice with record-not-found code",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "creates a share token with token, share path, accept path, and future expiry",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
      metadataCase(
        "allows public unauthenticated access to a valid shared RDI device snapshot",
        "boundary",
        false,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
      metadataCase(
        "marks owner acceptance of its own share token as already accepted",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "allows recipient tenant to accept and then list the shared device when tenant_admin_b exists",
        "boundary",
        false,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
      metadataCase(
        "rejects public access with an invalid token using share-token business code 201001",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["rdi"],
      ),
      metadataCase(
        "rejects empty public share route with HTTP 404 route miss",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["rdi"],
      ),
      metadataCase(
        "rejects accepting an invalid token using share-token business code 201001",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["rdi"],
      ),
      metadataCase(
        "rejects unauthenticated accept of a valid share token with HTTP 401 and nested 40100",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "rejects creating a share token for a missing device with business code 100404",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "expires a short-lived share token and rejects public access after expiry",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["rdi"],
      ),
      metadataCase(
        "keeps multiple share tokens for the same device independently valid",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["rdi"],
      ),
    ],
  },
  "tests/17_api_coverage_closure.test.js": {
    file: "tests/17_api_coverage_closure.test.js",
    type: "api",
    evidenceKind: "boundary",
    fileFlags: {},
    cases: [
      metadataCase(
        "rejects model list requests without a device template id",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects incomplete model create and update payloads",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "rejects delete and custom command detail requests for non-existent model ids",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns service and access lists",
        "catalog",
        false,
        true,
        true,
        false,
        false,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "rejects incomplete service and service access mutations",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "returns scene and automation lists",
        "catalog",
        false,
        true,
        true,
        false,
        false,
        ["automation-scene"],
      ),
      metadataCase(
        "rejects incomplete scene mutations and invalid scene ids",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["automation-scene"],
      ),
      metadataCase(
        "rejects incomplete automation mutations and invalid automation ids",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["automation-scene"],
      ),
    ],
  },
  "tests/18_seeded_device_data.test.js": {
    file: "tests/18_seeded_device_data.test.js",
    type: "api",
    evidenceKind: "boundary",
    fileFlags: {},
    cases: [
      metadataCase(
        "creates or locates a deterministic device and validates device read surfaces",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "sets desired twin state and reads platform-visible convergence evidence",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "walks seeded device onboarding guide through access, readiness, diagnostics, and next-step evidence",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "asserts telemetry, attribute, event, and command failure branches with explicit product errors",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns paged device and model lists with stable shapes",
        "catalog",
        false,
        true,
        true,
        false,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "validates topic mapping list/create/update boundaries for MQTT pipeline setup",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
    ],
  },
  "tests/19_seeded_alarm_notification.test.js": {
    file: "tests/19_seeded_alarm_notification.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "validates alarm history acknowledgement and reset negative branches",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "reports per-row failures for alarm history batch-action boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "batch-acknowledges and batch-resets a seeded alarm history with detail readback",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
      metadataCase(
        "activates a seeded alarm scene and verifies acknowledge/reset history readback",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
      metadataCase(
        "asserts alarm list and device alarm config response shapes",
        "catalog",
        false,
        true,
        true,
        false,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "covers notification group and record list/read plus create validation boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["alarm-notification"],
      ),
      metadataCase(
        "uses seed helper for notification groups and verifies the created row",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["alarm-notification"],
      ),
    ],
  },
  "tests/20_seeded_system_permission.test.js": {
    file: "tests/20_seeded_system_permission.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "refreshes token and rejects protected endpoints without auth",
        "business",
        true,
        true,
        true,
        false,
        true,
        ["permission-tenancy"],
      ),
      metadataCase(
        "asserts user, role, and casbin list surfaces",
        "catalog",
        false,
        true,
        true,
        false,
        false,
        ["permission-tenancy"],
      ),
      metadataCase(
        "asserts role and casbin mutation validation failures",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["permission-tenancy"],
      ),
      metadataCase(
        "covers system identity, function flags, logo, and version read APIs",
        "boundary",
        false,
        true,
        false,
        true,
        true,
        ["permission-tenancy", "system-deployment"],
      ),
    ],
  },
};
