const { metadataCase, e2eCase } = require("./helpers");

module.exports = {
  "tests/25_seeded_command_jobs.test.js": {
    file: "tests/25_seeded_command_jobs.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {
      requiresSeededDevice: true,
      runtimeEvidenceRequired: true,
      commandJobLifecycle: true,
    },
    cases: [
      metadataCase(
        "rejects command job preview requests without an identify value",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["command-jobs"],
      ),
      metadataCase(
        "rejects unsupported command job scope types before previewing devices",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["command-jobs"],
      ),
      metadataCase(
        "previews a seeded selected-device command job without dispatching it",
        "contract",
        false,
        true,
        true,
        true,
        false,
        ["command-jobs"],
      ),
      metadataCase(
        "requires a preview token before submitting a command job",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["command-jobs"],
      ),
      metadataCase(
        "rejects stale command job preview tokens without persisting a job",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["command-jobs"],
      ),
      metadataCase(
        "returns a stable paged command job history shape",
        "contract",
        false,
        true,
        true,
        false,
        false,
        ["command-jobs"],
      ),
      metadataCase(
        "creates, lists, updates, and deletes an owned fleet saved filter",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["command-jobs"],
      ),
      metadataCase(
        "returns seeded command delivery diagnostics with operator next actions",
        "business",
        true,
        true,
        true,
        false,
        false,
        ["command-jobs"],
      ),
      metadataCase(
        "keeps invalid command job detail and support boundaries explicit",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["command-jobs"],
      ),
      metadataCase(
        "filters and searches command job rows with response evidence shape",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["command-jobs"],
      ),
      metadataCase(
        "previews, submits, refreshes, and packages a seeded command job",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["command-jobs"],
      ),
    ],
  },
  "tests/26_uncovered_endpoints.test.js": {
    file: "tests/26_uncovered_endpoints.test.js",
    type: "api",
    evidenceKind: "boundary",
    fileFlags: {
      requiresSeededDevice: true,
      runtimeEvidenceRequired: true,
    },
    cases: [
      metadataCase(
        "returns structured root and API deployment health reports",
        "boundary",
        false,
        false,
        true,
        false,
        false,
        ["system-deployment"],
      ),
      metadataCase(
        "rejects a password reset-link request without an email",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["permission-tenancy"],
      ),
      metadataCase(
        "keeps OTA governance preview record-not-found behavior explicit",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "returns a tenant-scoped twin drift index with stable counters",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry"],
      ),
      metadataCase(
        "reports the explicit runtime boundary for all MQTT debug session operations",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
      metadataCase(
        "returns device status history and a real topic-mapping dry-run result",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
      metadataCase(
        "rejects dashboard-menu batch requests without dashboard ids",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["visualization"],
      ),
      metadataCase(
        "returns telemetry detail/statistic contracts and stable dead-letter operator responses",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "returns uplink dead-letter list/drain and validates a missing status row",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry"],
      ),
      metadataCase(
        "keeps simulation-send and command-job-retry validation/record boundaries explicit",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["device-telemetry", "command-jobs"],
      ),
      metadataCase(
        "creates, validates, updates, lists, and deletes a payload schema through HTTP",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["command-jobs"],
      ),
      metadataCase(
        "returns a structured scene dry-run result without executing actions",
        "business",
        true,
        true,
        true,
        false,
        true,
        ["automation-scene"],
      ),
      metadataCase(
        "returns an empty RDI history page and explicit share-revocation not-found results",
        "boundary",
        false,
        true,
        true,
        false,
        true,
        ["rdi"],
      ),
    ],
  },
  "e2e/10_automation.spec.js": {
    file: "e2e/10_automation.spec.js",
    type: "e2e",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      {
        title: "scene manage search submits a seeded scene name",
        evidenceKind: "business",
        businessClosureEvidence: true,
        provesBusinessFlow: true,
        evidenceLayer: "browser-e2e-with-api-setup",
        hasBrowserUserFlow: true,
      },
      {
        title: "scene edit echoes a seeded scene and matches the detail API",
        evidenceKind: "business",
        businessClosureEvidence: true,
        provesBusinessFlow: true,
        evidenceLayer: "browser-e2e-with-api-setup",
        hasBrowserUserFlow: true,
        capabilityIds: ["automation-scene"],
      },
      {
        title: "scene linkage search finds a seeded automation and matches its detail API",
        evidenceKind: "business",
        businessClosureEvidence: true,
        provesBusinessFlow: true,
        evidenceLayer: "browser-e2e-with-api-setup",
        hasBrowserUserFlow: true,
        capabilityIds: ["automation-scene"],
      },
      e2eCase(
        "automation editor pre-validates, saves, and keeps the updated rule after refresh",
        "business",
        true,
        true,
        {
          capabilityIds: ["automation-scene"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
    ],
  },
  "e2e/14_route_coverage_closure.spec.js": {
    file: "e2e/14_route_coverage_closure.spec.js",
    type: "e2e",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      e2eCase(
        "tenant menu denies unregistered dashboard workspace routes",
        "boundary",
        false,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "seeded child-device detail route renders the selected device API state",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
          requiresSeededDevice: true,
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "personal-center renders the authenticated profile returned by the API",
        "business",
        true,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "seeded OpenAPI key appears in management/api and remains tenant-scoped",
        "business",
        true,
        true,
        {
          capabilityIds: ["ota-script-openapi-service"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "system log path filter sends an exact API query and renders the empty result",
        "business",
        true,
        true,
        {
          capabilityIds: ["system-deployment"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "super-admin menu denies routes without backend menu registration",
        "boundary",
        false,
        true,
        {
          capabilityIds: ["system-deployment"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "management/auth renders a menu element that is present in the API payload",
        "business",
        true,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
    ],
  },
};
