const { metadataCase, e2eCase } = require("./helpers");

module.exports = {
  "tests/21_seeded_ota_script_openapi.test.js": {
    file: "tests/21_seeded_ota_script_openapi.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "asserts OTA package and task read plus invalid-id boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "returns OTA task support archive with task-level rollout counts and conditional Ready Check handoff fields",
        "business",
        true,
        true,
        true,
        false,
        false,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "asserts data script list and mutation validation branches",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "uses seeded OpenAPI key helper and verifies the created key appears in list results",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["ota-script-openapi-service"],
      ),
      metadataCase(
        "asserts service plugin and access validation boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["ota-script-openapi-service"],
      ),
    ],
  },
  "tests/22_mqtt_device_pipeline.test.js": {
    file: "tests/22_mqtt_device_pipeline.test.js",
    type: "api",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      metadataCase(
        "validates device topic mapping list and mutation boundaries",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
      metadataCase(
        "validates backend publish/simulation API request shape for MQTT uplink and downlink",
        "business",
        true,
        true,
        true,
        true,
        true,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
      metadataCase(
        "publishes unique simulated telemetry and reads the same current value back",
        "business",
        true,
        true,
        true,
        true,
        false,
        ["mqtt-broker-pipeline"],
      ),
      metadataCase(
        "ties seeded device identity to connect info and debug endpoints",
        "boundary",
        false,
        true,
        true,
        true,
        true,
        ["device-telemetry", "mqtt-broker-pipeline"],
      ),
    ],
  },
  "e2e/01_login.spec.js": {
    file: "e2e/01_login.spec.js",
    type: "e2e",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      e2eCase(
        "anonymous language switch stays local and forgot password stays usable",
        "boundary",
        false,
        false,
      ),
      e2eCase(
        "password-login module route renders the real password form",
        "boundary",
        false,
        false,
      ),
      e2eCase(
        "phone-register module route renders validation and returns to password login",
        "boundary",
        false,
        false,
      ),
      e2eCase(
        "super admin login reaches the authenticated shell",
        "business",
        true,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "tenant admin login reaches the authenticated shell",
        "business",
        true,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "second tenant admin login reaches the authenticated shell",
        "business",
        true,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "tenant user login reaches the authenticated shell",
        "business",
        true,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "additional tenant user login reaches the authenticated shell",
        "business",
        true,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "email-change tenant login reaches the authenticated shell",
        "business",
        true,
        true,
        {
          capabilityIds: ["permission-tenancy"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "wrong password keeps the user on the login page",
        "boundary",
        false,
        false,
      ),
      e2eCase(
        "clearing auth state forces the next protected route back to login",
        "boundary",
        false,
        false,
      ),
      e2eCase(
        "visiting a protected route without a token redirects to login",
        "boundary",
        false,
        false,
      ),
    ],
  },
  "e2e/02_device.spec.js": {
    file: "e2e/02_device.spec.js",
    type: "e2e",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      e2eCase(
        "seeded device search matches API state and opens the selected device",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
          requiresSeededDevice: true,
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "manual add submits a real device and exposes it through list and detail APIs",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "created thing model is searchable in UI and matches API state",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
      e2eCase(
        "created device group is searchable in UI and opens matching details",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
      e2eCase(
        "tenant admin service access stays empty when API denies plugin management",
        "boundary",
        false,
        true,
        {
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
      e2eCase(
        "share page distinguishes valid, invalid, and empty token states",
        "business",
        true,
        true,
        {
          capabilityIds: ["rdi"],
          evidenceLayer: "browser-e2e-with-api-setup",
          requiresSeededDevice: true,
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "Ready Check shows uniquely published MQTT telemetry evidence",
        "business",
        true,
        true,
        {
          evidenceLayer: "browser-e2e-with-api-setup",
          capabilityIds: ["mqtt-broker-pipeline"],
          requiresSeededDevice: true,
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "share link acceptance closes the loop when a recipient tenant is available",
        "business",
        true,
        true,
        {
          capabilityIds: ["rdi"],
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
    ],
  },
  "e2e/03_data.spec.js": {
    file: "e2e/03_data.spec.js",
    type: "e2e",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      e2eCase(
        "new device telemetry tab renders the same empty snapshot returned by the API",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "device twin tab downloads platform-visible evidence bundle for a seeded desired state",
        "business",
        true,
        true,
        {
          evidenceLayer: "browser-e2e-with-api-setup",
          capabilityIds: ["device-telemetry"],
        },
      ),
      e2eCase(
        "first-device Ready Check downloads diagnostics bundle with connection-guide evidence",
        "business",
        true,
        true,
        {
          evidenceLayer: "browser-e2e-with-api-setup",
          capabilityIds: ["device-telemetry"],
          firstDeviceOnboarding: true,
          readyCheckDiagnosticsBundle: true,
          requiresSeededDevice: true,
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "seeded device config detail renders its API identity and loads data processing for that config",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
      e2eCase(
        "seeded thing model is searchable in the UI and matches list and detail APIs",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
      e2eCase(
        "share link shows owner success and revoked-token error states backed by the API",
        "business",
        true,
        true,
        {
          evidenceLayer: "browser-e2e-with-api-setup",
          capabilityIds: ["rdi"],
          requiresSeededDevice: true,
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "tenant RDI alarm overview matches its tenant-scoped API responses without requesting all tenants",
        "boundary",
        false,
        false,
        {
          capabilityIds: ["rdi"],
          evidenceLayer: "browser-e2e",
          runtimeEvidenceRequired: true,
        },
      ),
    ],
  },
  "e2e/04_alarm.spec.js": {
    file: "e2e/04_alarm.spec.js",
    type: "e2e",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      e2eCase(
        "user search refresh keeps the seeded alarm aligned with the history API response",
        "business",
        true,
        true,
        {
          capabilityIds: ["alarm-notification"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "alarm level filter sends H to the history API and keeps the seeded high alarm visible",
        "business",
        true,
        true,
        {
          capabilityIds: ["alarm-notification"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "alert center downloads current page closure evidence JSON bundle",
        "business",
        true,
        true,
        {
          capabilityIds: ["alarm-notification"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "seeded alarm scene is visible in downloaded closure evidence bundle",
        "business",
        true,
        true,
        {
          capabilityIds: ["alarm-notification"],
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
      e2eCase(
        "browser acknowledge/reset actions persist and appear in downloaded closure evidence",
        "business",
        true,
        true,
        {
          capabilityIds: ["alarm-notification"],
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
      e2eCase(
        "notification recipient filter sends an exact negative query and renders the empty result",
        "boundary",
        false,
        false,
        {
          capabilityIds: ["alarm-notification"],
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "notification reset clears the recipient filter and reloads the unfiltered API query",
        "contract",
        false,
        false,
        {
          capabilityIds: ["alarm-notification"],
          runtimeEvidenceRequired: true,
        },
      ),
      e2eCase(
        "seeded notification group is visible from the notification group page",
        "business",
        true,
        true,
        {
          capabilityIds: ["alarm-notification"],
          evidenceLayer: "browser-e2e-with-api-setup",
        },
      ),
    ],
  },
  "e2e/06_system.spec.js": {
    file: "e2e/06_system.spec.js",
    type: "e2e",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      e2eCase(
        "data cleanup policy edited in the browser persists through the API and refreshed table",
        "business",
        true,
        true,
        {
          evidenceLayer: "browser-e2e-with-api-setup",
          capabilityIds: ["system-deployment"],
          runtimeEvidenceRequired: true,
        },
      ),
    ],
  },
  "e2e/05_config.spec.js": {
    file: "e2e/05_config.spec.js",
    type: "e2e",
    evidenceKind: "business",
    fileFlags: {},
    cases: [
      e2eCase(
        "seeded device config detail can be renamed through the browser and read back from the API",
        "business",
        true,
        true,
        {
          capabilityIds: ["device-telemetry"],
          evidenceLayer: "browser-e2e-with-api-setup",
          runtimeEvidenceRequired: true,
        },
      ),
    ],
  },
};
