// wave7cgen 从 service 包提取指定域类型的方法集，生成 Wave7-C 域接口文件。
// 用法：go run ./cmd/wave7cgen -types "Dict,Role,UiElements,OTA,Casbin" -out internal/service/wave7c_domains_gen.go
// 生成内容：每个类型一个 XxxDomain 接口（全部导出方法）+ 编译期断言。
// 指针接收者方法集用 (*T)(nil) 断言；纯值接收者用 T{} 断言。
package main

import (
	"flag"
	"fmt"
	"go/ast"
	"go/format"
	"go/parser"
	"go/token"
	"os"
	"path/filepath"
	"sort"
	"strings"
)

type methodSig struct {
	name       string
	params     string
	results    string
	pointerRecv bool
}

func main() {
	typesFlag := flag.String("types", "", "comma-separated service type names")
	out := flag.String("out", "", "output file path")
	flag.Parse()
	if *typesFlag == "" || *out == "" {
		fmt.Fprintln(os.Stderr, "-types and -out are required")
		os.Exit(1)
	}
	want := map[string]bool{}
	for _, t := range strings.Split(*typesFlag, ",") {
		want[strings.TrimSpace(t)] = true
	}

	fset := token.NewFileSet()
	pkg, err := parser.ParseDir(fset, "internal/service", func(fi os.FileInfo) bool {
		return !strings.HasSuffix(fi.Name(), "_test.go")
	}, 0)
	if err != nil {
		fmt.Fprintln(os.Stderr, "parse:", err)
		os.Exit(1)
	}

	sigs := map[string][]methodSig{}
	for _, files := range pkg {
		for _, file := range files.Files {
			for _, decl := range file.Decls {
				fd, ok := decl.(*ast.FuncDecl)
				if !ok || fd.Recv == nil || !ast.IsExported(fd.Name.Name) {
					continue
				}
				recvType := recvTypeName(fd.Recv)
				if !want[recvType] {
					continue
				}
				sigs[recvType] = append(sigs[recvType], methodSig{
					name:        fd.Name.Name,
					params:      exprsSource(fset, fd.Type.Params),
					results:     exprsSource(fset, fd.Type.Results),
					pointerRecv: recvIsPointer(fd.Recv),
				})
			}
		}
	}

	names := make([]string, 0, len(sigs))
	for n := range sigs {
		names = append(names, n)
	}
	sort.Strings(names)

	var b strings.Builder
	b.WriteString("// Code generated by cmd/wave7cgen; DO NOT EDIT.\n")
	b.WriteString("// Wave7-C（GroupApp → 构造注入）域接口：方法签名从实现逐字提取。\n\n")
	b.WriteString("package service\n\n")
	b.WriteString("import (\n")
	for _, imp := range collectImports(pkg, names, sigs) {
		b.WriteString("\t" + imp + "\n")
	}
	b.WriteString(")\n\n")

	for _, t := range names {
		ms := sigs[t]
		sort.Slice(ms, func(i, j int) bool { return ms[i].name < ms[j].name })
		iface := strings.TrimSuffix(t, "Service") + "Domain"
		b.WriteString("// " + iface + " 是 " + t + " 对 api 层暴露的能力集合。\n")
		b.WriteString("type " + iface + " interface {\n")
		for _, m := range ms {
			b.WriteString("\t" + m.name + "(" + m.params + ") " + m.results + "\n")
		}
		b.WriteString("}\n\n")
		anyPointer := false
		for _, m := range ms {
			if m.pointerRecv {
				anyPointer = true
			}
		}
		if anyPointer {
			b.WriteString("var _ " + iface + " = (*" + t + ")(nil)\n\n")
		} else {
			b.WriteString("var _ " + iface + " = " + t + "{}\n\n")
		}
	}

	formatted, err := format.Source([]byte(b.String()))
	if err != nil {
		_ = os.WriteFile(*out+".unformatted", []byte(b.String()), 0o644)
		fmt.Fprintln(os.Stderr, "format:", err, "(raw written to "+*out+".unformatted)")
		os.Exit(1)
	}
	if err := os.MkdirAll(filepath.Dir(*out), 0o755); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	if err := os.WriteFile(*out, formatted, 0o644); err != nil {
		fmt.Fprintln(os.Stderr, err)
		os.Exit(1)
	}
	fmt.Println("wrote", *out)
}

func recvTypeName(recv *ast.FieldList) string {
	if len(recv.List) == 0 {
		return ""
	}
	switch e := recv.List[0].Type.(type) {
	case *ast.Ident:
		return e.Name
	case *ast.StarExpr:
		if id, ok := e.X.(*ast.Ident); ok {
			return id.Name
		}
	}
	return ""
}

func recvIsPointer(recv *ast.FieldList) bool {
	if len(recv.List) == 0 {
		return false
	}
	_, ok := recv.List[0].Type.(*ast.StarExpr)
	return ok
}

// exprsSource 还原参数/返回值源码片段（保留命名与类型），多值用逗号连接。
func exprsSource(fset *token.FileSet, fl *ast.FieldList) string {
	if fl == nil {
		return ""
	}
	parts := make([]string, 0, len(fl.List))
	for _, field := range fl.List {
		src := sourceOf(fset, field.Type)
		if len(field.Names) > 0 {
			names := make([]string, 0, len(field.Names))
			for _, n := range field.Names {
				names = append(names, n.Name)
			}
			parts = append(parts, strings.Join(names, ", ")+" "+src)
		} else {
			parts = append(parts, src)
		}
	}
	joined := strings.Join(parts, ", ")
	if joined == "" {
		return ""
	}
	return "(" + joined + ")"
}

func sourceOf(fset *token.FileSet, e ast.Expr) string {
	start := fset.Position(e.Pos())
	end := fset.Position(e.End())
	if start.Filename != end.Filename {
		return ""
	}
	data, err := os.ReadFile(start.Filename)
	if err != nil {
		return ""
	}
	if start.Offset < 0 || end.Offset > len(data) || start.Offset >= end.Offset {
		return ""
	}
	return strings.TrimSpace(string(data[start.Offset:end.Offset]))
}

func collectImports(pkg map[string]*ast.Package, names []string, sigs map[string][]methodSig) []string {
	// 生成文件的 import 集合 = 各方法签名里出现的限定标识符（model./utils./context. 等）。
	used := map[string]bool{}
	for _, t := range names {
		for _, m := range sigs[t] {
			for _, piece := range []string{m.params, m.results} {
				for _, q := range strings.Split(piece, " ") {
					if i := strings.Index(q, "."); i > 0 && q[:i] != "" {
						used[q[:i]] = true
					}
				}
			}
		}
	}
	pathByPkg := map[string]string{}
	for _, files := range pkg {
		for _, file := range files.Files {
			for _, imp := range file.Imports {
				path := strings.Trim(imp.Path.Value, `"`)
				alias := ""
				if imp.Name != nil {
					alias = imp.Name.Name
				} else {
					segs := strings.Split(path, "/")
					alias = segs[len(segs)-1]
				}
				pathByPkg[alias] = path
			}
		}
	}
	out := make([]string, 0, len(used))
	for alias := range used {
		if p, ok := pathByPkg[alias]; ok {
			if alias == p[len(p)-len(alias):] && !strings.Contains(p[len(p)-len(alias)-1:], "/") {
				out = append(out, `"`+p+`"`)
			} else {
				out = append(out, alias+" \""+p+"\"")
			}
		}
	}
	sort.Strings(out)
	return out
}
