//go:build ignore
// +build ignore

// 文件用途：维护 broker 插件导入文件的生成器脚本。
// 核心逻辑：读取 plugin_imports.yml 后渲染 cmd/gmqttd/plugins.go 的空白导入列表。
// 关键注意事项：该文件本身是手写生成器，修改会影响生成产物但不应直接改生成结果逻辑。
// 重构建议：后续可把插件清单校验和生成命令纳入 CI，避免导入列表漂移。

package main

import (
	"bytes"
	"go/format"
	"log"
	"os"
	"strings"
	"text/template"

	"gopkg.in/yaml.v2"
)

var tmpl = `//go:generate sh -c "cd ../../ && go run plugin_generate.go"
// generated by plugin_generate.go; DO NOT EDIT

package main

import (
    {{- range $index, $element := .}}
    _ "{{$element}}"
    {{- end}}
)
`

const (
	pluginFile = "./cmd/gmqttd/plugins.go"
	pluginCfg  = "plugin_imports.yml"
	importPath = "github.com/DrmagicE/gmqtt/plugin"
)

type ymlCfg struct {
	Packages []string `yaml:"packages"`
}

// main 读取 plugin_imports.yml，将插件包名拼接为完整导入路径，
// 渲染模板并格式化后写入 cmd/gmqttd/plugins.go。
func main() {
	b, err := os.ReadFile(pluginCfg)
	if err != nil {
		log.Fatalf("ReadFile error %s", err)
	}

	var cfg ymlCfg
	err = yaml.Unmarshal(b, &cfg)
	if err != nil {
		log.Fatalf("Unmarshal error: %s", err)
	}
	t, err := template.New("plugin_gen").Parse(tmpl)
	if err != nil {
		log.Fatalf("Parse template error: %s", err)
	}

	for k, v := range cfg.Packages {
		if !strings.Contains(v, "/") {
			cfg.Packages[k] = importPath + "/" + v
		}
	}

	buf := &bytes.Buffer{}
	err = t.Execute(buf, cfg.Packages)
	if err != nil {
		log.Fatalf("excute template error: %s", err)
	}
	rs, err := format.Source(buf.Bytes())
	if err != nil {
		log.Fatalf("format error: %s", err)
	}
	err = os.WriteFile(pluginFile, rs, 0666)
	if err != nil {
		log.Fatalf("writeFile error: %s", err)
	}
}
