// 自动生成：核心图标清单与分组加载器（请勿手工编辑，源：icons-registry-core-buckets/）
import type { Component } from 'vue'

export const coreIconNames = [
  'Accessibility',
  'AccessibilityOutline',
  'Add',
  'AddCircle',
  'AddCircleOutline',
  'AddOutline',
  'AirplaneOutline',
  'AlarmOutline',
  'AlbumsOutline',
  'AlertCircle',
  'AlertCircleOutline',
  'AlertOutline',
  'AmericanFootballOutline',
  'AppsOutline',
  'Archive',
  'ArchiveOutline',
  'ArrowBack',
  'ArrowBackCircle',
  'ArrowBackCircleOutline',
  'ArrowBackOutline',
  'ArrowDown',
  'ArrowDownCircle',
  'ArrowDownCircleOutline',
  'ArrowDownOutline',
  'ArrowForward',
  'ArrowForwardCircle',
  'ArrowForwardCircleOutline',
  'ArrowForwardOutline',
  'ArrowUp',
  'ArrowUpCircle',
  'ArrowUpCircleOutline',
  'ArrowUpOutline',
  'At',
  'AtOutline',
  'Attach',
  'AttachOutline',
  'BagAdd',
  'BagAddOutline',
  'BagCheck',
  'BagCheckOutline',
  'BagHandle',
  'BagHandleOutline',
  'BagRemove',
  'BagRemoveOutline',
  'Balloon',
  'BalloonOutline',
  'Bandage',
  'BandageOutline',
  'Beaker',
  'BeakerOutline',
  'Bed',
  'BedOutline',
  'Beer',
  'BeerOutline',
  'Bicycle',
  'BicycleOutline',
  'Boat',
  'BoatOutline',
  'Body',
  'BodyOutline',
  'Bonfire',
  'BonfireOutline',
  'BookmarkOutline',
  'Bookmarks',
  'BookmarksOutline',
  'Briefcase',
  'BriefcaseOutline',
  'Browsers',
  'BrowsersOutline',
  'Bug',
  'BugOutline',
  'Build',
  'BuildOutline',
  'Bus',
  'BusOutline',
  'Business',
  'BusinessOutline',
  'Cafe',
  'CafeOutline',
  'Calculator',
  'CalculatorOutline',
  'Calendar',
  'CalendarClear',
  'CalendarClearOutline',
  'CalendarNumber',
  'CalendarNumberOutline',
  'CalendarOutline',
  'Call',
  'CallOutline',
  'Car',
  'CarOutline',
  'CarSport',
  'CarSportOutline',
  'CaretBack',
  'CaretBackCircle',
  'CaretBackCircleOutline',
  'CaretBackOutline',
  'CaretDown',
  'CaretDownCircle',
  'CaretDownCircleOutline',
  'CaretDownOutline',
  'CaretForward',
  'CaretForwardCircle',
  'CaretForwardCircleOutline',
  'CaretForwardOutline',
  'CaretUp',
  'CaretUpCircle',
  'CaretUpCircleOutline',
  'CaretUpOutline',
  'Cart',
  'CartOutline',
  'CashOutline',
  'Chatbox',
  'ChatboxEllipses',
  'ChatboxEllipsesOutline',
  'ChatboxOutline',
  'Chatbubbles',
  'ChatbubblesOutline',
  'Checkbox',
  'CheckboxOutline',
  'Checkmark',
  'CheckmarkCircle',
  'CheckmarkCircleOutline',
  'CheckmarkDone',
  'CheckmarkDoneCircle',
  'CheckmarkDoneCircleOutline',
  'CheckmarkDoneOutline',
  'CheckmarkOutline',
  'ChevronBack',
  'ChevronBackCircle',
  'ChevronBackCircleOutline',
  'ChevronBackOutline',
  'ChevronDown',
  'ChevronDownCircle',
  'ChevronDownCircleOutline',
  'ChevronDownOutline',
  'ChevronForward',
  'ChevronForwardCircle',
  'ChevronForwardCircleOutline',
  'ChevronForwardOutline',
  'ChevronUp',
  'ChevronUpCircle',
  'ChevronUpCircleOutline',
  'ChevronUpOutline',
  'Clipboard',
  'ClipboardOutline',
  'Close',
  'CloseCircle',
  'CloseCircleOutline',
  'CloseOutline',
  'Code',
  'CodeDownload',
  'CodeDownloadOutline',
  'CodeOutline',
  'CodeSlash',
  'CodeSlashOutline',
  'CodeWorking',
  'CodeWorkingOutline',
  'Cog',
  'CogOutline',
  'Compass',
  'CompassOutline',
  'Construct',
  'ConstructOutline',
  'Contract',
  'ContractOutline',
  'Copy',
  'CopyOutline',
  'Create',
  'CreateOutline',
  'CropOutline',
  'Cube',
  'CubeOutline',
  'Cut',
  'CutOutline',
  'Dice',
  'DiceOutline',
  'Disc',
  'DiscOutline',
  'Document',
  'DocumentAttach',
  'DocumentAttachOutline',
  'DocumentLock',
  'DocumentLockOutline',
  'DocumentOutline',
  'DocumentText',
  'DocumentTextOutline',
  'Download',
  'DownloadOutline',
  'Duplicate',
  'DuplicateOutline',
  'Ear',
  'EarOutline',
  'Earth',
  'EarthOutline',
  'Egg',
  'EggOutline',
  'ExtensionPuzzle',
  'ExtensionPuzzleOutline',
  'Eye',
  'EyeOff',
  'EyeOffOutline',
  'EyeOutline',
  'Eyedrop',
  'EyedropOutline',
  'Female',
  'FemaleOutline',
  'FileTray',
  'FileTrayFull',
  'FileTrayFullOutline',
  'FileTrayOutline',
  'Film',
  'FilmOutline',
  'FingerPrintOutline',
  'Fitness',
  'FitnessOutline',
  'Flag',
  'FlagOutline',
  'Flame',
  'FlameOutline',
  'Flask',
  'FlaskOutline',
  'Folder',
  'FolderOutline',
  'Football',
  'FootballOutline',
  'Gift',
  'GiftOutline',
  'GitBranch',
  'GitBranchOutline',
  'GitCommit',
  'GitCommitOutline',
  'GitCompare',
  'GitCompareOutline',
  'GitMerge',
  'GitMergeOutline',
  'GitNetwork',
  'GitNetworkOutline',
  'GitPullRequest',
  'GitPullRequestOutline',
  'Glasses',
  'GlassesOutline',
  'Globe',
  'GlobeOutline',
  'Golf',
  'GolfOutline',
  'Hammer',
  'HammerOutline',
  'HandLeftOutline',
  'HandLeftSharp',
  'HandRightOutline',
  'HandRightSharp',
  'Happy',
  'HappyOutline',
  'Headset',
  'HeadsetOutline',
  'Heart',
  'HeartCircle',
  'HeartCircleOutline',
  'HeartDislike',
  'HeartDislikeOutline',
  'HeartHalf',
  'HeartHalfOutline',
  'HeartOutline',
  'Help',
  'HelpBuoy',
  'HelpBuoyOutline',
  'HelpCircle',
  'HelpCircleOutline',
  'HelpOutline',
  'Home',
  'HomeOutline',
  'Hourglass',
  'HourglassOutline',
  'IceCream',
  'IceCreamOutline',
  'IdCard',
  'IdCardOutline',
  'Image',
  'ImageOutline',
  'Images',
  'ImagesOutline',
  'InformationCircle',
  'InformationCircleOutline',
  'InformationOutline',
  'Key',
  'KeyOutline',
  'Keypad',
  'KeypadOutline',
  'Language',
  'LanguageOutline',
  'Leaf',
  'LeafOutline',
  'Library',
  'LibraryOutline',
  'Link',
  'LinkOutline',
  'List',
  'ListCircle',
  'ListCircleOutline',
  'ListOutline',
  'Location',
  'LocationOutline',
  'LockClosed',
  'LockClosedOutline',
  'LockOpen',
  'LockOpenOutline',
  'LogoAndroid',
  'LogoAngular',
  'LogoApple',
  'LogoBitbucket',
  'LogoBitcoin',
  'LogoBuffer',
  'LogoCapacitor',
  'LogoChrome',
  'LogoCss3',
  'LogoDribbble',
  'LogoDropbox',
  'LogoEdge',
  'LogoElectron',
  'LogoEuro',
  'LogoFacebook',
  'LogoFlickr',
  'LogoFoursquare',
  'LogoGithub',
  'LogoGoogle',
  'LogoGooglePlaystore',
  'LogoHtml5',
  'LogoInstagram',
  'LogoIonic',
  'LogoIonitron',
  'LogoJavascript',
  'LogoLinkedin',
  'LogoNodejs',
  'LogoPinterest',
  'LogoPwa',
  'LogoPython',
  'LogoReddit',
  'LogoRss',
  'LogoSass',
  'LogoSkype',
  'LogoSlack',
  'LogoSnapchat',
  'LogoStackoverflow',
  'LogoSteam',
  'LogoTiktok',
  'LogoTumblr',
  'LogoTux',
  'LogoTwitch',
  'LogoTwitter',
  'LogoUsd',
  'LogoVenmo',
  'LogoVercel',
  'LogoVimeo',
  'LogoVue',
  'LogoWebComponent',
  'LogoWechat',
  'LogoWhatsapp',
  'LogoWindows',
  'LogoWordpress',
  'LogoXbox',
  'LogoXing',
  'LogoYahoo',
  'LogoYen',
  'LogoYoutube',
  'Magnet',
  'MagnetOutline',
  'Mail',
  'MailOpen',
  'MailOpenOutline',
  'MailOutline',
  'MailUnread',
  'MailUnreadOutline',
  'Male',
  'MaleOutline',
  'Man',
  'ManOutline',
  'Map',
  'MapOutline',
  'Menu',
  'MenuOutline',
  'Moon',
  'MoonOutline',
  'MusicalNote',
  'MusicalNoteOutline',
  'Nuclear',
  'NuclearOutline',
  'Nutrition',
  'NutritionOutline',
  'Open',
  'OpenOutline',
  'Options',
  'OptionsOutline',
  'PaperPlane',
  'PaperPlaneOutline',
  'PartlySunny',
  'PartlySunnyOutline',
  'Pause',
  'PauseCircle',
  'PauseCircleOutline',
  'PauseOutline',
  'Paw',
  'PawOutline',
  'Pencil',
  'PencilOutline',
  'People',
  'PeopleCircle',
  'PeopleCircleOutline',
  'PeopleOutline',
  'Person',
  'PersonAdd',
  'PersonAddOutline',
  'PersonCircle',
  'PersonCircleOutline',
  'PersonOutline',
  'Pin',
  'PinOutline',
  'Pint',
  'PintOutline',
  'Pizza',
  'PizzaOutline',
  'Planet',
  'PlanetOutline',
  'Play',
  'PlayBackCircle',
  'PlayBackCircleOutline',
  'PlayBackOutline',
  'PlayCircle',
  'PlayCircleOutline',
  'PlayForward',
  'PlayForwardCircle',
  'PlayForwardCircleOutline',
  'PlayForwardOutline',
  'PlayOutline',
  'PlaySkipBack',
  'PlaySkipBackCircle',
  'PlaySkipBackCircleOutline',
  'PlaySkipBackOutline',
  'PlaySkipForward',
  'PlaySkipForwardCircle',
  'PlaySkipForwardCircleOutline',
  'PlaySkipForwardOutline',
  'Pricetag',
  'PricetagOutline',
  'Pricetags',
  'PricetagsOutline',
  'Print',
  'PrintOutline',
  'Push',
  'PushOutline',
  'Rainy',
  'RainyOutline',
  'Reader',
  'ReaderOutline',
  'Receipt',
  'ReceiptOutline',
  'Refresh',
  'RefreshCircle',
  'RefreshCircleOutline',
  'RefreshOutline',
  'Reload',
  'ReloadCircle',
  'ReloadCircleOutline',
  'ReloadOutline',
  'Remove',
  'RemoveCircle',
  'RemoveCircleOutline',
  'RemoveOutline',
  'ReorderThree',
  'ReorderThreeOutline',
  'ReorderTwo',
  'ReorderTwoOutline',
  'Repeat',
  'RepeatOutline',
  'Restaurant',
  'RestaurantOutline',
  'ReturnDownBack',
  'ReturnDownBackOutline',
  'ReturnDownForward',
  'ReturnDownForwardOutline',
  'ReturnUpBack',
  'ReturnUpBackOutline',
  'ReturnUpForward',
  'ReturnUpForwardOutline',
  'Ribbon',
  'RibbonOutline',
  'Rocket',
  'RocketOutline',
  'Rose',
  'RoseOutline',
  'Sad',
  'SadOutline',
  'Save',
  'SaveOutline',
  'School',
  'SchoolOutline',
  'Search',
  'SearchCircle',
  'SearchCircleOutline',
  'SearchOutline',
  'Send',
  'SendOutline',
  'Settings',
  'SettingsOutline',
  'Share',
  'ShareOutline',
  'ShareSocial',
  'ShareSocialOutline',
  'ShieldCheckmark',
  'ShieldCheckmarkOutline',
  'ShieldOutline',
  'ShieldSharp',
  'Shirt',
  'ShirtOutline',
  'Shuffle',
  'ShuffleOutline',
  'Skull',
  'SkullOutline',
  'Snow',
  'SnowOutline',
  'Sparkles',
  'SparklesOutline',
  'Speedometer',
  'SpeedometerOutline',
  'Star',
  'StarHalf',
  'StarHalfOutline',
  'StarOutline',
  'Stop',
  'StopCircle',
  'StopCircleOutline',
  'StopOutline',
  'Storefront',
  'StorefrontOutline',
  'Subway',
  'SubwayOutline',
  'Sunny',
  'SunnyOutline',
  'SwapHorizontal',
  'SwapHorizontalOutline',
  'SwapVertical',
  'SwapVerticalOutline',
  'SwapVerticalSharp',
  'Sync',
  'SyncCircle',
  'SyncCircleOutline',
  'SyncOutline',
  'Tennisball',
  'TennisballOutline',
  'ThumbsDown',
  'ThumbsDownOutline',
  'ThumbsUp',
  'ThumbsUpOutline',
  'Thunderstorm',
  'ThunderstormOutline',
  'Ticket',
  'TicketOutline',
  'Time',
  'TimeOutline',
  'TimeSharp',
  'Timer',
  'TimerOutline',
  'Train',
  'TrainOutline',
  'Transgender',
  'TransgenderOutline',
  'Trash',
  'TrashBin',
  'TrashBinOutline',
  'TrashOutline',
  'TrendingDown',
  'TrendingDownOutline',
  'TrendingUp',
  'TrendingUpOutline',
  'Trophy',
  'TrophyOutline',
  'Umbrella',
  'UmbrellaOutline',
  'Unlink',
  'UnlinkOutline',
  'Walk',
  'WalkOutline',
  'Wallet',
  'WalletOutline',
  'Warning',
  'WarningOutline',
  'Water',
  'WaterOutline',
  'Wine',
  'WineOutline',
  'Woman',
  'WomanOutline'
] as const

export const coreIconBucketOf: Record<string, string> = {
  Accessibility: 'A',
  AccessibilityOutline: 'A',
  Add: 'A',
  AddCircle: 'A',
  AddCircleOutline: 'A',
  AddOutline: 'A',
  AirplaneOutline: 'A',
  AlarmOutline: 'A',
  AlbumsOutline: 'A',
  AlertCircle: 'A',
  AlertCircleOutline: 'A',
  AlertOutline: 'A',
  AmericanFootballOutline: 'A',
  AppsOutline: 'A',
  Archive: 'A',
  ArchiveOutline: 'A',
  ArrowBack: 'A',
  ArrowBackCircle: 'A',
  ArrowBackCircleOutline: 'A',
  ArrowBackOutline: 'A',
  ArrowDown: 'A',
  ArrowDownCircle: 'A',
  ArrowDownCircleOutline: 'A',
  ArrowDownOutline: 'A',
  ArrowForward: 'A',
  ArrowForwardCircle: 'A',
  ArrowForwardCircleOutline: 'A',
  ArrowForwardOutline: 'A',
  ArrowUp: 'A',
  ArrowUpCircle: 'A',
  ArrowUpCircleOutline: 'A',
  ArrowUpOutline: 'A',
  At: 'A',
  AtOutline: 'A',
  Attach: 'A',
  AttachOutline: 'A',
  BagAdd: 'B',
  BagAddOutline: 'B',
  BagCheck: 'B',
  BagCheckOutline: 'B',
  BagHandle: 'B',
  BagHandleOutline: 'B',
  BagRemove: 'B',
  BagRemoveOutline: 'B',
  Balloon: 'B',
  BalloonOutline: 'B',
  Bandage: 'B',
  BandageOutline: 'B',
  Beaker: 'B',
  BeakerOutline: 'B',
  Bed: 'B',
  BedOutline: 'B',
  Beer: 'B',
  BeerOutline: 'B',
  Bicycle: 'B',
  BicycleOutline: 'B',
  Boat: 'B',
  BoatOutline: 'B',
  Body: 'B',
  BodyOutline: 'B',
  Bonfire: 'B',
  BonfireOutline: 'B',
  BookmarkOutline: 'B',
  Bookmarks: 'B',
  BookmarksOutline: 'B',
  Briefcase: 'B',
  BriefcaseOutline: 'B',
  Browsers: 'B',
  BrowsersOutline: 'B',
  Bug: 'B',
  BugOutline: 'B',
  Build: 'B',
  BuildOutline: 'B',
  Bus: 'B',
  BusOutline: 'B',
  Business: 'B',
  BusinessOutline: 'B',
  Cafe: 'C',
  CafeOutline: 'C',
  Calculator: 'C',
  CalculatorOutline: 'C',
  Calendar: 'C',
  CalendarClear: 'C',
  CalendarClearOutline: 'C',
  CalendarNumber: 'C',
  CalendarNumberOutline: 'C',
  CalendarOutline: 'C',
  Call: 'C',
  CallOutline: 'C',
  Car: 'C',
  CarOutline: 'C',
  CarSport: 'C',
  CarSportOutline: 'C',
  CaretBack: 'C',
  CaretBackCircle: 'C',
  CaretBackCircleOutline: 'C',
  CaretBackOutline: 'C',
  CaretDown: 'C',
  CaretDownCircle: 'C',
  CaretDownCircleOutline: 'C',
  CaretDownOutline: 'C',
  CaretForward: 'C',
  CaretForwardCircle: 'C',
  CaretForwardCircleOutline: 'C',
  CaretForwardOutline: 'C',
  CaretUp: 'C',
  CaretUpCircle: 'C',
  CaretUpCircleOutline: 'C',
  CaretUpOutline: 'C',
  Cart: 'C',
  CartOutline: 'C',
  CashOutline: 'C',
  Chatbox: 'C',
  ChatboxEllipses: 'C',
  ChatboxEllipsesOutline: 'C',
  ChatboxOutline: 'C',
  Chatbubbles: 'C',
  ChatbubblesOutline: 'C',
  Checkbox: 'C',
  CheckboxOutline: 'C',
  Checkmark: 'C',
  CheckmarkCircle: 'C',
  CheckmarkCircleOutline: 'C',
  CheckmarkDone: 'C',
  CheckmarkDoneCircle: 'C',
  CheckmarkDoneCircleOutline: 'C',
  CheckmarkDoneOutline: 'C',
  CheckmarkOutline: 'C',
  ChevronBack: 'C',
  ChevronBackCircle: 'C',
  ChevronBackCircleOutline: 'C',
  ChevronBackOutline: 'C',
  ChevronDown: 'C',
  ChevronDownCircle: 'C',
  ChevronDownCircleOutline: 'C',
  ChevronDownOutline: 'C',
  ChevronForward: 'C',
  ChevronForwardCircle: 'C',
  ChevronForwardCircleOutline: 'C',
  ChevronForwardOutline: 'C',
  ChevronUp: 'C',
  ChevronUpCircle: 'C',
  ChevronUpCircleOutline: 'C',
  ChevronUpOutline: 'C',
  Clipboard: 'C',
  ClipboardOutline: 'C',
  Close: 'C',
  CloseCircle: 'C',
  CloseCircleOutline: 'C',
  CloseOutline: 'C',
  Code: 'C',
  CodeDownload: 'C',
  CodeDownloadOutline: 'C',
  CodeOutline: 'C',
  CodeSlash: 'C',
  CodeSlashOutline: 'C',
  CodeWorking: 'C',
  CodeWorkingOutline: 'C',
  Cog: 'C',
  CogOutline: 'C',
  Compass: 'C',
  CompassOutline: 'C',
  Construct: 'C',
  ConstructOutline: 'C',
  Contract: 'C',
  ContractOutline: 'C',
  Copy: 'C',
  CopyOutline: 'C',
  Create: 'C',
  CreateOutline: 'C',
  CropOutline: 'C',
  Cube: 'C',
  CubeOutline: 'C',
  Cut: 'C',
  CutOutline: 'C',
  Dice: 'D',
  DiceOutline: 'D',
  Disc: 'D',
  DiscOutline: 'D',
  Document: 'D',
  DocumentAttach: 'D',
  DocumentAttachOutline: 'D',
  DocumentLock: 'D',
  DocumentLockOutline: 'D',
  DocumentOutline: 'D',
  DocumentText: 'D',
  DocumentTextOutline: 'D',
  Download: 'D',
  DownloadOutline: 'D',
  Duplicate: 'D',
  DuplicateOutline: 'D',
  Ear: 'E',
  EarOutline: 'E',
  Earth: 'E',
  EarthOutline: 'E',
  Egg: 'E',
  EggOutline: 'E',
  ExtensionPuzzle: 'E',
  ExtensionPuzzleOutline: 'E',
  Eye: 'E',
  EyeOff: 'E',
  EyeOffOutline: 'E',
  EyeOutline: 'E',
  Eyedrop: 'E',
  EyedropOutline: 'E',
  Female: 'F',
  FemaleOutline: 'F',
  FileTray: 'F',
  FileTrayFull: 'F',
  FileTrayFullOutline: 'F',
  FileTrayOutline: 'F',
  Film: 'F',
  FilmOutline: 'F',
  FingerPrintOutline: 'F',
  Fitness: 'F',
  FitnessOutline: 'F',
  Flag: 'F',
  FlagOutline: 'F',
  Flame: 'F',
  FlameOutline: 'F',
  Flask: 'F',
  FlaskOutline: 'F',
  Folder: 'F',
  FolderOutline: 'F',
  Football: 'F',
  FootballOutline: 'F',
  Gift: 'G',
  GiftOutline: 'G',
  GitBranch: 'G',
  GitBranchOutline: 'G',
  GitCommit: 'G',
  GitCommitOutline: 'G',
  GitCompare: 'G',
  GitCompareOutline: 'G',
  GitMerge: 'G',
  GitMergeOutline: 'G',
  GitNetwork: 'G',
  GitNetworkOutline: 'G',
  GitPullRequest: 'G',
  GitPullRequestOutline: 'G',
  Glasses: 'G',
  GlassesOutline: 'G',
  Globe: 'G',
  GlobeOutline: 'G',
  Golf: 'G',
  GolfOutline: 'G',
  Hammer: 'H',
  HammerOutline: 'H',
  HandLeftOutline: 'H',
  HandLeftSharp: 'H',
  HandRightOutline: 'H',
  HandRightSharp: 'H',
  Happy: 'H',
  HappyOutline: 'H',
  Headset: 'H',
  HeadsetOutline: 'H',
  Heart: 'H',
  HeartCircle: 'H',
  HeartCircleOutline: 'H',
  HeartDislike: 'H',
  HeartDislikeOutline: 'H',
  HeartHalf: 'H',
  HeartHalfOutline: 'H',
  HeartOutline: 'H',
  Help: 'H',
  HelpBuoy: 'H',
  HelpBuoyOutline: 'H',
  HelpCircle: 'H',
  HelpCircleOutline: 'H',
  HelpOutline: 'H',
  Home: 'H',
  HomeOutline: 'H',
  Hourglass: 'H',
  HourglassOutline: 'H',
  IceCream: 'I',
  IceCreamOutline: 'I',
  IdCard: 'I',
  IdCardOutline: 'I',
  Image: 'I',
  ImageOutline: 'I',
  Images: 'I',
  ImagesOutline: 'I',
  InformationCircle: 'I',
  InformationCircleOutline: 'I',
  InformationOutline: 'I',
  Key: 'K',
  KeyOutline: 'K',
  Keypad: 'K',
  KeypadOutline: 'K',
  Language: 'L',
  LanguageOutline: 'L',
  Leaf: 'L',
  LeafOutline: 'L',
  Library: 'L',
  LibraryOutline: 'L',
  Link: 'L',
  LinkOutline: 'L',
  List: 'L',
  ListCircle: 'L',
  ListCircleOutline: 'L',
  ListOutline: 'L',
  Location: 'L',
  LocationOutline: 'L',
  LockClosed: 'L',
  LockClosedOutline: 'L',
  LockOpen: 'L',
  LockOpenOutline: 'L',
  LogoAndroid: 'L',
  LogoAngular: 'L',
  LogoApple: 'L',
  LogoBitbucket: 'L',
  LogoBitcoin: 'L',
  LogoBuffer: 'L',
  LogoCapacitor: 'L',
  LogoChrome: 'L',
  LogoCss3: 'L',
  LogoDribbble: 'L',
  LogoDropbox: 'L',
  LogoEdge: 'L',
  LogoElectron: 'L',
  LogoEuro: 'L',
  LogoFacebook: 'L',
  LogoFlickr: 'L',
  LogoFoursquare: 'L',
  LogoGithub: 'L',
  LogoGoogle: 'L',
  LogoGooglePlaystore: 'L',
  LogoHtml5: 'L',
  LogoInstagram: 'L',
  LogoIonic: 'L',
  LogoIonitron: 'L',
  LogoJavascript: 'L',
  LogoLinkedin: 'L',
  LogoNodejs: 'L',
  LogoPinterest: 'L',
  LogoPwa: 'L',
  LogoPython: 'L',
  LogoReddit: 'L',
  LogoRss: 'L',
  LogoSass: 'L',
  LogoSkype: 'L',
  LogoSlack: 'L',
  LogoSnapchat: 'L',
  LogoStackoverflow: 'L',
  LogoSteam: 'L',
  LogoTiktok: 'L',
  LogoTumblr: 'L',
  LogoTux: 'L',
  LogoTwitch: 'L',
  LogoTwitter: 'L',
  LogoUsd: 'L',
  LogoVenmo: 'L',
  LogoVercel: 'L',
  LogoVimeo: 'L',
  LogoVue: 'L',
  LogoWebComponent: 'L',
  LogoWechat: 'L',
  LogoWhatsapp: 'L',
  LogoWindows: 'L',
  LogoWordpress: 'L',
  LogoXbox: 'L',
  LogoXing: 'L',
  LogoYahoo: 'L',
  LogoYen: 'L',
  LogoYoutube: 'L',
  Magnet: 'M',
  MagnetOutline: 'M',
  Mail: 'M',
  MailOpen: 'M',
  MailOpenOutline: 'M',
  MailOutline: 'M',
  MailUnread: 'M',
  MailUnreadOutline: 'M',
  Male: 'M',
  MaleOutline: 'M',
  Man: 'M',
  ManOutline: 'M',
  Map: 'M',
  MapOutline: 'M',
  Menu: 'M',
  MenuOutline: 'M',
  Moon: 'M',
  MoonOutline: 'M',
  MusicalNote: 'M',
  MusicalNoteOutline: 'M',
  Nuclear: 'N',
  NuclearOutline: 'N',
  Nutrition: 'N',
  NutritionOutline: 'N',
  Open: 'O',
  OpenOutline: 'O',
  Options: 'O',
  OptionsOutline: 'O',
  PaperPlane: 'P',
  PaperPlaneOutline: 'P',
  PartlySunny: 'P',
  PartlySunnyOutline: 'P',
  Pause: 'P',
  PauseCircle: 'P',
  PauseCircleOutline: 'P',
  PauseOutline: 'P',
  Paw: 'P',
  PawOutline: 'P',
  Pencil: 'P',
  PencilOutline: 'P',
  People: 'P',
  PeopleCircle: 'P',
  PeopleCircleOutline: 'P',
  PeopleOutline: 'P',
  Person: 'P',
  PersonAdd: 'P',
  PersonAddOutline: 'P',
  PersonCircle: 'P',
  PersonCircleOutline: 'P',
  PersonOutline: 'P',
  Pin: 'P',
  PinOutline: 'P',
  Pint: 'P',
  PintOutline: 'P',
  Pizza: 'P',
  PizzaOutline: 'P',
  Planet: 'P',
  PlanetOutline: 'P',
  Play: 'P',
  PlayBackCircle: 'P',
  PlayBackCircleOutline: 'P',
  PlayBackOutline: 'P',
  PlayCircle: 'P',
  PlayCircleOutline: 'P',
  PlayForward: 'P',
  PlayForwardCircle: 'P',
  PlayForwardCircleOutline: 'P',
  PlayForwardOutline: 'P',
  PlayOutline: 'P',
  PlaySkipBack: 'P',
  PlaySkipBackCircle: 'P',
  PlaySkipBackCircleOutline: 'P',
  PlaySkipBackOutline: 'P',
  PlaySkipForward: 'P',
  PlaySkipForwardCircle: 'P',
  PlaySkipForwardCircleOutline: 'P',
  PlaySkipForwardOutline: 'P',
  Pricetag: 'P',
  PricetagOutline: 'P',
  Pricetags: 'P',
  PricetagsOutline: 'P',
  Print: 'P',
  PrintOutline: 'P',
  Push: 'P',
  PushOutline: 'P',
  Rainy: 'R',
  RainyOutline: 'R',
  Reader: 'R',
  ReaderOutline: 'R',
  Receipt: 'R',
  ReceiptOutline: 'R',
  Refresh: 'R',
  RefreshCircle: 'R',
  RefreshCircleOutline: 'R',
  RefreshOutline: 'R',
  Reload: 'R',
  ReloadCircle: 'R',
  ReloadCircleOutline: 'R',
  ReloadOutline: 'R',
  Remove: 'R',
  RemoveCircle: 'R',
  RemoveCircleOutline: 'R',
  RemoveOutline: 'R',
  ReorderThree: 'R',
  ReorderThreeOutline: 'R',
  ReorderTwo: 'R',
  ReorderTwoOutline: 'R',
  Repeat: 'R',
  RepeatOutline: 'R',
  Restaurant: 'R',
  RestaurantOutline: 'R',
  ReturnDownBack: 'R',
  ReturnDownBackOutline: 'R',
  ReturnDownForward: 'R',
  ReturnDownForwardOutline: 'R',
  ReturnUpBack: 'R',
  ReturnUpBackOutline: 'R',
  ReturnUpForward: 'R',
  ReturnUpForwardOutline: 'R',
  Ribbon: 'R',
  RibbonOutline: 'R',
  Rocket: 'R',
  RocketOutline: 'R',
  Rose: 'R',
  RoseOutline: 'R',
  Sad: 'S',
  SadOutline: 'S',
  Save: 'S',
  SaveOutline: 'S',
  School: 'S',
  SchoolOutline: 'S',
  Search: 'S',
  SearchCircle: 'S',
  SearchCircleOutline: 'S',
  SearchOutline: 'S',
  Send: 'S',
  SendOutline: 'S',
  Settings: 'S',
  SettingsOutline: 'S',
  Share: 'S',
  ShareOutline: 'S',
  ShareSocial: 'S',
  ShareSocialOutline: 'S',
  ShieldCheckmark: 'S',
  ShieldCheckmarkOutline: 'S',
  ShieldOutline: 'S',
  ShieldSharp: 'S',
  Shirt: 'S',
  ShirtOutline: 'S',
  Shuffle: 'S',
  ShuffleOutline: 'S',
  Skull: 'S',
  SkullOutline: 'S',
  Snow: 'S',
  SnowOutline: 'S',
  Sparkles: 'S',
  SparklesOutline: 'S',
  Speedometer: 'S',
  SpeedometerOutline: 'S',
  Star: 'S',
  StarHalf: 'S',
  StarHalfOutline: 'S',
  StarOutline: 'S',
  Stop: 'S',
  StopCircle: 'S',
  StopCircleOutline: 'S',
  StopOutline: 'S',
  Storefront: 'S',
  StorefrontOutline: 'S',
  Subway: 'S',
  SubwayOutline: 'S',
  Sunny: 'S',
  SunnyOutline: 'S',
  SwapHorizontal: 'S',
  SwapHorizontalOutline: 'S',
  SwapVertical: 'S',
  SwapVerticalOutline: 'S',
  SwapVerticalSharp: 'S',
  Sync: 'S',
  SyncCircle: 'S',
  SyncCircleOutline: 'S',
  SyncOutline: 'S',
  Tennisball: 'T',
  TennisballOutline: 'T',
  ThumbsDown: 'T',
  ThumbsDownOutline: 'T',
  ThumbsUp: 'T',
  ThumbsUpOutline: 'T',
  Thunderstorm: 'T',
  ThunderstormOutline: 'T',
  Ticket: 'T',
  TicketOutline: 'T',
  Time: 'T',
  TimeOutline: 'T',
  TimeSharp: 'T',
  Timer: 'T',
  TimerOutline: 'T',
  Train: 'T',
  TrainOutline: 'T',
  Transgender: 'T',
  TransgenderOutline: 'T',
  Trash: 'T',
  TrashBin: 'T',
  TrashBinOutline: 'T',
  TrashOutline: 'T',
  TrendingDown: 'T',
  TrendingDownOutline: 'T',
  TrendingUp: 'T',
  TrendingUpOutline: 'T',
  Trophy: 'T',
  TrophyOutline: 'T',
  Umbrella: 'U',
  UmbrellaOutline: 'U',
  Unlink: 'U',
  UnlinkOutline: 'U',
  Walk: 'W',
  WalkOutline: 'W',
  Wallet: 'W',
  WalletOutline: 'W',
  Warning: 'W',
  WarningOutline: 'W',
  Water: 'W',
  WaterOutline: 'W',
  Wine: 'W',
  WineOutline: 'W',
  Woman: 'W',
  WomanOutline: 'W'
}

export const coreBucketLoaders: Record<string, () => Promise<Record<string, Component>>> = {
  A: () => import('./icons-registry-core-buckets/A').then((m) => m.icons),
  B: () => import('./icons-registry-core-buckets/B').then((m) => m.icons),
  C: () => import('./icons-registry-core-buckets/C').then((m) => m.icons),
  D: () => import('./icons-registry-core-buckets/D').then((m) => m.icons),
  E: () => import('./icons-registry-core-buckets/E').then((m) => m.icons),
  F: () => import('./icons-registry-core-buckets/F').then((m) => m.icons),
  G: () => import('./icons-registry-core-buckets/G').then((m) => m.icons),
  H: () => import('./icons-registry-core-buckets/H').then((m) => m.icons),
  I: () => import('./icons-registry-core-buckets/I').then((m) => m.icons),
  K: () => import('./icons-registry-core-buckets/K').then((m) => m.icons),
  L: () => import('./icons-registry-core-buckets/L').then((m) => m.icons),
  M: () => import('./icons-registry-core-buckets/M').then((m) => m.icons),
  N: () => import('./icons-registry-core-buckets/N').then((m) => m.icons),
  O: () => import('./icons-registry-core-buckets/O').then((m) => m.icons),
  P: () => import('./icons-registry-core-buckets/P').then((m) => m.icons),
  R: () => import('./icons-registry-core-buckets/R').then((m) => m.icons),
  S: () => import('./icons-registry-core-buckets/S').then((m) => m.icons),
  T: () => import('./icons-registry-core-buckets/T').then((m) => m.icons),
  U: () => import('./icons-registry-core-buckets/U').then((m) => m.icons),
  W: () => import('./icons-registry-core-buckets/W').then((m) => m.icons)
}
