// 文件用途：标注 cmd\gmqttd\plugins.go 的生成或模拟代码维护边界。
// 核心逻辑：由 protoc、grpc-gateway、MockGen 或插件生成流程产出服务桩、序列化代码或测试 mock。
// 关键注意事项：除本维护说明外不要手改生成逻辑，业务变更应修改源 proto、接口或生成脚本后重新生成。
// 重构建议：后续可把生成命令和校验脚本固化到文档或 CI，避免维护说明在再生成时丢失。

//go:generate sh -c "cd ../../ && go run plugin_generate.go"
// generated by plugin_generate.go; DO NOT EDIT

package main

import (
	_ "github.com/DrmagicE/gmqtt/plugin/admin"
	_ "github.com/DrmagicE/gmqtt/plugin/aetherlink"
	_ "github.com/DrmagicE/gmqtt/plugin/auth"
	_ "github.com/DrmagicE/gmqtt/plugin/federation"
	_ "github.com/DrmagicE/gmqtt/plugin/prometheus"
)
