/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteComponent } from "vue-router";
import type { LastLevelRouteKey, RouteLayout } from "@elegant-router/types";

import BaseLayout from "@/layouts/base-layout/index.vue";
import BlankLayout from "@/layouts/blank-layout/index.vue";

export const layouts: Record<RouteLayout, RouteComponent | (() => Promise<RouteComponent>)> = {
  base: BaseLayout,
  blank: BlankLayout,
};

export const views: Record<LastLevelRouteKey, RouteComponent | (() => Promise<RouteComponent>)> = {
  403: () => import("@/views/_builtin/403/index.vue"),
  404: () => import("@/views/_builtin/404/index.vue"),
  500: () => import("@/views/_builtin/500/index.vue"),
  legal: () => import("@/views/_builtin/legal/index.vue"),
  login: () => import("@/views/_builtin/login/index.vue"),
  "alarm_notification-group": () => import("@/views/alarm/notification-group/index.vue"),
  "alarm_notification-record": () => import("@/views/alarm/notification-record/index.vue"),
  "alarm_rdi-overview": () => import("@/views/alarm/rdi-overview/index.vue"),
  "alarm_warning-message": () => import("@/views/alarm/warning-message/index.vue"),
  apply_plugin: () => import("@/views/apply/plugin/index.vue"),
  apply_service: () => import("@/views/apply/service/index.vue"),
  "automation_linkage-edit": () => import("@/views/automation/linkage-edit/index.vue"),
  "automation_scene-edit": () => import("@/views/automation/scene-edit/index.vue"),
  "automation_scene-linkage": () => import("@/views/automation/scene-linkage/index.vue"),
  "automation_scene-manage": () => import("@/views/automation/scene-manage/index.vue"),
  "automation_rule-chain": () => import("@/views/automation/rule-chain/index.vue"),
  "automation_rule-chain-edit": () => import("@/views/automation/rule-chain/modules/editor.vue"),
  "dashboard_rdi-overview": () => import("@/views/dashboard/rdi-overview/index.vue"),
  dashboard_workbench: () => import("@/views/dashboard/workbench/index.vue"),
  dashboard_workspace: () => import("@/views/dashboard/workspace/index.vue"),
  "device-details-app": () => import("@/views/device-details-app/index.vue"),
  "device_command-center": () => import("@/views/device/command-center/index.vue"),
  "device_config-detail": () => import("@/views/device/config-detail/index.vue"),
  "device_config-edit": () => import("@/views/device/config-edit/index.vue"),
  device_config: () => import("@/views/device/config/index.vue"),
  "device_details-child": () => import("@/views/device/details-child/index.vue"),
  device_details: () => import("@/views/device/details/index.vue"),
  "device_grouping-details": () => import("@/views/device/grouping-details/index.vue"),
  device_grouping: () => import("@/views/device/grouping/index.vue"),
  device_manage: () => import("@/views/device/manage/index.vue"),
  "device_service-access": () => import("@/views/device/service-access/index.vue"),
  "device_service-details": () => import("@/views/device/service-details/index.vue"),
  device_share: () => import("@/views/device/share/index.vue"),
  "device_shared-with-me": () => import("@/views/device/shared-with-me/index.vue"),
  device_template: () => import("@/views/device/template/index.vue"),
  home: () => import("@/views/home/index.vue"),
  management_api: () => import("@/views/management/api/index.vue"),
  management_auth: () => import("@/views/management/auth/index.vue"),
  management_notification: () => import("@/views/management/notification/index.vue"),
  management_role: () => import("@/views/management/role/index.vue"),
  management_setting: () => import("@/views/management/setting/index.vue"),
  management_user: () => import("@/views/management/user/index.vue"),
  "personal-center": () => import("@/views/personal-center/index.vue"),
  "product_update-ota": () => import("@/views/product/update-ota/index.vue"),
  "product_update-package": () => import("@/views/product/update-package/index.vue"),
  "system-management-user_equipment-map": () => import("@/views/system-management-user/equipment-map/index.vue"),
  "system-management-user_system-log": () => import("@/views/system-management-user/system-log/index.vue"),
  "visualization_native-board": () => import("@/views/visualization/native-board/index.vue"),
  "visualization_native-board-editor": () => import("@/views/visualization/native-board-editor/index.vue"),
  "visualization_native-boards": () => import("@/views/visualization/native-boards/index.vue"),
  "visualization_thingsvis-dashboards": () => import("@/views/visualization/thingsvis-dashboards/index.vue"),
  "visualization_thingsvis-editor": () => import("@/views/visualization/thingsvis-editor/index.vue"),
  "visualization_thingsvis-menu-dashboard": () => import("@/views/visualization/thingsvis-menu-dashboard/index.vue"),
  "visualization_thingsvis-preview": () => import("@/views/visualization/thingsvis-preview/index.vue"),
  visualization_thingsvis: () => import("@/views/visualization/thingsvis/index.vue"),
};
