/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

import { systemIntroRoutes, applicationRoutes, authRoutes, adminRoutes, managementRoutes, personalRoutes, systemManagementRoutes } from './systemRoutes';
import { alarmRoutes, automationRoutes } from './automationRoutes';
import { dashboardRoutes, visualizationRoutes } from './visualizationRoutes';
import { deviceRoutes, deviceAppRoutes, productRoutes } from './deviceRoutes';
import { marketRoutes } from './marketRoutes';
import { customerRoutes } from './customerRoutes';
import { billingRoutes } from './billingRoutes';
import { mediaRoutes } from './mediaRoutes';
import { integrationRoutes } from './integrationRoutes';
import { mobileAppRoutes } from './mobileAppRoutes';
import { schedulerRoutes } from './schedulerRoutes';

export const generatedRoutes: GeneratedRoute[] = [
  ...systemIntroRoutes,
  ...alarmRoutes,
  ...applicationRoutes,
  ...automationRoutes,
  ...dashboardRoutes,
  ...deviceRoutes,
  ...deviceAppRoutes,
  ...authRoutes,
  ...adminRoutes,
  ...managementRoutes,
  ...personalRoutes,
  ...productRoutes,
  ...systemManagementRoutes,
  ...visualizationRoutes,
  ...marketRoutes,
  ...customerRoutes,
  ...billingRoutes,
  ...mediaRoutes,
  ...integrationRoutes,
  ...mobileAppRoutes,
  ...schedulerRoutes
];
