/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router

import type { GeneratedRoute } from '@elegant-router/types';

import { systemIntroRoutes, applicationRoutes, authRoutes, adminRoutes, managementRoutes, personalRoutes, systemManagementRoutes } from './systemRoutes';
import { alarmRoutes, automationRoutes } from './automationRoutes';
import { dashboardRoutes, visualizationRoutes } from './visualizationRoutes';
import { deviceRoutes, deviceAppRoutes, productRoutes } from './deviceRoutes';

export const generatedRoutes: GeneratedRoute[] = [
  ...systemIntroRoutes,
  ...alarmRoutes,
  ...applicationRoutes,
  ...automationRoutes,
  ...dashboardRoutes,
  ...deviceRoutes,
  ...deviceAppRoutes,
  ...authRoutes,
  ...adminRoutes,
  ...managementRoutes,
  ...personalRoutes,
  ...productRoutes,
  ...systemManagementRoutes,
  ...visualizationRoutes
];
