/* eslint-disable */
/* prettier-ignore */
// Generated by elegant-router
// Read more: https://github.com/soybeanjs/elegant-router

import type { RouteRecordRaw, RouteComponent } from 'vue-router';
import type { ElegantConstRoute } from '@elegant-router/vue';
import type { RouteMap, RouteKey, RoutePath } from '@elegant-router/types';

/**
 * transform elegant const routes to vue routes
 * @param routes elegant const routes
 * @param layouts layout components
 * @param views view components
 */
export function transformElegantRoutesToVueRoutes(
  routes: ElegantConstRoute[],
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  return routes.flatMap(route => transformElegantRouteToVueRoute(route, layouts, views));
}

/**
 * transform elegant route to vue route
 * @param route elegant const route
 * @param layouts layout components
 * @param views view components
 */
function transformElegantRouteToVueRoute(
  route: ElegantConstRoute,
  layouts: Record<string, RouteComponent | (() => Promise<RouteComponent>)>,
  views: Record<string, RouteComponent | (() => Promise<RouteComponent>)>
) {
  const LAYOUT_PREFIX = 'layout.';
  const VIEW_PREFIX = 'view.';
  const ROUTE_DEGREE_SPLITTER = '_';
  const FIRST_LEVEL_ROUTE_COMPONENT_SPLIT = '$';

  function isLayout(component: string) {
    return component.startsWith(LAYOUT_PREFIX);
  }

  function getLayoutName(component: string) {
    const layout = component.replace(LAYOUT_PREFIX, '');

    if(!layouts[layout]) {
      throw new Error(`Layout component "${layout}" not found`);
    }

    return layout;
  }

  function isView(component: string) {
    return component.startsWith(VIEW_PREFIX);
  }

  function getViewName(component: string) {
    const view = component.replace(VIEW_PREFIX, '');

    if(!views[view]) {
      throw new Error(`View component "${view}" not found`);
    }

    return view;
  }

  function isFirstLevelRoute(item: ElegantConstRoute) {
    return !item.name.includes(ROUTE_DEGREE_SPLITTER);
  }

  function isSingleLevelRoute(item: ElegantConstRoute) {
    return isFirstLevelRoute(item) && !item.children?.length;
  }

  function getSingleLevelRouteComponent(component: string) {
    const [layout, view] = component.split(FIRST_LEVEL_ROUTE_COMPONENT_SPLIT);

    return {
      layout: getLayoutName(layout),
      view: getViewName(view)
    };
  }

  const vueRoutes: RouteRecordRaw[] = [];

  // add props: true to route
  if (route.path.includes(':') && !route.props) {
    route.props = true;
  }

  const { name, path, component, children, ...rest } = route;

  const vueRoute = { name, path, ...rest } as RouteRecordRaw;

  try {
    if (component) {
      if (isSingleLevelRoute(route)) {
        const { layout, view } = getSingleLevelRouteComponent(component);

        const singleLevelRoute: RouteRecordRaw = {
          path,
          component: layouts[layout],
          children: [
            {
              name,
              path: '',
              component: views[view],
              ...rest
            } as RouteRecordRaw
          ]
        };

        return [singleLevelRoute];
      }

      if (isLayout(component)) {
        const layoutName = getLayoutName(component);

        vueRoute.component = layouts[layoutName];
      }

      if (isView(component)) {
        const viewName = getViewName(component);

        vueRoute.component = views[viewName];
      }

    }
  } catch (error: any) {
    console.error(`Error transforming route "${route.name}": ${error.toString()}`);
    return [];
  }


  // add redirect to child
  if (children?.length && !vueRoute.redirect) {
    vueRoute.redirect = {
      name: children[0].name
    };
  }

  if (children?.length) {
    const childRoutes = children.flatMap(child => transformElegantRouteToVueRoute(child, layouts, views));

    if(isFirstLevelRoute(route)) {
      vueRoute.children = childRoutes;
    } else {
      vueRoutes.push(...childRoutes);
    }
  }

  vueRoutes.unshift(vueRoute);

  return vueRoutes;
}

/**
 * map of route name and route path
 */
const routeMap: RouteMap = {
  "root": "/",
  "not-found": "/:pathMatch(.*)*",
  "403": "/403",
  "404": "/404",
  "500": "/500",
  "alarm": "/alarm",
  "alarm_notification-group": "/alarm/notification-group",
  "alarm_notification-record": "/alarm/notification-record",
  "alarm_rdi-overview": "/alarm/rdi-overview",
  "alarm_warning-message": "/alarm/warning-message",
  "apply": "/apply",
  "apply_plugin": "/apply/plugin",
  "apply_service": "/apply/service",
  "automation": "/automation",
  "automation_linkage-edit": "/automation/linkage-edit",
  "automation_scene-edit": "/automation/scene-edit",
  "automation_scene-linkage": "/automation/scene-linkage",
  "automation_scene-manage": "/automation/scene-manage",
  "automation_rule-chain": "/automation/rule-chain",
  "automation_rule-chain-edit": "/automation/rule-chain/edit",
  "dashboard": "/dashboard",
  "dashboard_rdi-overview": "/dashboard/rdi-overview",
  "dashboard_workbench": "/dashboard/workbench",
  "dashboard_workspace": "/dashboard/workspace",
  "device": "/device",
  "device_asset": "/device/asset",
  "device_command-center": "/device/command-center",
  "device_config": "/device/template",
  "device_config-detail": "/device/config-detail",
  "device_config-edit": "/device/config-edit",
  "device_details": "/device/details",
  "device_details-child": "/device/details-child",
  "device_grouping": "/device/grouping",
  "device_grouping-details": "/device/grouping-details",
  "device_manage": "/device/manage",
  "device_service-access": "/device/service-access",
  "device_service-details": "/device/service-details",
  "device_share": "/device/share",
  "device_shared-with-me": "/device/shared-with-me",
  "device_template": "/device/thingsmodel",
  "device-details-app": "/device-details-app",
  "home": "/home",
  "legal": "/legal",
  "login": "/login/:module(pwd-login|code-login|register|register-email|register-super-admin|reset-pwd|bind-wechat)?",
  "management": "/management",
  "management_entity-version": "/management/entity-version",
  "management_api": "/management/api",
  "management_auth": "/management/auth",
  "management_entity-version": "/management/entity-version",
  "management_notification": "/management/notification",
  "management_role": "/management/role",
  "management_setting": "/management/setting",
  "management_user": "/management/user",
  "personal-center": "/personal-center",
  "product": "/product",
  "product_update-ota": "/product/update-ota",
  "product_update-package": "/product/update-package",
  "product_pre-register": "/product/pre-register",
  "system-management-user": "/system-management-user",
  "system-management-user_equipment-map": "/system-management-user/equipment-map",
  "system-management-user_system-log": "/system-management-user/system-log",
  "visualization": "/visualization",
  "visualization_native-board": "/visualization/native-board",
  "visualization_native-board-editor": "/visualization/native-board-editor",
  "visualization_native-boards": "/visualization/native-boards",
  "visualization_thingsvis": "/visualization/thingsvis",
  "visualization_thingsvis-dashboards": "/visualization/thingsvis-dashboards",
  "visualization_thingsvis-editor": "/visualization/thingsvis-editor",
  "visualization_thingsvis-menu-dashboard": "/visualization/thingsvis-menu-dashboard",
  "visualization_thingsvis-preview": "/visualization/thingsvis-preview"
};

/**
 * get route path by route name
 * @param name route name
 */
export function getRoutePath<T extends RouteKey>(name: T) {
  return routeMap[name];
}

/**
 * get route name by route path
 * @param path route path
 */
export function getRouteName(path: RoutePath) {
  const routeEntries = Object.entries(routeMap) as [RouteKey, RoutePath][];

  const routeName: RouteKey | null = routeEntries.find(([, routePath]) => routePath === path)?.[0] || null;

  return routeName;
}
